import { homedir } from "node:os";
import { join, resolve } from "node:path";

import type { RuntimeBoardData } from "../core";
import { createTaggedLogger, findCardInBoard, normalizeDiagnosticErrorClass } from "../core";
import type { ProjectBoardCommandService } from "../state";
import type { TerminalSessionManager } from "../terminal";
import { readCodexThreadNames } from "../title/codex-thread-names";

const log = createTaggedLogger("codex-task-title");
const POLL_INTERVAL_MS = 2_000;

type ManagedProject = {
	projectId: string;
	projectPath: string | null;
	terminalManager: Pick<TerminalSessionManager, "store" | "getTaskSessionProcessIdentity">;
};

export interface CodexTaskTitleMonitorDependencies {
	listManagedProjects: () => ManagedProject[];
	loadBoard: (projectId: string) => Promise<RuntimeBoardData>;
	boardCommands: Pick<ProjectBoardCommandService, "setGeneratedTaskTitle">;
	publishTitleUpdated: (input: { projectId: string; taskId: string; title: string }) => Promise<void> | void;
	readThreadNames?: typeof readCodexThreadNames;
}

/** Native TUIs own their app-server connection. Follow their persisted name updates read-only. */
export function createCodexTaskTitleMonitor(deps: CodexTaskTitleMonitorDependencies) {
	let closed = false;
	let timer: NodeJS.Timeout | null = null;
	let pending: Promise<void> | null = null;
	// Treat polling as name-change delivery, so an unchanged provider name does not undo explicit regeneration.
	const observedNames = new WeakMap<ManagedProject["terminalManager"], Map<string, string>>();

	async function refreshProject(project: ManagedProject): Promise<void> {
		const { projectId, projectPath, terminalManager: manager } = project;
		if (!projectPath) return;
		const sessions = manager.store
			.listSummaries()
			.filter(
				(session) =>
					session.agentId === "codex" &&
					session.resumeSessionId &&
					manager.getTaskSessionProcessIdentity(session.taskId),
			);
		const observations = observedNames.get(manager) ?? new Map<string, string>();
		observedNames.set(manager, observations);
		const liveTaskIds = new Set(sessions.map((session) => session.taskId));
		for (const taskId of observations.keys()) if (!liveTaskIds.has(taskId)) observations.delete(taskId);
		if (!sessions.length) return;
		const board = await deps.loadBoard(projectId);
		const groups = new Map<string, Array<{ threadId: string; apply: (title: string) => Promise<void> }>>();
		for (const session of sessions) {
			const card = findCardInBoard(board, session.taskId);
			const identity = manager.getTaskSessionProcessIdentity(session.taskId);
			if (
				!card ||
				!identity ||
				identity.agentId !== "codex" ||
				identity.sessionInstanceId !== session.sessionInstanceId ||
				!session.resumeSessionId
			)
				continue;
			// Missing provenance on a named legacy card is not permission to overwrite it.
			if (card.titleAutoGenerated === false || (card.title !== null && card.titleAutoGenerated !== true)) continue;
			const profile = identity.profileEnvironment;
			const codexHome = resolve(
				session.sessionLaunchPath ?? projectPath,
				profile.CODEX_HOME?.trim() || join(profile.HOME || homedir(), ".codex"),
			);
			const isCurrent = () => {
				if (
					closed ||
					!deps
						.listManagedProjects()
						.some(
							(current) =>
								current.projectId === projectId &&
								current.projectPath === projectPath &&
								current.terminalManager === manager,
						)
				)
					return false;
				const current = manager.store.getSummary(session.taskId);
				const process = manager.getTaskSessionProcessIdentity(session.taskId);
				return (
					current?.agentId === "codex" &&
					current.sessionInstanceId === session.sessionInstanceId &&
					current.resumeSessionId === session.resumeSessionId &&
					process?.sessionInstanceId === identity.sessionInstanceId
				);
			};
			const group = groups.get(codexHome) ?? [];
			group.push({
				threadId: session.resumeSessionId,
				apply: async (title) => {
					if (!isCurrent()) return;
					const observation = JSON.stringify([
						card.createdAt,
						identity.sessionInstanceId,
						session.resumeSessionId,
						codexHome,
						title,
					]);
					if (observations.get(card.id) === observation) return;
					if (title === card.title) {
						observations.set(card.id, observation);
						return;
					}
					const result = await deps.boardCommands.setGeneratedTaskTitle(
						{ projectId, projectPath },
						card.id,
						card.createdAt,
						title,
						Date.now(),
						{ expectedTitle: card.title, expectedAutoGenerated: card.titleAutoGenerated === true, isCurrent },
					);
					if (result.acceptedChange) {
						observations.set(card.id, observation);
						await deps.publishTitleUpdated({ projectId, taskId: card.id, title });
					}
				},
			});
			groups.set(codexHome, group);
		}
		for (const [profile, targets] of groups) {
			const names = await (deps.readThreadNames ?? readCodexThreadNames)(
				profile,
				new Set(targets.map((target) => target.threadId)),
			);
			for (const target of targets) {
				const name = names.get(target.threadId);
				if (name) await target.apply(name);
			}
		}
	}

	function refresh(): Promise<void> {
		if (closed) return Promise.resolve();
		if (pending) return pending;
		pending = (async () => {
			for (const project of deps.listManagedProjects()) {
				if (closed) break;
				try {
					await refreshProject(project);
				} catch (error) {
					log.debug("Codex title metadata unavailable", {
						projectId: project.projectId,
						errorClass: error instanceof Error ? normalizeDiagnosticErrorClass(error.name) : "UnknownError",
					});
				}
			}
		})().finally(() => {
			pending = null;
		});
		return pending;
	}

	function schedule(): void {
		if (closed || timer) return;
		timer = setTimeout(() => {
			timer = null;
			void refresh().finally(schedule);
		}, POLL_INTERVAL_MS);
		timer.unref();
	}

	return {
		start: schedule,
		refresh,
		async close(): Promise<void> {
			closed = true;
			if (timer) clearTimeout(timer);
			timer = null;
			await pending;
		},
	};
}
