/**
 * Factory functions for RuntimeStateStream messages.
 *
 * Each function constructs one message type from the discriminated union.
 * Centralizing construction here replaces inline object literals scattered
 * across RuntimeStateHub, making call sites one-liners and keeping the
 * message shape in one place.
 */
import type {
	LogEntry,
	LogLevel,
	RuntimeProjectSummary,
	RuntimeStateStreamDebugLogBatchMessage,
	RuntimeStateStreamDebugLoggingStateMessage,
	RuntimeStateStreamErrorMessage,
	RuntimeStateStreamProjectsMessage,
	RuntimeStateStreamSnapshotMessage,
	RuntimeStateStreamTaskBaseRefUpdatedMessage,
	RuntimeStateStreamTaskNotificationMessage,
	RuntimeStateStreamTaskReadyForReviewMessage,
	RuntimeStateStreamTaskSessionsMessage,
	RuntimeStateStreamTaskTitleUpdatedMessage,
	RuntimeStateStreamTaskWorkingDirectoryUpdatedMessage,
	RuntimeStateStreamWorkspaceMetadataMessage,
	RuntimeStateStreamWorkspaceStateMessage,
	RuntimeTaskSessionSummary,
	RuntimeWorkspaceMetadata,
	RuntimeWorkspaceStateResponse,
} from "../core";

export function buildSnapshotMessage(
	currentProjectId: string | null,
	projects: RuntimeProjectSummary[],
	workspaceState: RuntimeWorkspaceStateResponse | null,
): RuntimeStateStreamSnapshotMessage {
	return {
		type: "snapshot",
		currentProjectId,
		projects,
		workspaceState,
		workspaceMetadata: null,
	};
}

export function buildWorkspaceStateUpdatedMessage(
	workspaceId: string,
	workspaceState: RuntimeWorkspaceStateResponse,
): RuntimeStateStreamWorkspaceStateMessage {
	return {
		type: "workspace_state_updated",
		workspaceId,
		workspaceState,
	};
}

export function buildWorkspaceMetadataUpdatedMessage(
	workspaceId: string,
	workspaceMetadata: RuntimeWorkspaceMetadata,
): RuntimeStateStreamWorkspaceMetadataMessage {
	return {
		type: "workspace_metadata_updated",
		workspaceId,
		workspaceMetadata,
	};
}

export function buildProjectsUpdatedMessage(
	currentProjectId: string | null,
	projects: RuntimeProjectSummary[],
): RuntimeStateStreamProjectsMessage {
	return {
		type: "projects_updated",
		currentProjectId,
		projects,
	};
}

export function buildTaskSessionsUpdatedMessage(
	workspaceId: string,
	summaries: RuntimeTaskSessionSummary[],
): RuntimeStateStreamTaskSessionsMessage {
	return {
		type: "task_sessions_updated",
		workspaceId,
		summaries,
	};
}

export function buildTaskReadyForReviewMessage(
	workspaceId: string,
	taskId: string,
): RuntimeStateStreamTaskReadyForReviewMessage {
	return {
		type: "task_ready_for_review",
		workspaceId,
		taskId,
		triggeredAt: Date.now(),
	};
}

export function buildTaskTitleUpdatedMessage(
	workspaceId: string,
	taskId: string,
	title: string,
	options?: { autoGenerated?: boolean },
): RuntimeStateStreamTaskTitleUpdatedMessage {
	return {
		type: "task_title_updated",
		workspaceId,
		taskId,
		title,
		...(options?.autoGenerated ? { autoGenerated: true } : undefined),
	};
}

export function buildTaskBaseRefUpdatedMessage(
	workspaceId: string,
	taskId: string,
	baseRef: string,
): RuntimeStateStreamTaskBaseRefUpdatedMessage {
	return {
		type: "task_base_ref_updated",
		workspaceId,
		taskId,
		baseRef,
	};
}

export function buildTaskWorkingDirectoryUpdatedMessage(
	workspaceId: string,
	taskId: string,
	workingDirectory: string,
	useWorktree: boolean,
): RuntimeStateStreamTaskWorkingDirectoryUpdatedMessage {
	return {
		type: "task_working_directory_updated",
		workspaceId,
		taskId,
		workingDirectory,
		useWorktree,
	};
}

export function buildTaskNotificationMessage(
	workspaceId: string,
	summaries: RuntimeTaskSessionSummary[],
): RuntimeStateStreamTaskNotificationMessage {
	return {
		type: "task_notification",
		workspaceId,
		summaries,
	};
}

export function buildErrorMessage(message: string): RuntimeStateStreamErrorMessage {
	return {
		type: "error",
		message,
	};
}

export function buildDebugLoggingStateMessage(
	level: LogLevel,
	recentEntries?: LogEntry[],
): RuntimeStateStreamDebugLoggingStateMessage {
	return {
		type: "debug_logging_state",
		level,
		recentEntries,
	};
}

export function buildDebugLogBatchMessage(entries: LogEntry[]): RuntimeStateStreamDebugLogBatchMessage {
	return {
		type: "debug_log_batch",
		entries,
	};
}
