/**
 * Factory functions for RuntimeStateStream messages.
 *
 * Each function constructs one message type from the discriminated union.
 * Centralizing construction here replaces inline object literals scattered
 * across RuntimeStateHub, making call sites one-liners and keeping the
 * message shape in one place.
 */
import type {
	LogEntry,
	LogLevel,
	RuntimeProjectMetadata,
	RuntimeProjectStateResponse,
	RuntimeProjectSummary,
	RuntimeStateStreamDebugLogBatchMessage,
	RuntimeStateStreamDebugLoggingStateMessage,
	RuntimeStateStreamErrorMessage,
	RuntimeStateStreamProjectMetadataMessage,
	RuntimeStateStreamProjectStateMessage,
	RuntimeStateStreamProjectsMessage,
	RuntimeStateStreamSnapshotMessage,
	RuntimeStateStreamTaskBaseRefUpdatedMessage,
	RuntimeStateStreamTaskNotificationMessage,
	RuntimeStateStreamTaskReadyForReviewMessage,
	RuntimeStateStreamTaskSessionsMessage,
	RuntimeStateStreamTaskTitleUpdatedMessage,
	RuntimeStateStreamTaskWorkingDirectoryUpdatedMessage,
	RuntimeTaskSessionSummary,
} from "../core";

export function buildSnapshotMessage(
	currentProjectId: string | null,
	projects: RuntimeProjectSummary[],
	projectState: RuntimeProjectStateResponse | null,
): RuntimeStateStreamSnapshotMessage {
	return {
		type: "snapshot",
		currentProjectId,
		projects,
		projectState,
		projectMetadata: null,
	};
}

export function buildProjectStateUpdatedMessage(
	projectId: string,
	projectState: RuntimeProjectStateResponse,
): RuntimeStateStreamProjectStateMessage {
	return {
		type: "project_state_updated",
		projectId,
		projectState,
	};
}

export function buildProjectMetadataUpdatedMessage(
	projectId: string,
	projectMetadata: RuntimeProjectMetadata,
): RuntimeStateStreamProjectMetadataMessage {
	return {
		type: "project_metadata_updated",
		projectId,
		projectMetadata,
	};
}

export function buildProjectsUpdatedMessage(
	currentProjectId: string | null,
	projects: RuntimeProjectSummary[],
): RuntimeStateStreamProjectsMessage {
	return {
		type: "projects_updated",
		currentProjectId,
		projects,
	};
}

export function buildTaskSessionsUpdatedMessage(
	projectId: string,
	summaries: RuntimeTaskSessionSummary[],
): RuntimeStateStreamTaskSessionsMessage {
	return {
		type: "task_sessions_updated",
		projectId,
		summaries,
	};
}

export function buildTaskReadyForReviewMessage(
	projectId: string,
	taskId: string,
): RuntimeStateStreamTaskReadyForReviewMessage {
	return {
		type: "task_ready_for_review",
		projectId,
		taskId,
		triggeredAt: Date.now(),
	};
}

export function buildTaskTitleUpdatedMessage(
	projectId: string,
	taskId: string,
	title: string,
	options?: { autoGenerated?: boolean },
): RuntimeStateStreamTaskTitleUpdatedMessage {
	return {
		type: "task_title_updated",
		projectId,
		taskId,
		title,
		...(options?.autoGenerated ? { autoGenerated: true } : undefined),
	};
}

export function buildTaskBaseRefUpdatedMessage(
	projectId: string,
	taskId: string,
	baseRef: string,
): RuntimeStateStreamTaskBaseRefUpdatedMessage {
	return {
		type: "task_base_ref_updated",
		projectId,
		taskId,
		baseRef,
	};
}

export function buildTaskWorkingDirectoryUpdatedMessage(
	projectId: string,
	taskId: string,
	workingDirectory: string,
	useWorktree: boolean,
): RuntimeStateStreamTaskWorkingDirectoryUpdatedMessage {
	return {
		type: "task_working_directory_updated",
		projectId,
		taskId,
		workingDirectory,
		useWorktree,
	};
}

export function buildTaskNotificationMessage(
	projectId: string,
	summaries: RuntimeTaskSessionSummary[],
): RuntimeStateStreamTaskNotificationMessage {
	return {
		type: "task_notification",
		projectId,
		summaries,
	};
}

export function buildErrorMessage(message: string): RuntimeStateStreamErrorMessage {
	return {
		type: "error",
		message,
	};
}

export function buildDebugLoggingStateMessage(
	level: LogLevel,
	recentEntries?: LogEntry[],
): RuntimeStateStreamDebugLoggingStateMessage {
	return {
		type: "debug_logging_state",
		level,
		recentEntries,
	};
}

export function buildDebugLogBatchMessage(entries: LogEntry[]): RuntimeStateStreamDebugLogBatchMessage {
	return {
		type: "debug_log_batch",
		entries,
	};
}
