import type { ConversationEntry, ConversationReadService } from "../conversation";
import type { RuntimeBoardData, RuntimeTaskSessionSummary } from "../core";
import { findCardInBoard } from "../core";
import type { ProjectBoardCommandScope, ProjectBoardCommandService } from "../state";
import { buildTitleThreadContext, generateTaskTitle } from "../title";

export interface TaskTitleServiceDependencies {
	boardCommands: Pick<ProjectBoardCommandService, "setGeneratedTaskTitle">;
	conversationReads: ConversationReadService;
	loadBoard: (projectId: string) => Promise<RuntimeBoardData>;
	getSessionReader: (scope: ProjectBoardCommandScope) => Promise<(taskId: string) => RuntimeTaskSessionSummary | null>;
	publishTitleUpdated: (input: { projectId: string; taskId: string; title: string }) => Promise<void> | void;
	generateTitle?: typeof generateTaskTitle;
}

/** Shared explicit/automatic regeneration; provider history remains the only transcript store. */
export function createTaskTitleService(deps: TaskTitleServiceDependencies) {
	return {
		async regenerate(
			scope: ProjectBoardCommandScope,
			taskId: string,
			options: { automatic?: boolean; isCurrent?: () => boolean } = {},
		): Promise<{ ok: boolean; title: string | null }> {
			const board = await deps.loadBoard(scope.projectId);
			const card = findCardInBoard(board, taskId);
			const isTrashed = (currentBoard: RuntimeBoardData) =>
				currentBoard.columns.some(
					(column) => column.id === "trash" && column.cards.some((candidate) => candidate.id === taskId),
				);
			if (!card || (options.automatic && (card.titleAutoGenerated !== true || isTrashed(board)))) {
				return { ok: false, title: null };
			}

			const readSession = await deps.getSessionReader(scope);
			const session = readSession(taskId);
			if (options.automatic && (session?.state !== "awaiting_review" || session.reviewReason !== "hook")) {
				return { ok: false, title: null };
			}
			const isCurrent = () => {
				const current = readSession(taskId);
				return (
					options.isCurrent?.() !== false &&
					current?.sessionInstanceId === session?.sessionInstanceId &&
					current?.resumeSessionId === session?.resumeSessionId &&
					(!options.automatic ||
						(current?.lastHookAt === session?.lastHookAt && current?.state === session?.state))
				);
			};
			const history = await deps.conversationReads.readRecent({
				projectId: scope.projectId,
				taskId,
				maxMessages: 24,
			});
			if (!isCurrent()) return { ok: false, title: null };
			const messages = history.entries.filter((entry) => entry.type === "message" && entry.text.trim().length > 0);
			const hasUserMessage = messages.some((entry) => entry.type === "message" && entry.role === "user");
			const finalMessage = session?.latestHookActivity?.finalMessage;
			const summaries = (session?.conversationSummaries ?? []).filter((summary) => summary.text.trim()).slice(-8);
			// Boundaries carry no task context; progress-only windows need the available completed-work summaries.
			const useSummaries = !hasUserMessage && !finalMessage?.trim() && summaries.length > 0;
			const entries: readonly ConversationEntry[] = useSummaries
				? summaries.map((summary, index) => ({
						type: "message",
						role: "assistant",
						id: `summary-${index}`,
						text: summary.text,
					}))
				: messages;
			const hasActivity =
				entries.some((entry) => entry.type === "message" && entry.text.trim()) || Boolean(finalMessage?.trim());
			// Missing history must not replace an evolved title with the opening request.
			if (options.automatic && !hasActivity) return { ok: false, title: null };
			// Long tool-heavy turns may fill the bounded history window with progress messages.
			if (options.automatic && !hasUserMessage && !finalMessage?.trim() && !useSummaries)
				return { ok: false, title: null };
			const context = buildTitleThreadContext({ prompt: card.prompt, entries, finalMessage });
			if (!context) return { ok: false, title: null };
			const title = await (deps.generateTitle ?? generateTaskTitle)(context, {
				mode: hasActivity ? "followup" : "initial",
				currentTitle: card.title,
			});
			if (!title || !isCurrent()) return { ok: false, title: null };
			const result = await deps.boardCommands.setGeneratedTaskTitle(
				scope,
				taskId,
				card.createdAt,
				title,
				Date.now(),
				{
					expectedTitle: card.title,
					expectedAutoGenerated: card.titleAutoGenerated === true,
					isCurrent: (currentBoard) => isCurrent() && (!options.automatic || !isTrashed(currentBoard)),
				},
			);
			const persisted = findCardInBoard(result.state.board, taskId);
			if (
				persisted?.createdAt !== card.createdAt ||
				persisted.title !== title ||
				persisted.titleAutoGenerated !== true
			) {
				return { ok: false, title: null };
			}
			if (result.acceptedChange) await deps.publishTitleUpdated({ projectId: scope.projectId, taskId, title });
			return { ok: true, title };
		},
	};
}
