import type { Dispatch, SetStateAction } from "react";
import { useEffect } from "react";
import type { TaskTitleUpdate } from "@/runtime/use-runtime-state-stream";
import type { BoardData } from "@/types";

interface UseTaskTitleSyncInput {
	latestTaskTitleUpdate: TaskTitleUpdate | null;
	setBoard: Dispatch<SetStateAction<BoardData>>;
}

/**
 * Applies task title updates received via WebSocket to the board.
 * Auto-generated titles are only applied when the card title is still null
 * (not yet set by the user).
 */
export function useTaskTitleSync({ latestTaskTitleUpdate, setBoard }: UseTaskTitleSyncInput): void {
	useEffect(() => {
		if (!latestTaskTitleUpdate) {
			return;
		}
		const { taskId, title, autoGenerated } = latestTaskTitleUpdate;
		setBoard((current) => {
			for (const column of current.columns) {
				const cardIndex = column.cards.findIndex((c) => c.id === taskId);
				if (cardIndex === -1) {
					continue;
				}
				const card = column.cards[cardIndex]!;
				if (card.title === title) {
					return current;
				}
				if (autoGenerated && card.title !== null) {
					return current;
				}
				const updatedCards = [...column.cards];
				updatedCards[cardIndex] = { ...card, title };
				return {
					...current,
					columns: current.columns.map((col) => (col.id === column.id ? { ...col, cards: updatedCards } : col)),
				};
			}
			return current;
		});
	}, [latestTaskTitleUpdate, setBoard]);
}
