import { applyProjectBoardCommands } from "@runtime-board-commands";
import { runtimeProjectBoardCommandBatchEnvelopeSchema } from "@runtime-contract";
import { describe, expect, it } from "vitest";

import { createInitialBoardData } from "@/data/board-data";
import { saveEditedTaskToBoard } from "@/hooks/board/task-editor-drafts";
import {
	addTaskDependency,
	addTaskToColumnWithResult,
	moveTaskToColumn,
	removeTask,
	toggleTaskPinned,
	updateTask,
} from "@/state/board-state";
import type { BoardCard } from "@/types";

import { applyPendingProjectBoardCommands, deriveProjectBoardCommands } from "./project-board-command-sync";

function applyDerived(
	before: ReturnType<typeof createInitialBoardData>,
	after: ReturnType<typeof createInitialBoardData>,
) {
	const commands = deriveProjectBoardCommands(before, after);
	return { commands, board: applyProjectBoardCommands(before, commands).board };
}

describe("project board command sync", () => {
	it("reproduces multi-task creation and final ordering", () => {
		const before = createInitialBoardData();
		const first = addTaskToColumnWithResult(before, "backlog", {
			prompt: "First",
			baseRef: "main",
			agentId: "codex",
			codexOptions: { model: "test-model", reasoningEffort: "high" },
			useWorktree: true,
		});
		const second = addTaskToColumnWithResult(first.board, "backlog", {
			prompt: "Second",
			baseRef: "main",
			agentId: "claude",
			useWorktree: false,
		});

		const result = applyDerived(before, second.board);

		expect(result.commands.filter((command) => command.kind === "create_task")).toHaveLength(2);
		expect(result.board).toEqual(second.board);
	});

	it("preserves Pi ownership when creating a durable backlog task", () => {
		const before = createInitialBoardData();
		const created = addTaskToColumnWithResult(before, "backlog", {
			prompt: "Use Pi",
			baseRef: "main",
			agentId: "pi",
			useWorktree: true,
		});

		const result = applyDerived(before, created.board);

		expect(result.commands).toContainEqual(expect.objectContaining({ kind: "create_task", agentId: "pi" }));
		expect(result.board).toEqual(created.board);
	});

	it("reproduces editable and runtime metadata patches", () => {
		const created = addTaskToColumnWithResult(createInitialBoardData(), "backlog", {
			prompt: "Original",
			baseRef: "main",
			agentId: "codex",
			useWorktree: true,
		});
		const edited = updateTask(created.board, created.task.id, {
			prompt: "Updated",
			baseRef: "develop",
			useWorktree: false,
		});
		const backlog = edited.board.columns.find((column) => column.id === "backlog");
		if (!backlog?.cards[0]) throw new Error("Missing test task.");
		backlog.cards[0] = {
			...backlog.cards[0],
			title: "Updated title",
			titleAutoGenerated: false,
			agentId: "claude",
			baseRefPinned: true,
			workingDirectory: "/tmp/task",
			branch: "feature/task",
			pinned: true,
			updatedAt: 500,
		};

		const result = applyDerived(created.board, edited.board);

		expect(result.commands.some((command) => command.kind === "update_task")).toBe(true);
		expect(result.commands.some((command) => command.kind === "patch_task")).toBe(true);
		expect(result.board).toEqual(edited.board);
	});

	it("keeps generated title ownership when editing the prompt or pinning a task", () => {
		const initial = createInitialBoardData();
		const card: BoardCard = {
			id: "generated-task",
			title: "Search Experience",
			titleAutoGenerated: true,
			prompt: "Improve search",
			baseRef: "main",
			createdAt: 1,
			updatedAt: 1,
		};
		const before = {
			...initial,
			columns: initial.columns.map((column) => (column.id === "backlog" ? { ...column, cards: [card] } : column)),
		};
		const edited = updateTask(before, card.id, { prompt: "Improve recommendations too", baseRef: "develop" });
		const pinned = toggleTaskPinned(edited.board, card.id);
		const result = applyDerived(before, pinned.board);
		expect(result.commands).toHaveLength(1);
		expect(result.commands[0]).not.toHaveProperty("title");
		expect(result.board.columns[0]?.cards[0]).toMatchObject({
			title: "Search Experience",
			titleAutoGenerated: true,
			prompt: "Improve recommendations too",
			baseRef: "develop",
			pinned: true,
		});
		expect(result.board).toEqual(pinned.board);
	});

	it("preserves unpinning through serialized commands and pending overlays", () => {
		const created = addTaskToColumnWithResult(createInitialBoardData(), "backlog", {
			prompt: "Pinned task",
			baseRef: "main",
		});
		const pinned = toggleTaskPinned(created.board, created.task.id);
		const unpinned = toggleTaskPinned(pinned.board, created.task.id);
		const commands = deriveProjectBoardCommands(pinned.board, unpinned.board);
		const envelope = runtimeProjectBoardCommandBatchEnvelopeSchema.parse(
			JSON.parse(JSON.stringify({ commandId: "browser:unpin", expectedRevision: 1, commands })),
		);

		expect(envelope.commands).toEqual([
			expect.objectContaining({ kind: "update_task", taskId: created.task.id, pinned: false }),
		]);
		expect(applyProjectBoardCommands(pinned.board, envelope.commands).board).toEqual(unpinned.board);
		expect(applyPendingProjectBoardCommands(pinned.board, [commands])).toEqual(unpinned.board);
		expect(
			applyPendingProjectBoardCommands(created.board, [
				deriveProjectBoardCommands(created.board, pinned.board),
				commands,
			]),
		).toEqual(unpinned.board);
	});

	it("preserves removal of the last image through serialized commands and pending overlays", () => {
		const created = addTaskToColumnWithResult(createInitialBoardData(), "backlog", {
			prompt: "Task with an attachment",
			baseRef: "main",
			images: [{ id: "image-1", data: "YQ==", mimeType: "image/png" }],
		});
		const edited = saveEditedTaskToBoard({
			board: created.board,
			editingTaskId: created.task.id,
			prompt: created.task.prompt,
			images: [],
			branchRef: "main",
			defaultBranchRef: "main",
		});
		const commands = deriveProjectBoardCommands(created.board, edited.board);
		const envelope = runtimeProjectBoardCommandBatchEnvelopeSchema.parse(
			JSON.parse(JSON.stringify({ commandId: "browser:remove-image", expectedRevision: 1, commands })),
		);

		expect(envelope.commands).toEqual([
			expect.objectContaining({ kind: "update_task", taskId: created.task.id, images: [] }),
		]);
		expect(applyProjectBoardCommands(created.board, envelope.commands).board).toEqual(edited.board);
		expect(applyPendingProjectBoardCommands(created.board, [commands])).toEqual(edited.board);
	});

	it("preserves an explicit manual rename even when the title words stay the same", () => {
		const initial = createInitialBoardData();
		const card: BoardCard = {
			id: "generated-task",
			title: "Search Experience",
			titleAutoGenerated: true,
			prompt: "Improve search",
			baseRef: "main",
			createdAt: 1,
			updatedAt: 1,
		};
		const before = {
			...initial,
			columns: initial.columns.map((column) => (column.id === "backlog" ? { ...column, cards: [card] } : column)),
		};
		const after = {
			...before,
			columns: before.columns.map((column) => ({
				...column,
				cards: column.cards.map((task) => ({ ...task, titleAutoGenerated: false })),
			})),
		};
		const result = applyDerived(before, after);
		expect(result.commands).toHaveLength(1);
		expect(result.commands[0]).toMatchObject({ kind: "update_task", title: card.title });
		expect(result.board).toEqual(after);
	});

	it("does not persist a patch for Windows path casing alone", () => {
		const created = addTaskToColumnWithResult(createInitialBoardData(), "backlog", {
			prompt: "Task",
			baseRef: "main",
		});
		const withPath = {
			...created.board,
			columns: created.board.columns.map((column) => ({
				...column,
				cards: column.cards.map((card) =>
					card.id === created.task.id ? { ...card, workingDirectory: "C:\\Repo\\Task" } : card,
				),
			})),
		};
		const caseAlias = {
			...withPath,
			columns: withPath.columns.map((column) => ({
				...column,
				cards: column.cards.map((card) =>
					card.id === created.task.id ? { ...card, workingDirectory: "c:/repo/task/" } : card,
				),
			})),
		};

		expect(deriveProjectBoardCommands(withPath, caseAlias)).toEqual([]);
	});

	it("reproduces moves, dependency cleanup, and deletion", () => {
		const first = addTaskToColumnWithResult(createInitialBoardData(), "backlog", {
			prompt: "First",
			baseRef: "main",
		});
		const second = addTaskToColumnWithResult(first.board, "backlog", {
			prompt: "Second",
			baseRef: "main",
		});
		const linked = addTaskDependency(second.board, first.task.id, second.task.id);
		if (!linked.added) throw new Error("Expected dependency.");
		const moved = moveTaskToColumn(linked.board, first.task.id, "in_progress", { insertAtTop: true });
		const deleted = removeTask(moved.board, first.task.id);

		const result = applyDerived(linked.board, deleted.board);

		expect(result.commands.some((command) => command.kind === "delete_tasks")).toBe(true);
		expect(result.board).toEqual(deleted.board);
	});

	it("overlays pending batches in issue order", () => {
		const before = createInitialBoardData();
		const created = addTaskToColumnWithResult(before, "backlog", { prompt: "Task", baseRef: "main" });
		const moved = moveTaskToColumn(created.board, created.task.id, "in_progress", { insertAtTop: true });
		const createCommands = deriveProjectBoardCommands(before, created.board);
		const moveCommands = deriveProjectBoardCommands(created.board, moved.board);

		expect(applyPendingProjectBoardCommands(before, [createCommands, moveCommands])).toEqual(moved.board);
	});

	it("represents a large reorder as one bounded command", () => {
		const initial = createInitialBoardData();
		const cards: BoardCard[] = Array.from({ length: 600 }, (_, index) => ({
			id: `task-${index}`,
			title: `Task ${index}`,
			prompt: `Prompt ${index}`,
			baseRef: "main",
			createdAt: index,
			updatedAt: index,
		}));
		const before = {
			...initial,
			columns: initial.columns.map((column) => (column.id === "backlog" ? { ...column, cards } : column)),
		};
		const after = {
			...before,
			columns: before.columns.map((column) =>
				column.id === "backlog" ? { ...column, cards: [...cards].reverse() } : column,
			),
		};

		const result = applyDerived(before, after);

		expect(result.commands).toEqual([
			{
				kind: "reorder_column",
				columnId: "backlog",
				taskIds: after.columns[0]?.cards.map((card) => card.id),
			},
		]);
		expect(() =>
			runtimeProjectBoardCommandBatchEnvelopeSchema.parse({
				commandId: "browser:large-reorder",
				expectedRevision: 1,
				commands: result.commands,
			}),
		).not.toThrow();
		expect(result.board).toEqual(after);
	});
});
