import { resolve } from "node:path";

import { describe, expect, it, vi } from "vitest";

import type { RuntimeBoardCard } from "../../../src/core";
import { createCodexTaskTitleMonitor } from "../../../src/server/codex-task-title-monitor";
import type { ProjectBoardCommandService } from "../../../src/state";
import { InMemorySessionSummaryStore } from "../../../src/terminal";
import { createReviewBoard } from "../../utilities/board-factory";
import { createTestTaskSessionSummary } from "../../utilities/task-session-factory";

function harness(overrides: Partial<RuntimeBoardCard> = {}) {
	const board = createReviewBoard("task-1", "Fix title syncing");
	const card = board.columns.find((column) => column.id === "review")?.cards[0];
	if (!card) throw new Error("Missing test card");
	Object.assign(card, { title: "Placeholder", titleAutoGenerated: true, ...overrides });
	let session = createTestTaskSessionSummary({
		taskId: "task-1",
		agentId: "codex",
		resumeSessionId: "thread-1",
		sessionInstanceId: "launch-1",
	});
	const store = new InMemorySessionSummaryStore();
	vi.spyOn(store, "listSummaries").mockImplementation(() => [session]);
	vi.spyOn(store, "getSummary").mockImplementation(() => session);
	let active = true;
	const manager = {
		store,
		getTaskSessionProcessIdentity: () =>
			active
				? {
						pid: 123,
						sessionInstanceId: session.sessionInstanceId ?? "",
						launchOperationId: null,
						agentId: "codex" as const,
						binary: "codex",
						profileEnvironment: { CODEX_HOME: "/profile/codex" },
					}
				: null,
	};
	let removed = false;
	const readThreadNames = vi.fn(async () => new Map([["thread-1", "Codex title"]]));
	const setGeneratedTaskTitle = vi.fn(
		async (...args: Parameters<ProjectBoardCommandService["setGeneratedTaskTitle"]>) => {
			const options = args[5] ?? {};
			const acceptedChange =
				card.createdAt === args[2] &&
				card.title === options.expectedTitle &&
				(card.titleAutoGenerated === true) === options.expectedAutoGenerated &&
				Boolean(options.isCurrent?.(board));
			if (acceptedChange) Object.assign(card, { title: args[3], titleAutoGenerated: true });
			return { acceptedChange } as Awaited<ReturnType<ProjectBoardCommandService["setGeneratedTaskTitle"]>>;
		},
	);
	const publishTitleUpdated = vi.fn();
	const monitor = createCodexTaskTitleMonitor({
		listManagedProjects: () =>
			removed ? [] : [{ projectId: "project-1", projectPath: "/project", terminalManager: manager }],
		loadBoard: async () => structuredClone(board),
		boardCommands: { setGeneratedTaskTitle },
		readThreadNames,
		publishTitleUpdated,
	});
	return {
		monitor,
		board,
		card,
		readThreadNames,
		setGeneratedTaskTitle,
		publishTitleUpdated,
		replace: () => {
			session = { ...session, sessionInstanceId: "launch-2" };
		},
		navigate: () => {
			session = { ...session, resumeSessionId: "thread-2" };
		},
		stop: () => {
			active = false;
		},
		remove: () => {
			removed = true;
		},
	};
}

describe("Codex task title monitor", () => {
	it("adopts saved names, follows later updates and avoids duplicate writes", async () => {
		const h = harness();
		await h.monitor.refresh();
		expect(h.readThreadNames).toHaveBeenCalledWith(resolve("/profile/codex"), new Set(["thread-1"]));
		expect(h.publishTitleUpdated).toHaveBeenCalledWith({
			projectId: "project-1",
			taskId: "task-1",
			title: "Codex title",
		});
		await h.monitor.refresh();
		expect(h.setGeneratedTaskTitle).toHaveBeenCalledTimes(1);
		h.readThreadNames.mockResolvedValue(new Map([["thread-1", "Updated Codex title"]]));
		await h.monitor.refresh();
		expect(h.card.title).toBe("Updated Codex title");
		await h.monitor.close();
	});

	it.each([{ titleAutoGenerated: false }, { titleAutoGenerated: undefined }])(
		"preserves manual and legacy names: %j",
		async (overrides) => {
			const h = harness(overrides);
			await h.monitor.refresh();
			expect(h.readThreadNames).not.toHaveBeenCalled();
			expect(h.setGeneratedTaskTitle).not.toHaveBeenCalled();
			await h.monitor.close();
		},
	);

	it("only replaces an explicitly regenerated title after the provider name changes", async () => {
		const h = harness();
		await h.monitor.refresh();
		h.card.title = "Explicit regeneration";
		await h.monitor.refresh();
		expect(h.card.title).toBe("Explicit regeneration");
		h.readThreadNames.mockResolvedValue(new Map([["thread-1", "New provider name"]]));
		await h.monitor.refresh();
		expect(h.card.title).toBe("New provider name");
		await h.monitor.close();
	});

	it("accepts an untitled task before its local placeholder arrives", async () => {
		const h = harness({ title: null, titleAutoGenerated: undefined });
		await h.monitor.refresh();
		expect(h.publishTitleUpdated).toHaveBeenCalledOnce();
		await h.monitor.close();
	});

	it.each(["replace", "navigate", "stop", "remove"] as const)("rejects a late read after %s", async (action) => {
		const h = harness();
		h.readThreadNames.mockImplementation(async () => {
			h[action]();
			return new Map([["thread-1", "Late name"]]);
		});
		await h.monitor.refresh();
		expect(h.setGeneratedTaskTitle).not.toHaveBeenCalled();
		await h.monitor.close();
	});

	it("rechecks manual rename provenance under the board lock", async () => {
		const h = harness();
		h.readThreadNames.mockImplementation(async () => {
			h.card.titleAutoGenerated = false;
			return new Map([["thread-1", "Late name"]]);
		});
		await h.monitor.refresh();
		expect(h.publishTitleUpdated).not.toHaveBeenCalled();
		expect(h.card.title).toBe("Placeholder");
		await h.monitor.close();
	});

	it("leaves the placeholder on missing metadata or read errors", async () => {
		const h = harness();
		h.readThreadNames.mockResolvedValueOnce(new Map()).mockRejectedValueOnce(new Error("unavailable"));
		await h.monitor.refresh();
		await h.monitor.refresh();
		expect(h.setGeneratedTaskTitle).not.toHaveBeenCalled();
		await h.monitor.close();
	});

	it("stops polling and fences an in-flight result at shutdown", async () => {
		vi.useFakeTimers();
		const h = harness();
		let resolve!: (names: Map<string, string>) => void;
		h.readThreadNames.mockImplementation(
			() =>
				new Promise((done) => {
					resolve = done;
				}),
		);
		h.monitor.start();
		await vi.advanceTimersByTimeAsync(2_000);
		const closing = h.monitor.close();
		resolve(new Map([["thread-1", "Late name"]]));
		await closing;
		await vi.advanceTimersByTimeAsync(4_000);
		expect(h.readThreadNames).toHaveBeenCalledOnce();
		expect(h.setGeneratedTaskTitle).not.toHaveBeenCalled();
		vi.useRealTimers();
	});
});
