import { describe, expect, it, vi } from "vitest";

import type { ConversationReadResult, ConversationReadService } from "../../../src/conversation";
import type {
	RuntimeBoardCard,
	RuntimeBoardData,
	RuntimeProjectStateResponse,
	RuntimeTaskSessionSummary,
} from "../../../src/core";
import { createTaskTitleService, type TaskTitleServiceDependencies } from "../../../src/server/task-title-service";
import type { ProjectBoardCommandService } from "../../../src/state";
import { createTestTaskSessionSummary } from "../../utilities/task-session-factory";

const scope = { projectId: "project-1", projectPath: "/project" };

function history(
	entries: ConversationReadResult["entries"] = [
		{ type: "message", id: "user-1", role: "user", text: "Review the listing sorting settings." },
		{
			type: "message",
			id: "user-2",
			role: "user",
			text: "Make search cards and recommendations follow the same UI guidance.",
		},
		{
			type: "message",
			id: "assistant-1",
			role: "assistant",
			text: "Updated search cards, recommendation layouts, and shared guidance.",
		},
	],
): ConversationReadResult {
	return {
		status: "available",
		reason: null,
		entries,
		hasOlder: false,
		incomplete: false,
		requestedMessages: 24,
		diagnostics: {
			sourceBytesExamined: 0,
			recordsExamined: 0,
			lookupEntriesExamined: 0,
			returnedMessages: entries.length,
			returnedBoundaries: 0,
			durationMs: 0,
			issues: [],
		},
	};
}

function deferred<T>() {
	let resolve!: (value: T) => void;
	const promise = new Promise<T>((done) => {
		resolve = done;
	});
	return { promise, resolve };
}

function harness() {
	const card: RuntimeBoardCard = {
		id: "task-1",
		title: "Review Listing Sorting Settings",
		titleAutoGenerated: true,
		prompt: "Review the listing sorting settings.",
		baseRef: "main",
		createdAt: 1,
		updatedAt: 1,
	};
	const board: RuntimeBoardData = {
		columns: [
			{ id: "review", title: "Review", cards: [card] },
			{ id: "trash", title: "Trash", cards: [] },
		],
		dependencies: [],
	};
	const state: RuntimeProjectStateResponse = {
		repoPath: "/project",
		statePath: "/state/project",
		board,
		git: { currentBranch: "main", defaultBranch: "main", branches: ["main"] },
		sessions: {},
		revision: 1,
	};
	let session: RuntimeTaskSessionSummary | null = createTestTaskSessionSummary({
		taskId: card.id,
		agentId: "codex",
		state: "awaiting_review",
		reviewReason: "hook",
		sessionInstanceId: "launch-1",
		resumeSessionId: "thread-1",
		lastHookAt: 20,
	});
	const readRecent = vi.fn<ConversationReadService["readRecent"]>().mockResolvedValue(history());
	const generateTitle = vi
		.fn<NonNullable<TaskTitleServiceDependencies["generateTitle"]>>()
		.mockResolvedValue("Search and Recommendation UX");
	const publishTitleUpdated = vi.fn();
	const setGeneratedTaskTitle = vi
		.fn<ProjectBoardCommandService["setGeneratedTaskTitle"]>()
		.mockImplementation(async (_scope, _taskId, _createdAt, title, _updatedAt, options) => {
			const changed =
				options?.isCurrent?.(board) !== false && (card.title !== title || card.titleAutoGenerated !== true);
			if (changed) {
				card.title = title;
				card.titleAutoGenerated = true;
			}
			return { state, changed, acceptedChange: changed, replayed: false };
		});
	const service = createTaskTitleService({
		boardCommands: { setGeneratedTaskTitle },
		conversationReads: { readRecent },
		loadBoard: async () => board,
		getSessionReader: async () => () => session,
		generateTitle,
		publishTitleUpdated,
	});
	return {
		card,
		board,
		state,
		service,
		readRecent,
		generateTitle,
		publishTitleUpdated,
		setGeneratedTaskTitle,
		getSession: () => session,
		setSession: (next: RuntimeTaskSessionSummary | null) => {
			session = next;
		},
	};
}

describe("task title service", () => {
	it.each([
		{ scenario: "boundary-only", automatic: true },
		{ scenario: "boundary-only", automatic: false },
		{ scenario: "commentary-only", automatic: true },
		{ scenario: "commentary-only", automatic: false },
	])("uses completed-work summaries for $scenario history (automatic=$automatic)", async ({ scenario, automatic }) => {
		const h = harness();
		const summary = "Unified the search and recommendation review interface.";
		h.setSession(
			createTestTaskSessionSummary({
				...h.getSession(),
				conversationSummaries: [{ text: summary, capturedAt: 10, sessionIndex: 1 }],
			}),
		);
		h.readRecent.mockResolvedValue(
			history(
				scenario === "boundary-only"
					? [{ type: "boundary", id: "compacted", kind: "compacted" }]
					: Array.from({ length: 24 }, (_, index) => ({
							type: "message" as const,
							id: `progress-${index}`,
							role: "assistant" as const,
							text: "Running formatting checks now.",
						})),
			),
		);
		await expect(h.service.regenerate(scope, "task-1", { automatic })).resolves.toEqual({
			ok: true,
			title: "Search and Recommendation UX",
		});
		expect(h.generateTitle).toHaveBeenCalledWith(expect.stringContaining(summary), {
			mode: "followup",
			currentTitle: "Review Listing Sorting Settings",
		});
		expect(h.generateTitle.mock.calls[0]?.[0]).not.toContain("Running formatting checks");
	});

	it("does not treat empty user messages or summaries as substantive context", async () => {
		const h = harness();
		h.setSession(
			createTestTaskSessionSummary({
				...h.getSession(),
				conversationSummaries: [{ text: "  ", capturedAt: 10, sessionIndex: 1 }],
			}),
		);
		h.readRecent.mockResolvedValue(
			history([
				{ type: "message", id: "empty-user", role: "user", text: "  " },
				{ type: "message", id: "progress", role: "assistant", text: "Running formatting checks now." },
			]),
		);
		await expect(h.service.regenerate(scope, "task-1", { automatic: true })).resolves.toEqual({
			ok: false,
			title: null,
		});
		expect(h.generateTitle).not.toHaveBeenCalled();
	});

	it("allows explicit regeneration during ongoing tool activity in the same session", async () => {
		const h = harness();
		h.setSession(createTestTaskSessionSummary({ ...h.getSession(), state: "running" }));
		const pendingTitle = deferred<string | null>();
		h.generateTitle.mockReturnValue(pendingTitle.promise);
		const pending = h.service.regenerate(scope, "task-1");
		await vi.waitFor(() => expect(h.generateTitle).toHaveBeenCalledOnce());
		h.setSession(createTestTaskSessionSummary({ ...h.getSession(), lastHookAt: 30 }));
		pendingTitle.resolve("Search and Recommendation UX");
		await expect(pending).resolves.toEqual({ ok: true, title: "Search and Recommendation UX" });
	});
	it("uses recent provider conversation when stored summaries and final message are empty", async () => {
		const h = harness();
		expect(h.getSession()?.conversationSummaries).toEqual([]);
		expect(h.getSession()?.latestHookActivity).toBeNull();
		await expect(h.service.regenerate(scope, "task-1", { automatic: true })).resolves.toEqual({
			ok: true,
			title: "Search and Recommendation UX",
		});
		expect(h.readRecent).toHaveBeenCalledWith({ projectId: "project-1", taskId: "task-1", maxMessages: 24 });
		expect(h.generateTitle).toHaveBeenCalledWith(expect.stringContaining("Make search cards and recommendations"), {
			mode: "followup",
			currentTitle: "Review Listing Sorting Settings",
		});
		expect(h.generateTitle.mock.calls[0]?.[0]).toContain("Updated search cards, recommendation layouts");
		expect(h.setGeneratedTaskTitle).toHaveBeenCalledWith(
			scope,
			"task-1",
			1,
			"Search and Recommendation UX",
			expect.any(Number),
			expect.objectContaining({
				expectedTitle: "Review Listing Sorting Settings",
				expectedAutoGenerated: true,
				isCurrent: expect.any(Function),
			}),
		);
		expect(h.publishTitleUpdated).toHaveBeenCalledOnce();
	});

	it.each(["manual", "legacy", "trash", "running", "missing session", "missing task", "missing history"])(
		"skips automatic generation for %s",
		async (scenario) => {
			const h = harness();
			if (scenario === "manual") h.card.titleAutoGenerated = false;
			if (scenario === "legacy") delete h.card.titleAutoGenerated;
			if (scenario === "trash") {
				h.board.columns = [{ id: "trash", title: "Trash", cards: [h.card] }];
			}
			if (scenario === "running") h.setSession(createTestTaskSessionSummary({ state: "running" }));
			if (scenario === "missing session") h.setSession(null);
			if (scenario === "missing task") h.board.columns = [];
			if (scenario === "missing history") h.readRecent.mockResolvedValue(history([]));
			await expect(h.service.regenerate(scope, "task-1", { automatic: true })).resolves.toEqual({
				ok: false,
				title: null,
			});
			expect(h.generateTitle).not.toHaveBeenCalled();
			expect(h.setGeneratedTaskTitle).not.toHaveBeenCalled();
		},
	);

	it("explicit regeneration opts a legacy title into generated ownership", async () => {
		const h = harness();
		delete h.card.titleAutoGenerated;
		await h.service.regenerate(scope, "task-1");
		expect(h.setGeneratedTaskTitle).toHaveBeenCalledWith(
			scope,
			"task-1",
			1,
			"Search and Recommendation UX",
			expect.any(Number),
			expect.objectContaining({ expectedTitle: "Review Listing Sorting Settings", expectedAutoGenerated: false }),
		);
	});

	it("explicit regeneration can use the initial request when history is unavailable", async () => {
		const h = harness();
		h.readRecent.mockResolvedValue({
			...history([]),
			status: "unavailable",
			reason: "source_read_failed",
			entries: [],
		});
		await h.service.regenerate(scope, "task-1");
		expect(h.generateTitle).toHaveBeenCalledWith(h.card.prompt, {
			mode: "initial",
			currentTitle: "Review Listing Sorting Settings",
		});
	});

	it.each(["resumed", "provider replaced", "launch replaced", "new hook"])(
		"rejects a result when the session is %s during generation",
		async (scenario) => {
			const h = harness();
			const pendingTitle = deferred<string | null>();
			h.generateTitle.mockReturnValue(pendingTitle.promise);
			const pending = h.service.regenerate(scope, "task-1", { automatic: true });
			await vi.waitFor(() => expect(h.generateTitle).toHaveBeenCalledOnce());
			h.setSession(
				createTestTaskSessionSummary({
					...h.getSession(),
					...(scenario === "resumed" ? { state: "running" } : {}),
					...(scenario === "provider replaced" ? { resumeSessionId: "thread-2" } : {}),
					...(scenario === "launch replaced" ? { sessionInstanceId: "launch-2" } : {}),
					...(scenario === "new hook" ? { lastHookAt: 21 } : {}),
				}),
			);
			pendingTitle.resolve("Late title");
			await expect(pending).resolves.toEqual({ ok: false, title: null });
			expect(h.setGeneratedTaskTitle).not.toHaveBeenCalled();
			expect(h.publishTitleUpdated).not.toHaveBeenCalled();
		},
	);

	it("checks session identity again after reading history before spending a model call", async () => {
		const h = harness();
		const reading = deferred<ConversationReadResult>();
		h.readRecent.mockReturnValue(reading.promise);
		const pending = h.service.regenerate(scope, "task-1", { automatic: true });
		await vi.waitFor(() => expect(h.readRecent).toHaveBeenCalledOnce());
		h.setSession(null);
		reading.resolve(history());
		await expect(pending).resolves.toEqual({ ok: false, title: null });
		expect(h.generateTitle).not.toHaveBeenCalled();
	});

	it("passes a live guard to the lock-held writer", async () => {
		const h = harness();
		let current = true;
		h.setGeneratedTaskTitle.mockImplementation(async (_scope, _taskId, _createdAt, _title, _updatedAt, options) => {
			expect(options?.isCurrent?.(h.board)).toBe(true);
			current = false;
			expect(options?.isCurrent?.(h.board)).toBe(false);
			return { state: h.state, changed: false, acceptedChange: false, replayed: false };
		});
		await expect(
			h.service.regenerate(scope, "task-1", { automatic: true, isCurrent: () => current }),
		).resolves.toEqual({ ok: false, title: null });
		expect(h.publishTitleUpdated).not.toHaveBeenCalled();
	});

	it("does not publish an unchanged generated title", async () => {
		const h = harness();
		h.generateTitle.mockResolvedValue(h.card.title);
		await expect(h.service.regenerate(scope, "task-1", { automatic: true })).resolves.toEqual({
			ok: true,
			title: h.card.title,
		});
		expect(h.setGeneratedTaskTitle).toHaveBeenCalledOnce();
		expect(h.publishTitleUpdated).not.toHaveBeenCalled();
	});

	it("rejects automatic updates if the card is trashed before the locked write", async () => {
		const h = harness();
		h.setGeneratedTaskTitle.mockImplementation(async (_scope, _taskId, _createdAt, _title, _updatedAt, options) => {
			const trashedBoard: RuntimeBoardData = {
				...h.board,
				columns: [{ id: "trash", title: "Trash", cards: [h.card] }],
			};
			expect(options?.isCurrent?.(trashedBoard)).toBe(false);
			return { state: { ...h.state, board: trashedBoard }, changed: false, acceptedChange: false, replayed: false };
		});
		await expect(h.service.regenerate(scope, "task-1", { automatic: true })).resolves.toEqual({
			ok: false,
			title: null,
		});
		expect(h.publishTitleUpdated).not.toHaveBeenCalled();
	});

	it("does not replace an evolved title when history cannot be read", async () => {
		const h = harness();
		h.readRecent.mockResolvedValue({
			...history([]),
			status: "unavailable",
			reason: "source_read_failed",
			entries: [],
		});
		await expect(h.service.regenerate(scope, "task-1", { automatic: true })).resolves.toEqual({
			ok: false,
			title: null,
		});
		expect(h.generateTitle).not.toHaveBeenCalled();
	});

	it("skips a commentary-only transcript window with no user steering or completion", async () => {
		const h = harness();
		h.readRecent.mockResolvedValue(
			history([{ type: "message", id: "progress", role: "assistant", text: "Running the formatting check now." }]),
		);
		await expect(h.service.regenerate(scope, "task-1", { automatic: true })).resolves.toEqual({
			ok: false,
			title: null,
		});
		expect(h.readRecent).toHaveBeenCalledOnce();
		expect(h.generateTitle).not.toHaveBeenCalled();
		expect(h.setGeneratedTaskTitle).not.toHaveBeenCalled();
	});
});
