import { TRPCError } from "@trpc/server";
import { parseWorktreeDeleteRequest, parseWorktreeEnsureRequest } from "../core";
import { ProjectStateConflictError, saveProjectState } from "../state";
import { generateTaskTitle } from "../title";
import { deleteTaskWorktree, ensureTaskWorktreeIfDoesntExist, getTaskWorktreeInfo } from "../workdir";
import type { RuntimeTrpcContext } from "./app-router-context";
import { normalizeRequiredTaskScopeInput, type ProjectApiContext } from "./project-api-shared";

const MAX_CONCURRENT_TITLE_REQUESTS = 3;

type StateOps = Pick<
	RuntimeTrpcContext["projectApi"],
	| "ensureWorktree"
	| "deleteWorktree"
	| "loadTaskContext"
	| "loadState"
	| "saveState"
	| "notifyTaskTitleUpdated"
	| "setTaskDisplaySummary"
	| "setFocusedTask"
>;

export function createStateOps(ctx: ProjectApiContext): StateOps {
	return {
		// Called by the UI's ensureTaskWorktree (use-task-sessions.ts) for restore-from-trash.
		// The other path to ensureTaskWorktreeIfDoesntExist is startTaskSession in runtime-api.ts,
		// which reads branch from persisted board state server-side instead.
		ensureWorktree: async (projectScope, input) => {
			const body = parseWorktreeEnsureRequest(input);
			return await ensureTaskWorktreeIfDoesntExist({
				cwd: projectScope.projectPath,
				taskId: body.taskId,
				baseRef: body.baseRef,
				branch: body.branch ?? undefined,
			});
		},

		deleteWorktree: async (projectScope, input) => {
			const body = parseWorktreeDeleteRequest(input);
			const result = await deleteTaskWorktree({
				repoPath: projectScope.projectPath,
				taskId: body.taskId,
			});
			// workingDirectory is cleared by the client when it moves the card
			// to trash (moveTaskToColumn sets workingDirectory = null for trash).
			// The client persists through its normal board state cycle, avoiding
			// a dual-writer race where the server bumps the revision while the
			// client's persist debounce is in flight.
			return result;
		},

		loadTaskContext: async (projectScope, input) => {
			const normalizedInput = normalizeRequiredTaskScopeInput(input);
			return await getTaskWorktreeInfo({
				cwd: projectScope.projectPath,
				taskId: normalizedInput.taskId,
				baseRef: normalizedInput.baseRef,
			});
		},

		loadState: async (projectScope) => {
			return await ctx.deps.data.buildProjectStateSnapshot(projectScope.projectId, projectScope.projectPath);
		},

		saveState: async (projectScope, input) => {
			try {
				const terminalManager = await ctx.deps.terminals.ensureTerminalManagerForProject(
					projectScope.projectId,
					projectScope.projectPath,
				);
				const authoritativeSessions = Object.fromEntries(
					terminalManager.store.listSummaries().map((summary) => [summary.taskId, summary]),
				);
				const response = await saveProjectState(projectScope.projectPath, {
					board: input.board,
					sessions: authoritativeSessions,
					expectedRevision: input.expectedRevision,
				});
				ctx.broadcastStateUpdate(projectScope);
				void ctx.deps.broadcaster.broadcastRuntimeProjectsUpdated(projectScope.projectId);

				// Fire-and-forget: generate titles for any new cards that have title === null.
				// Cap concurrency to avoid flooding the LLM proxy when many cards are created at once.
				const untitledCards = input.board.columns.flatMap((col) => col.cards.filter((card) => card.title === null));
				const generateTitle = async (card: (typeof untitledCards)[number]) => {
					const title = await generateTaskTitle(card.prompt);
					if (!title) return;
					// Send the title to the UI via a lightweight message. The client
					// applies it to its board state and persists through its normal
					// single-writer cycle.
					ctx.deps.broadcaster.broadcastTaskTitleUpdated(projectScope.projectId, card.id, title, {
						autoGenerated: true,
					});
				};
				if (untitledCards.length > 0) {
					void (async () => {
						for (let i = 0; i < untitledCards.length; i += MAX_CONCURRENT_TITLE_REQUESTS) {
							const batch = untitledCards.slice(i, i + MAX_CONCURRENT_TITLE_REQUESTS);
							await Promise.allSettled(batch.map(generateTitle));
						}
					})();
				}

				return response;
			} catch (error) {
				if (error instanceof ProjectStateConflictError) {
					throw new TRPCError({
						code: "CONFLICT",
						message: error.message,
						cause: { currentRevision: error.currentRevision },
					});
				}
				throw error;
			}
		},

		notifyTaskTitleUpdated: (projectScope, taskId, title) => {
			ctx.deps.broadcaster.broadcastTaskTitleUpdated(projectScope.projectId, taskId, title);
		},

		setTaskDisplaySummary: async (projectScope, taskId, text, generatedAt) => {
			const manager = await ctx.deps.terminals.ensureTerminalManagerForProject(
				projectScope.projectId,
				projectScope.projectPath,
			);
			manager.store.setDisplaySummary(taskId, text, generatedAt);
			ctx.broadcastStateUpdate(projectScope);
		},

		setFocusedTask: (projectScope, taskId) => {
			ctx.deps.broadcaster.setFocusedTask(projectScope.projectId, taskId);
		},
	};
}
