import { randomUUID } from "node:crypto";

import { TRPCError } from "@trpc/server";
import { findCardInBoard, parseWorktreeDeleteRequest, parseWorktreeEnsureRequest } from "../core";
import { ProjectBoardCommandIdentityConflictError, ProjectStateConflictError } from "../state";
import { generateTaskTitle } from "../title";
import { deleteTaskWorktree, ensureTaskWorktreeIfDoesntExist, getTaskRepositoryInfo } from "../workdir";
import type { RuntimeTrpcContext, RuntimeTrpcProjectScope } from "./app-router-context";
import { normalizeRequiredTaskScopeInput, type ProjectApiContext } from "./project-api-shared";
import {
	createBoardCommandCommittedEffects,
	createProjectStateUpdatedEffects,
	createTaskTitleUpdatedEffects,
} from "./runtime-mutation-effects";

const MAX_CONCURRENT_TITLE_REQUESTS = 3;
const automaticTitleGenerationInFlight = new Set<string>();

type StateOps = Pick<
	RuntimeTrpcContext["projectApi"],
	| "ensureWorktree"
	| "deleteWorktree"
	| "loadTaskContext"
	| "loadState"
	| "applyBoardCommands"
	| "updateTaskTitle"
	| "setTaskDisplaySummary"
	| "setFocusedTask"
	| "setDocumentVisible"
>;

function requireBoardCommands(ctx: ProjectApiContext) {
	if (!ctx.deps.boardCommands) {
		throw new Error("Project board command authority is not configured.");
	}
	return ctx.deps.boardCommands;
}

async function persistTaskTitle(
	ctx: ProjectApiContext,
	projectScope: RuntimeTrpcProjectScope,
	input: {
		taskId: string;
		title: string;
		commandId: string;
	},
): Promise<boolean> {
	const updatedAt = Date.now();
	for (let attempt = 0; attempt < 3; attempt += 1) {
		const current = await ctx.deps.data.buildProjectStateSnapshot(projectScope.projectId, projectScope.projectPath);
		const card = findCardInBoard(current.board, input.taskId);
		if (!card) {
			return false;
		}
		try {
			const result = await requireBoardCommands(ctx).executeBatch(projectScope, {
				commandId: input.commandId,
				expectedRevision: current.revision,
				commands: [
					{
						kind: "patch_task",
						taskId: input.taskId,
						title: input.title,
						updatedAt,
					},
				],
			});
			if (!result.acceptedChange) {
				return false;
			}
			ctx.applyEffects(
				createTaskTitleUpdatedEffects({
					projectId: projectScope.projectId,
					taskId: input.taskId,
					title: input.title,
				}),
			);
			return true;
		} catch (error) {
			if (!(error instanceof ProjectStateConflictError) || attempt === 2) {
				throw error;
			}
		}
	}
	return false;
}

function scheduleAutomaticTaskTitles(
	ctx: ProjectApiContext,
	projectScope: RuntimeTrpcProjectScope,
	state: Awaited<ReturnType<ProjectApiContext["deps"]["data"]["buildProjectStateSnapshot"]>>,
): void {
	const untitledCards = state.board.columns.flatMap((column) => column.cards.filter((card) => card.title === null));
	if (untitledCards.length === 0) {
		return;
	}
	void (async () => {
		for (let index = 0; index < untitledCards.length; index += MAX_CONCURRENT_TITLE_REQUESTS) {
			const batch = untitledCards.slice(index, index + MAX_CONCURRENT_TITLE_REQUESTS);
			await Promise.allSettled(
				batch.map(async (card) => {
					const generationKey = JSON.stringify([projectScope.projectId, card.id]);
					if (automaticTitleGenerationInFlight.has(generationKey)) {
						return;
					}
					automaticTitleGenerationInFlight.add(generationKey);
					try {
						const title = await generateTaskTitle(card.prompt);
						if (!title) {
							return;
						}
						const result = await requireBoardCommands(ctx).setGeneratedTaskTitle(projectScope, card.id, title);
						if (result.acceptedChange) {
							ctx.applyEffects(
								createTaskTitleUpdatedEffects({
									projectId: projectScope.projectId,
									taskId: card.id,
									title,
									autoGenerated: true,
								}),
							);
						}
					} finally {
						automaticTitleGenerationInFlight.delete(generationKey);
					}
				}),
			);
		}
	})();
}

export function createStateOps(ctx: ProjectApiContext): StateOps {
	return {
		// Called by the UI's ensureTaskWorktree (use-task-sessions.ts) for restore-from-trash.
		// The other path to ensureTaskWorktreeIfDoesntExist is startTaskSession in runtime-api.ts,
		// which reads branch from persisted board state server-side instead.
		ensureWorktree: async (projectScope, input) => {
			const body = parseWorktreeEnsureRequest(input);
			return await ensureTaskWorktreeIfDoesntExist({
				cwd: projectScope.projectPath,
				taskId: body.taskId,
				baseRef: body.baseRef,
				branch: body.branch ?? undefined,
			});
		},

		deleteWorktree: async (projectScope, input) => {
			const body = parseWorktreeDeleteRequest(input);
			const result = await deleteTaskWorktree({
				repoPath: projectScope.projectPath,
				taskId: body.taskId,
			});
			// The runtime board command that moved the task to trash already
			// cleared workingDirectory. The browser flushes that command before
			// invoking this destructive cleanup.
			return result;
		},

		loadTaskContext: async (projectScope, input) => {
			const normalizedInput = normalizeRequiredTaskScopeInput(input);
			return await getTaskRepositoryInfo({
				cwd: projectScope.projectPath,
				taskId: normalizedInput.taskId,
				baseRef: normalizedInput.baseRef,
			});
		},

		loadState: async (projectScope) => {
			return await ctx.deps.data.buildProjectStateSnapshot(projectScope.projectId, projectScope.projectPath);
		},

		applyBoardCommands: async (projectScope, input) => {
			try {
				const result = await requireBoardCommands(ctx).executeBatch(projectScope, input);
				ctx.applyEffects(createBoardCommandCommittedEffects(projectScope));
				scheduleAutomaticTaskTitles(ctx, projectScope, result.state);
				return result;
			} catch (error) {
				if (error instanceof ProjectStateConflictError) {
					throw new TRPCError({
						code: "CONFLICT",
						message: error.message,
						cause: { currentRevision: error.currentRevision },
					});
				}
				if (error instanceof ProjectBoardCommandIdentityConflictError) {
					throw new TRPCError({ code: "CONFLICT", message: error.message });
				}
				throw error;
			}
		},

		updateTaskTitle: async (projectScope, taskId, title) =>
			await persistTaskTitle(ctx, projectScope, {
				taskId,
				title,
				commandId: `title:${randomUUID()}`,
			}),

		setTaskDisplaySummary: async (projectScope, taskId, text, generatedAt) => {
			const manager = await ctx.deps.terminals.ensureTerminalManagerForProject(
				projectScope.projectId,
				projectScope.projectPath,
			);
			manager.store.setDisplaySummary(taskId, text, generatedAt);
			ctx.applyEffects(createProjectStateUpdatedEffects(projectScope));
		},

		setFocusedTask: (projectScope, taskId) => {
			// This intentionally stays a direct command instead of becoming a
			// post-mutation effect. Focus steers metadata-monitor polling policy;
			// it is not a "mutation happened, now deliver consequences" path.
			ctx.deps.broadcaster.setFocusedTask(projectScope.projectId, taskId);
		},

		setDocumentVisible: (projectScope, clientId, isDocumentVisible) => {
			ctx.deps.broadcaster.setDocumentVisible(projectScope.projectId, clientId, isDocumentVisible);
		},
	};
}
