import type { IRuntimeBroadcaster, RuntimeHookEvent } from "../core";
import type { RuntimeTrpcProjectScope } from "./app-router-context";

type RuntimeLogLevel = Parameters<IRuntimeBroadcaster["broadcastLogLevel"]>[0];
type RuntimePollIntervals = Parameters<IRuntimeBroadcaster["setPollIntervals"]>[1];

export type RuntimeMutationEffect =
	| {
			type: "project_state_updated";
			projectId: string;
			projectPath: string;
	  }
	| {
			type: "projects_updated";
			preferredCurrentProjectId: string | null;
	  }
	| {
			type: "task_ready_for_review";
			projectId: string;
			taskId: string;
	  }
	| {
			type: "task_title_updated";
			projectId: string;
			taskId: string;
			title: string;
			autoGenerated?: boolean;
	  }
	| {
			type: "task_base_ref_updated";
			projectId: string;
			taskId: string;
			baseRef: string;
	  }
	| {
			type: "task_git_metadata_refresh";
			projectId: string;
			taskId: string;
	  }
	| {
			type: "home_git_metadata_refresh";
			projectId: string;
	  }
	| {
			type: "poll_intervals_updated";
			projectId: string;
			intervals: RuntimePollIntervals;
	  }
	| {
			type: "log_level_broadcast";
			level: RuntimeLogLevel;
	  };

type RuntimeMutationEffectBroadcaster = Partial<
	Pick<
		IRuntimeBroadcaster,
		| "broadcastRuntimeProjectStateUpdated"
		| "broadcastRuntimeProjectsUpdated"
		| "broadcastTaskReadyForReview"
		| "broadcastTaskTitleUpdated"
		| "broadcastTaskBaseRefUpdated"
		| "broadcastLogLevel"
		| "requestTaskRefresh"
		| "requestHomeRefresh"
		| "setPollIntervals"
	>
>;

function requireBroadcasterMethod<K extends keyof NonNullable<RuntimeMutationEffectBroadcaster>>(
	broadcaster: RuntimeMutationEffectBroadcaster,
	method: K,
): NonNullable<RuntimeMutationEffectBroadcaster[K]> {
	const candidate = broadcaster[method];
	if (!candidate) {
		throw new Error(`Missing runtime mutation broadcaster method: ${String(method)}`);
	}
	return candidate;
}

export function createProjectStateUpdatedEffects(
	projectScope: RuntimeTrpcProjectScope,
): readonly RuntimeMutationEffect[] {
	return [
		{
			type: "project_state_updated",
			projectId: projectScope.projectId,
			projectPath: projectScope.projectPath,
		},
	];
}

export function createProjectsUpdatedEffects(
	preferredCurrentProjectId: string | null,
): readonly RuntimeMutationEffect[] {
	return [
		{
			type: "projects_updated",
			preferredCurrentProjectId,
		},
	];
}

export function createBoardStateSavedEffects(projectScope: RuntimeTrpcProjectScope): readonly RuntimeMutationEffect[] {
	return [...createProjectStateUpdatedEffects(projectScope), ...createProjectsUpdatedEffects(projectScope.projectId)];
}

export function createTaskTitleUpdatedEffects(input: {
	projectId: string;
	taskId: string;
	title: string;
	autoGenerated?: boolean;
}): readonly RuntimeMutationEffect[] {
	return [
		{
			type: "task_title_updated",
			projectId: input.projectId,
			taskId: input.taskId,
			title: input.title,
			...(input.autoGenerated ? { autoGenerated: true } : undefined),
		},
	];
}

export function createTaskBaseRefUpdatedEffects(input: {
	projectId: string;
	taskId: string;
	baseRef: string;
}): readonly RuntimeMutationEffect[] {
	return [
		{
			type: "task_base_ref_updated",
			projectId: input.projectId,
			taskId: input.taskId,
			baseRef: input.baseRef,
		},
	];
}

export function createGitMetadataRefreshEffects(
	projectScope: Pick<RuntimeTrpcProjectScope, "projectId">,
	taskScope: { taskId: string } | null,
): readonly RuntimeMutationEffect[] {
	if (taskScope) {
		return [
			{
				type: "task_git_metadata_refresh",
				projectId: projectScope.projectId,
				taskId: taskScope.taskId,
			},
		];
	}

	return [
		{
			type: "home_git_metadata_refresh",
			projectId: projectScope.projectId,
		},
	];
}

export function createHookTransitionEffects(input: {
	projectId: string;
	projectPath: string;
	taskId: string;
	event: RuntimeHookEvent;
}): readonly RuntimeMutationEffect[] {
	const effects: RuntimeMutationEffect[] = [
		{
			type: "project_state_updated",
			projectId: input.projectId,
			projectPath: input.projectPath,
		},
	];
	if (input.event === "to_review") {
		effects.push({
			type: "task_ready_for_review",
			projectId: input.projectId,
			taskId: input.taskId,
		});
	}
	return effects;
}

export function createPollIntervalsUpdatedEffects(
	projectId: string,
	intervals: RuntimePollIntervals,
): readonly RuntimeMutationEffect[] {
	return [
		{
			type: "poll_intervals_updated",
			projectId,
			intervals,
		},
	];
}

export function createLogLevelBroadcastEffects(level: RuntimeLogLevel): readonly RuntimeMutationEffect[] {
	return [
		{
			type: "log_level_broadcast",
			level,
		},
	];
}

function getEffectKey(effect: RuntimeMutationEffect): string {
	switch (effect.type) {
		case "project_state_updated":
			return `${effect.type}:${effect.projectId}:${effect.projectPath}`;
		case "projects_updated":
			return `${effect.type}:${effect.preferredCurrentProjectId ?? ""}`;
		case "task_ready_for_review":
			return `${effect.type}:${effect.projectId}:${effect.taskId}`;
		case "task_title_updated":
			return `${effect.type}:${effect.projectId}:${effect.taskId}:${effect.title}:${effect.autoGenerated ? "auto" : "manual"}`;
		case "task_base_ref_updated":
			return `${effect.type}:${effect.projectId}:${effect.taskId}:${effect.baseRef}`;
		case "task_git_metadata_refresh":
			return `${effect.type}:${effect.projectId}:${effect.taskId}`;
		case "home_git_metadata_refresh":
			return `${effect.type}:${effect.projectId}`;
		case "poll_intervals_updated":
			return `${effect.type}:${effect.projectId}:${effect.intervals.focusedTaskPollMs}:${effect.intervals.backgroundTaskPollMs}:${effect.intervals.homeRepoPollMs}`;
		case "log_level_broadcast":
			return `${effect.type}:${effect.level}`;
	}
}

function dedupeRuntimeMutationEffects(effects: readonly RuntimeMutationEffect[]): RuntimeMutationEffect[] {
	const deduped = new Map<string, RuntimeMutationEffect>();
	for (const effect of effects) {
		deduped.set(getEffectKey(effect), effect);
	}
	return Array.from(deduped.values());
}

export async function applyRuntimeMutationEffects(
	broadcaster: RuntimeMutationEffectBroadcaster,
	effects: readonly RuntimeMutationEffect[],
): Promise<void> {
	for (const effect of dedupeRuntimeMutationEffects(effects)) {
		switch (effect.type) {
			case "project_state_updated":
				await requireBroadcasterMethod(broadcaster, "broadcastRuntimeProjectStateUpdated")(
					effect.projectId,
					effect.projectPath,
				);
				break;
			case "projects_updated":
				await requireBroadcasterMethod(
					broadcaster,
					"broadcastRuntimeProjectsUpdated",
				)(effect.preferredCurrentProjectId);
				break;
			case "task_ready_for_review":
				requireBroadcasterMethod(broadcaster, "broadcastTaskReadyForReview")(effect.projectId, effect.taskId);
				break;
			case "task_title_updated":
				requireBroadcasterMethod(broadcaster, "broadcastTaskTitleUpdated")(
					effect.projectId,
					effect.taskId,
					effect.title,
					{
						autoGenerated: effect.autoGenerated,
					},
				);
				break;
			case "task_base_ref_updated":
				requireBroadcasterMethod(broadcaster, "broadcastTaskBaseRefUpdated")(
					effect.projectId,
					effect.taskId,
					effect.baseRef,
				);
				break;
			case "task_git_metadata_refresh":
				requireBroadcasterMethod(broadcaster, "requestTaskRefresh")(effect.projectId, effect.taskId);
				break;
			case "home_git_metadata_refresh":
				requireBroadcasterMethod(broadcaster, "requestHomeRefresh")(effect.projectId);
				break;
			case "poll_intervals_updated":
				requireBroadcasterMethod(broadcaster, "setPollIntervals")(effect.projectId, effect.intervals);
				break;
			case "log_level_broadcast":
				requireBroadcasterMethod(broadcaster, "broadcastLogLevel")(effect.level);
				break;
		}
	}
}
