import { resolve } from "node:path";
import { TRPCError } from "@trpc/server";
import type {
	RuntimeAutoMergedFilesResponse,
	RuntimeConflictAbortResponse,
	RuntimeConflictContinueResponse,
	RuntimeConflictFilesResponse,
	RuntimeFileContentResponse,
	RuntimeGitCheckoutResponse,
	RuntimeGitCommitResponse,
	RuntimeGitDiscardResponse,
	RuntimeGitMergeResponse,
	RuntimeGitSummaryResponse,
	RuntimeListFilesResponse,
	RuntimeStashDropResponse,
	RuntimeStashListResponse,
	RuntimeStashPopApplyResponse,
	RuntimeStashPushResponse,
	RuntimeStashShowResponse,
	RuntimeWorkspaceChangesMode,
	RuntimeWorkspaceFileSearchResponse,
	RuntimeWorkspaceStateResponse,
} from "../core/api-contract";
import {
	parseGitCheckoutRequest,
	parseWorktreeDeleteRequest,
	parseWorktreeEnsureRequest,
} from "../core/api-validation";
import { loadWorkspaceState, saveWorkspaceState, WorkspaceStateConflictError } from "../state/workspace-state";
import type { TerminalSessionManager } from "../terminal/session-manager";
import { generateTaskTitle } from "../title/title-generator";
import {
	createEmptyWorkspaceChangesResponse,
	getWorkspaceChanges,
	getWorkspaceChangesBetweenRefs,
	getWorkspaceChangesFromRef,
	getWorkspaceFileDiff,
} from "../workspace/get-workspace-changes";
import { cherryPickCommit } from "../workspace/git-cherry-pick";
import {
	abortMergeOrRebase,
	continueMergeOrRebase,
	getAutoMergedFileContent,
	getConflictFileContent,
	resolveConflictFile as gitResolveConflictFile,
	runGitMergeAction,
} from "../workspace/git-conflict";
import { getCommitDiff, getGitLog, getGitRefs } from "../workspace/git-history";
import { getGitSyncSummary } from "../workspace/git-probe";
import { stashApply, stashDrop, stashList, stashPop, stashPush, stashShow } from "../workspace/git-stash";
import {
	commitSelectedFiles,
	createBranchFromRef,
	deleteBranch,
	discardGitChanges,
	discardSingleFile,
	runGitCheckoutAction,
	runGitSyncAction,
} from "../workspace/git-sync";
import {
	assertValidGitRef,
	getFileContentAtRef,
	getGitStdout,
	listFilesAtRef,
	validateGitPath,
} from "../workspace/git-utils";
import { readWorkspaceFile } from "../workspace/read-workspace-file";
import { listAllWorkspaceFiles, searchWorkspaceFiles } from "../workspace/search-workspace-files";
import {
	deleteTaskWorktree,
	ensureTaskWorktreeIfDoesntExist,
	getTaskWorkspaceInfo,
	isMissingTaskWorktreeError,
	resolveTaskWorkingDirectory,
} from "../workspace/task-worktree";
import type { RuntimeTrpcContext } from "./app-router";

const MAX_CONCURRENT_TITLE_REQUESTS = 3;

export interface CreateWorkspaceApiDependencies {
	ensureTerminalManagerForWorkspace: (workspaceId: string, repoPath: string) => Promise<TerminalSessionManager>;
	broadcastRuntimeWorkspaceStateUpdated: (workspaceId: string, workspacePath: string) => Promise<void> | void;
	broadcastRuntimeProjectsUpdated: (preferredCurrentProjectId: string | null) => Promise<void> | void;
	broadcastTaskTitleUpdated: (
		workspaceId: string,
		taskId: string,
		title: string,
		options?: { autoGenerated?: boolean },
	) => void;
	buildWorkspaceStateSnapshot: (workspaceId: string, workspacePath: string) => Promise<RuntimeWorkspaceStateResponse>;
	setFocusedTask: (workspaceId: string, taskId: string | null) => void;
	requestTaskRefresh: (workspaceId: string, taskId: string) => void;
	requestHomeRefresh: (workspaceId: string) => void;
}

// ── Shared helpers ──────────────────────────────────────────────────────────────

const EMPTY_GIT_SUMMARY = {
	currentBranch: null,
	upstreamBranch: null,
	changedFiles: 0,
	additions: 0,
	deletions: 0,
	aheadCount: 0,
	behindCount: 0,
} as const;

function errorMessage(error: unknown): string {
	return error instanceof Error ? error.message : String(error);
}

/** Resolve cwd for optional task scope — returns workspace root when taskScope is null. */
async function resolveWorkingDir(
	workspacePath: string,
	taskScope: { taskId: string; baseRef: string } | null,
): Promise<string> {
	if (!taskScope) return workspacePath;
	return await resolveTaskWorkingDirectory({ workspacePath, ...taskScope });
}

/** Resolve task cwd, returning null instead of throwing for missing worktrees. */
async function tryResolveTaskCwd(workspacePath: string, taskId: string, baseRef: string): Promise<string | null> {
	try {
		return await resolveTaskWorkingDirectory({ workspacePath, taskId, baseRef });
	} catch (error) {
		if (isMissingTaskWorktreeError(error)) return null;
		throw error;
	}
}

/** Check whether any in_progress or review task is running against the shared checkout. */
async function hasActiveSharedCheckoutTask(workspacePath: string): Promise<boolean> {
	const state = await loadWorkspaceState(workspacePath);
	const activeColumnIds = new Set(["in_progress", "review"]);
	return state.board.columns
		.filter((col) => activeColumnIds.has(col.id))
		.some((col) =>
			col.cards.some((card) => {
				const isSharedCheckout = card.workingDirectory
					? resolve(card.workingDirectory) === resolve(workspacePath)
					: card.useWorktree === false;
				return isSharedCheckout;
			}),
		);
}

// ── Input normalization ─────────────────────────────────────────────────────────

function normalizeOptionalTaskWorkspaceScopeInput(
	input: { taskId: string; baseRef: string } | null,
): { taskId: string; baseRef: string } | null {
	if (!input) return null;
	const taskId = input.taskId.trim();
	const baseRef = input.baseRef.trim();
	if (!taskId || !baseRef) {
		throw new Error("baseRef query parameter requires taskId.");
	}
	return { taskId, baseRef };
}

function normalizeRequiredTaskWorkspaceScopeInput(input: {
	taskId: string | null;
	baseRef?: string;
	mode?: RuntimeWorkspaceChangesMode;
}): {
	taskId: string;
	baseRef: string;
	mode: RuntimeWorkspaceChangesMode;
} {
	const taskId = (input.taskId ?? "").trim();
	const baseRef = (input.baseRef ?? "").trim();
	if (!taskId) throw new Error("Missing taskId query parameter.");
	if (!baseRef) throw new Error("Missing baseRef query parameter.");
	return { taskId, baseRef, mode: input.mode ?? "working_copy" };
}

// ── Error response factories ────────────────────────────────────────────────────

/** Checkout and merge error responses share the same shape. */
function createGitBranchErrorResponse(error: unknown): RuntimeGitCheckoutResponse & RuntimeGitMergeResponse {
	return { ok: false, branch: "", summary: { ...EMPTY_GIT_SUMMARY }, output: "", error: errorMessage(error) };
}

/** Discard and commit error responses share the same shape. */
function createGitOutputErrorResponse(error: unknown): RuntimeGitDiscardResponse & RuntimeGitCommitResponse {
	return { ok: false, summary: { ...EMPTY_GIT_SUMMARY }, output: "", error: errorMessage(error) };
}

// ── Workspace API implementation ────────────────────────────────────────────────

export function createWorkspaceApi(deps: CreateWorkspaceApiDependencies): RuntimeTrpcContext["workspaceApi"] {
	const broadcastStateUpdate = (scope: { workspaceId: string; workspacePath: string }) => {
		void deps.broadcastRuntimeWorkspaceStateUpdated(scope.workspaceId, scope.workspacePath);
	};

	// Lightweight refresh for git-only operations (commit, discard, stash) that don't
	// change board state or sessions. Refreshes only the affected metadata scope instead
	// of rebuilding + broadcasting the full workspace state snapshot and probing all tasks.
	const refreshGitMetadata = (
		scope: { workspaceId: string },
		taskScope: { taskId: string; baseRef: string } | null,
	) => {
		if (taskScope) {
			deps.requestTaskRefresh(scope.workspaceId, taskScope.taskId);
		} else {
			deps.requestHomeRefresh(scope.workspaceId);
		}
	};

	return {
		loadGitSummary: async (workspaceScope, input) => {
			try {
				const cwd = await resolveWorkingDir(
					workspaceScope.workspacePath,
					normalizeOptionalTaskWorkspaceScopeInput(input),
				);
				const summary = await getGitSyncSummary(cwd);
				return { ok: true, summary } satisfies RuntimeGitSummaryResponse;
			} catch (error) {
				return { ok: false, summary: { ...EMPTY_GIT_SUMMARY }, error: errorMessage(error) };
			}
		},

		runGitSyncAction: async (workspaceScope, input) => {
			try {
				const cwd = await resolveWorkingDir(
					workspaceScope.workspacePath,
					normalizeOptionalTaskWorkspaceScopeInput(input.taskScope ?? null),
				);
				return await runGitSyncAction({ cwd, action: input.action, branch: input.branch ?? null });
			} catch (error) {
				return {
					ok: false,
					action: input.action,
					summary: { ...EMPTY_GIT_SUMMARY },
					output: "",
					error: errorMessage(error),
				};
			}
		},

		checkoutGitBranch: async (workspaceScope, input) => {
			try {
				const body = parseGitCheckoutRequest(input);

				// Task-scoped checkout: resolve task worktree and checkout there
				if (input.taskId) {
					const taskCwd = await resolveTaskWorkingDirectory({
						workspacePath: workspaceScope.workspacePath,
						taskId: input.taskId,
						baseRef: input.baseRef ?? "",
					});
					const response = await runGitCheckoutAction({ cwd: taskCwd, branch: body.branch });
					if (response.ok) {
						deps.requestTaskRefresh(workspaceScope.workspaceId, input.taskId);
					}
					return response;
				}

				// Home repo checkout: block when an active task is running in the shared checkout
				if (await hasActiveSharedCheckoutTask(workspaceScope.workspacePath)) {
					return createGitBranchErrorResponse(
						new Error(
							"Cannot switch branches while a task in the shared checkout is in progress or review. Isolate the task or move it to another column first.",
						),
					);
				}
				const response = await runGitCheckoutAction({
					cwd: workspaceScope.workspacePath,
					branch: body.branch,
				});
				if (response.ok) broadcastStateUpdate(workspaceScope);
				return response;
			} catch (error) {
				return createGitBranchErrorResponse(error);
			}
		},

		mergeBranch: async (workspaceScope, input) => {
			try {
				const branchToMerge = input.branch.trim();
				if (!branchToMerge) {
					return createGitBranchErrorResponse(new Error("Branch name cannot be empty."));
				}

				// Task-scoped merge: resolve task worktree and merge there
				if (input.taskId) {
					const taskCwd = await resolveTaskWorkingDirectory({
						workspacePath: workspaceScope.workspacePath,
						taskId: input.taskId,
						baseRef: input.baseRef ?? "",
					});
					const response = await runGitMergeAction({ cwd: taskCwd, branch: branchToMerge });
					if (response.ok || response.conflictState) {
						deps.requestTaskRefresh(workspaceScope.workspaceId, input.taskId);
					}
					return response;
				}

				// Home repo merge: block when an active task is running in the shared checkout
				if (await hasActiveSharedCheckoutTask(workspaceScope.workspacePath)) {
					return createGitBranchErrorResponse(
						new Error(
							"Cannot merge while a task in the shared checkout is in progress or review. Isolate the task or move it to another column first.",
						),
					);
				}
				const response = await runGitMergeAction({ cwd: workspaceScope.workspacePath, branch: branchToMerge });
				if (response.ok || response.conflictState) broadcastStateUpdate(workspaceScope);
				return response;
			} catch (error) {
				return createGitBranchErrorResponse(error);
			}
		},

		getConflictFiles: async (workspaceScope, input) => {
			try {
				const cwd = await resolveWorkingDir(
					workspaceScope.workspacePath,
					input.taskId ? { taskId: input.taskId, baseRef: "" } : null,
				);
				const files = await Promise.all(input.paths.map((path) => getConflictFileContent(cwd, path)));
				return { ok: true, files } satisfies RuntimeConflictFilesResponse;
			} catch (error) {
				return { ok: false, files: [], error: errorMessage(error) } satisfies RuntimeConflictFilesResponse;
			}
		},

		getAutoMergedFiles: async (workspaceScope, input) => {
			try {
				const cwd = await resolveWorkingDir(
					workspaceScope.workspacePath,
					input.taskId ? { taskId: input.taskId, baseRef: "" } : null,
				);
				const files = await Promise.all(input.paths.map((path) => getAutoMergedFileContent(cwd, path)));
				return { ok: true, files } satisfies RuntimeAutoMergedFilesResponse;
			} catch (error) {
				return { ok: false, files: [], error: errorMessage(error) } satisfies RuntimeAutoMergedFilesResponse;
			}
		},

		resolveConflictFile: async (workspaceScope, input) => {
			try {
				const cwd = await resolveWorkingDir(
					workspaceScope.workspacePath,
					input.taskId ? { taskId: input.taskId, baseRef: "" } : null,
				);
				const result = await gitResolveConflictFile(cwd, input.path, input.resolution);
				if (result.ok) broadcastStateUpdate(workspaceScope);
				return result;
			} catch (error) {
				return { ok: false, error: errorMessage(error) };
			}
		},

		continueConflictResolution: async (workspaceScope, input) => {
			try {
				const cwd = await resolveWorkingDir(
					workspaceScope.workspacePath,
					input.taskId ? { taskId: input.taskId, baseRef: "" } : null,
				);
				const response = await continueMergeOrRebase(cwd);
				broadcastStateUpdate(workspaceScope);
				return response;
			} catch (error) {
				return {
					ok: false,
					completed: false,
					summary: { ...EMPTY_GIT_SUMMARY },
					output: "",
					error: errorMessage(error),
				} satisfies RuntimeConflictContinueResponse;
			}
		},

		abortConflictResolution: async (workspaceScope, input) => {
			try {
				const cwd = await resolveWorkingDir(
					workspaceScope.workspacePath,
					input.taskId ? { taskId: input.taskId, baseRef: "" } : null,
				);
				const response = await abortMergeOrRebase(cwd);
				broadcastStateUpdate(workspaceScope);
				return response;
			} catch (error) {
				return {
					ok: false,
					summary: { ...EMPTY_GIT_SUMMARY },
					error: errorMessage(error),
				} satisfies RuntimeConflictAbortResponse;
			}
		},

		discardGitChanges: async (workspaceScope, input) => {
			try {
				const taskScope = normalizeOptionalTaskWorkspaceScopeInput(input);
				const cwd = await resolveWorkingDir(workspaceScope.workspacePath, taskScope);
				// Block discard for non-worktree tasks to avoid destroying shared checkout state.
				if (taskScope && resolve(cwd) === resolve(workspaceScope.workspacePath)) {
					return createGitOutputErrorResponse(
						new Error("Cannot discard changes in the shared checkout. Isolate the task to a worktree first."),
					);
				}
				const response = await discardGitChanges({ cwd });
				if (response.ok) refreshGitMetadata(workspaceScope, taskScope);
				return response;
			} catch (error) {
				return createGitOutputErrorResponse(error);
			}
		},

		commitSelectedFiles: async (workspaceScope, input) => {
			try {
				const taskScope = normalizeOptionalTaskWorkspaceScopeInput(input.taskScope);
				const commitCwd = await resolveWorkingDir(workspaceScope.workspacePath, taskScope);
				if (taskScope && resolve(commitCwd) === resolve(workspaceScope.workspacePath)) {
					return createGitOutputErrorResponse(
						new Error("Cannot commit in the shared checkout. Isolate the task to a worktree first."),
					);
				}
				const response = await commitSelectedFiles({
					cwd: commitCwd,
					paths: input.paths,
					message: input.message,
				});
				if (response.ok) {
					// Push after successful commit if requested, reusing the existing git sync infrastructure.
					if (input.pushAfterCommit) {
						const pushResult = await runGitSyncAction({ cwd: commitCwd, action: "push" });
						// Refresh after push — skip the intermediate post-commit refresh to avoid
						// a transient stale broadcast that the post-push refresh immediately supersedes.
						refreshGitMetadata(workspaceScope, taskScope);
						return {
							...response,
							pushOk: pushResult.ok,
							...(!pushResult.ok && { pushError: pushResult.error ?? "Push failed." }),
							// Update summary to reflect post-push state (ahead/behind counts change).
							summary: pushResult.summary,
						};
					}
					refreshGitMetadata(workspaceScope, taskScope);
				}
				return response;
			} catch (error) {
				return createGitOutputErrorResponse(error);
			}
		},

		discardFile: async (workspaceScope, input) => {
			try {
				const taskScope = normalizeOptionalTaskWorkspaceScopeInput(input.taskScope);
				const cwd = await resolveWorkingDir(workspaceScope.workspacePath, taskScope);
				if (taskScope && resolve(cwd) === resolve(workspaceScope.workspacePath)) {
					return createGitOutputErrorResponse(
						new Error("Cannot discard changes in the shared checkout. Isolate the task to a worktree first."),
					);
				}
				const response = await discardSingleFile({
					cwd,
					path: input.path,
					fileStatus: input.fileStatus,
				});
				if (response.ok) refreshGitMetadata(workspaceScope, taskScope);
				return response;
			} catch (error) {
				return createGitOutputErrorResponse(error);
			}
		},

		createBranch: async (workspaceScope, input) => {
			try {
				const result = await createBranchFromRef({
					cwd: workspaceScope.workspacePath,
					branchName: input.branchName,
					startRef: input.startRef,
				});
				if (result.ok) broadcastStateUpdate(workspaceScope);
				return result;
			} catch (error) {
				return { ok: false as const, branchName: input.branchName, error: errorMessage(error) };
			}
		},

		deleteBranch: async (workspaceScope, input) => {
			try {
				const result = await deleteBranch({
					cwd: workspaceScope.workspacePath,
					branchName: input.branchName,
				});
				if (result.ok) broadcastStateUpdate(workspaceScope);
				return result;
			} catch (error) {
				return { ok: false as const, branchName: input.branchName, error: errorMessage(error) };
			}
		},

		cherryPickCommit: async (workspaceScope, input) => {
			try {
				const cwd = await resolveWorkingDir(
					workspaceScope.workspacePath,
					normalizeOptionalTaskWorkspaceScopeInput(input.taskScope ?? null),
				);
				const result = await cherryPickCommit({
					cwd,
					commitHash: input.commitHash,
					targetBranch: input.targetBranch,
				});
				if (result.ok) broadcastStateUpdate(workspaceScope);
				return result;
			} catch (error) {
				return {
					ok: false as const,
					commitHash: input.commitHash,
					targetBranch: input.targetBranch,
					output: "",
					error: errorMessage(error),
				};
			}
		},

		loadChanges: async (workspaceScope, input) => {
			// Ref-based comparison (Compare tab / Compare with uncommitted)
			if (input.fromRef) {
				assertValidGitRef(input.fromRef, "fromRef");
				if (input.toRef) assertValidGitRef(input.toRef, "toRef");

				let cwd = workspaceScope.workspacePath;
				if (input.taskId) {
					const resolved = await tryResolveTaskCwd(
						workspaceScope.workspacePath,
						input.taskId,
						input.baseRef ?? "",
					);
					if (!resolved) return await createEmptyWorkspaceChangesResponse(workspaceScope.workspacePath);
					cwd = resolved;
				}

				if (input.toRef) {
					return await getWorkspaceChangesBetweenRefs({ cwd, fromRef: input.fromRef, toRef: input.toRef });
				}
				return await getWorkspaceChangesFromRef({ cwd, fromRef: input.fromRef });
			}

			// Home repo uncommitted (no task)
			if (!input.taskId) {
				return await getWorkspaceChanges(workspaceScope.workspacePath);
			}

			// Task-scoped
			const normalizedInput = normalizeRequiredTaskWorkspaceScopeInput(input);
			const taskCwd = await tryResolveTaskCwd(
				workspaceScope.workspacePath,
				normalizedInput.taskId,
				normalizedInput.baseRef,
			);
			if (!taskCwd) return await createEmptyWorkspaceChangesResponse(workspaceScope.workspacePath);

			if (normalizedInput.mode === "last_turn") {
				const terminalManager = await deps.ensureTerminalManagerForWorkspace(
					workspaceScope.workspaceId,
					workspaceScope.workspacePath,
				);
				const summary = terminalManager.store.getSummary(normalizedInput.taskId);
				const fromCheckpoint = summary?.previousTurnCheckpoint;
				const toCheckpoint = summary?.latestTurnCheckpoint;
				if (!toCheckpoint) {
					return await createEmptyWorkspaceChangesResponse(taskCwd);
				}
				if (summary?.state === "running" || !fromCheckpoint) {
					return await getWorkspaceChangesFromRef({
						cwd: taskCwd,
						fromRef: toCheckpoint.commit,
					});
				}
				return await getWorkspaceChangesBetweenRefs({
					cwd: taskCwd,
					fromRef: fromCheckpoint.commit,
					toRef: toCheckpoint.commit,
				});
			}
			return await getWorkspaceChanges(taskCwd);
		},

		loadFileDiff: async (workspaceScope, input) => {
			const emptyResult = { path: input.path, oldText: null, newText: null };

			if (!validateGitPath(input.path)) {
				throw new TRPCError({ code: "BAD_REQUEST", message: "Invalid file path." });
			}
			if (input.previousPath && !validateGitPath(input.previousPath)) {
				throw new TRPCError({ code: "BAD_REQUEST", message: "Invalid previous path." });
			}

			// Ref-based comparison (Compare tab)
			if (input.fromRef) {
				assertValidGitRef(input.fromRef, "fromRef");
				if (input.toRef) assertValidGitRef(input.toRef, "toRef");

				let cwd = workspaceScope.workspacePath;
				if (input.taskId) {
					const resolved = await tryResolveTaskCwd(
						workspaceScope.workspacePath,
						input.taskId,
						input.baseRef ?? "",
					);
					if (!resolved) return emptyResult;
					cwd = resolved;
				}

				return await getWorkspaceFileDiff({
					cwd,
					path: input.path,
					previousPath: input.previousPath,
					status: input.status,
					fromRef: input.fromRef,
					toRef: input.toRef,
				});
			}

			// Home repo uncommitted (no task)
			if (!input.taskId) {
				return await getWorkspaceFileDiff({
					cwd: workspaceScope.workspacePath,
					path: input.path,
					previousPath: input.previousPath,
					status: input.status,
				});
			}

			// Task-scoped
			const normalizedInput = normalizeRequiredTaskWorkspaceScopeInput(input);
			const taskCwd = await tryResolveTaskCwd(
				workspaceScope.workspacePath,
				normalizedInput.taskId,
				normalizedInput.baseRef,
			);
			if (!taskCwd) return emptyResult;

			if (normalizedInput.mode === "last_turn") {
				const terminalManager = await deps.ensureTerminalManagerForWorkspace(
					workspaceScope.workspaceId,
					workspaceScope.workspacePath,
				);
				const summary = terminalManager.store.getSummary(normalizedInput.taskId);
				const fromCheckpoint = summary?.previousTurnCheckpoint;
				const toCheckpoint = summary?.latestTurnCheckpoint;
				if (!toCheckpoint) return emptyResult;

				return await getWorkspaceFileDiff({
					cwd: taskCwd,
					path: input.path,
					previousPath: input.previousPath,
					status: input.status,
					fromRef: summary?.state === "running" || !fromCheckpoint ? toCheckpoint.commit : fromCheckpoint.commit,
					toRef: summary?.state === "running" || !fromCheckpoint ? undefined : toCheckpoint.commit,
				});
			}

			return await getWorkspaceFileDiff({
				cwd: taskCwd,
				path: input.path,
				previousPath: input.previousPath,
				status: input.status,
			});
		},

		// Called by the UI's ensureTaskWorkspace (use-task-sessions.ts) for restore-from-trash.
		// The other path to ensureTaskWorktreeIfDoesntExist is startTaskSession in runtime-api.ts,
		// which reads branch from persisted board state server-side instead.
		ensureWorktree: async (workspaceScope, input) => {
			const body = parseWorktreeEnsureRequest(input);
			return await ensureTaskWorktreeIfDoesntExist({
				cwd: workspaceScope.workspacePath,
				taskId: body.taskId,
				baseRef: body.baseRef,
				branch: body.branch ?? undefined,
			});
		},

		deleteWorktree: async (workspaceScope, input) => {
			const body = parseWorktreeDeleteRequest(input);
			const result = await deleteTaskWorktree({
				repoPath: workspaceScope.workspacePath,
				taskId: body.taskId,
			});
			// workingDirectory is cleared by the client when it moves the card
			// to trash (moveTaskToColumn sets workingDirectory = null for trash).
			// The client persists through its normal board state cycle, avoiding
			// a dual-writer race where the server bumps the revision while the
			// client's persist debounce is in flight.
			return result;
		},

		loadTaskContext: async (workspaceScope, input) => {
			const normalizedInput = normalizeRequiredTaskWorkspaceScopeInput(input);
			return await getTaskWorkspaceInfo({
				cwd: workspaceScope.workspacePath,
				taskId: normalizedInput.taskId,
				baseRef: normalizedInput.baseRef,
			});
		},

		searchFiles: async (workspaceScope, input) => {
			const query = input.query.trim();
			const files = await searchWorkspaceFiles(workspaceScope.workspacePath, query, input.limit);
			return { query, files } satisfies RuntimeWorkspaceFileSearchResponse;
		},

		listFiles: async (workspaceScope, input) => {
			// Home-scoped or branch-view: no task resolution needed
			if (!input.taskId) {
				if (input.ref) {
					const files = await listFilesAtRef(workspaceScope.workspacePath, input.ref);
					return { files } satisfies RuntimeListFilesResponse;
				}
				const files = await listAllWorkspaceFiles(workspaceScope.workspacePath);
				return { files } satisfies RuntimeListFilesResponse;
			}

			const normalizedInput = normalizeRequiredTaskWorkspaceScopeInput(input);
			const taskCwd = await tryResolveTaskCwd(
				workspaceScope.workspacePath,
				normalizedInput.taskId,
				normalizedInput.baseRef,
			);
			if (!taskCwd) return { files: [] } satisfies RuntimeListFilesResponse;

			if (input.ref) {
				const files = await listFilesAtRef(taskCwd, input.ref);
				return { files } satisfies RuntimeListFilesResponse;
			}

			const files = await listAllWorkspaceFiles(taskCwd);
			return { files } satisfies RuntimeListFilesResponse;
		},

		getFileContent: async (workspaceScope, input) => {
			const filePath = input.path.trim();
			if (!filePath) throw new Error("Missing path parameter.");

			const EMPTY_FILE_RESPONSE = {
				content: "",
				language: "",
				binary: false,
				size: 0,
				truncated: false,
			} satisfies RuntimeFileContentResponse;

			// Determine the working directory for file reading
			let cwd: string | null;
			if (!input.taskId) {
				cwd = workspaceScope.workspacePath;
			} else {
				const normalizedInput = normalizeRequiredTaskWorkspaceScopeInput(input);
				cwd = await tryResolveTaskCwd(
					workspaceScope.workspacePath,
					normalizedInput.taskId,
					normalizedInput.baseRef,
				);
			}
			if (!cwd) return EMPTY_FILE_RESPONSE;

			// Ref-based content: read from git object store
			if (input.ref) {
				const refContent = await getFileContentAtRef(cwd, input.ref, filePath);
				if (!refContent) return EMPTY_FILE_RESPONSE;
				return {
					content: refContent.content,
					language: "",
					binary: refContent.binary,
					size: refContent.content.length,
					truncated: false,
				} satisfies RuntimeFileContentResponse;
			}

			// Disk-based content: existing behavior
			return await readWorkspaceFile(cwd, filePath);
		},

		loadState: async (workspaceScope) => {
			return await deps.buildWorkspaceStateSnapshot(workspaceScope.workspaceId, workspaceScope.workspacePath);
		},

		notifyStateUpdated: async (workspaceScope) => {
			broadcastStateUpdate(workspaceScope);
			void deps.broadcastRuntimeProjectsUpdated(workspaceScope.workspaceId);
			return { ok: true };
		},

		saveState: async (workspaceScope, input) => {
			try {
				const terminalManager = await deps.ensureTerminalManagerForWorkspace(
					workspaceScope.workspaceId,
					workspaceScope.workspacePath,
				);
				for (const summary of terminalManager.store.listSummaries()) {
					input.sessions[summary.taskId] = summary;
				}
				const response = await saveWorkspaceState(workspaceScope.workspacePath, input);
				broadcastStateUpdate(workspaceScope);
				void deps.broadcastRuntimeProjectsUpdated(workspaceScope.workspaceId);

				// Fire-and-forget: generate titles for any new cards that have title === null.
				// Cap concurrency to avoid flooding the LLM proxy when many cards are created at once.
				const untitledCards = input.board.columns.flatMap((col) => col.cards.filter((card) => card.title === null));
				const generateTitle = async (card: (typeof untitledCards)[number]) => {
					const title = await generateTaskTitle(card.prompt);
					if (!title) return;
					// Send the title to the UI via a lightweight message. The client
					// applies it to its board state and persists through its normal
					// cycle, avoiding a dual-writer race where mutateWorkspaceState
					// would bump the revision while the client's persist is in flight.
					deps.broadcastTaskTitleUpdated(workspaceScope.workspaceId, card.id, title, { autoGenerated: true });
				};
				if (untitledCards.length > 0) {
					void (async () => {
						for (let i = 0; i < untitledCards.length; i += MAX_CONCURRENT_TITLE_REQUESTS) {
							const batch = untitledCards.slice(i, i + MAX_CONCURRENT_TITLE_REQUESTS);
							await Promise.allSettled(batch.map(generateTitle));
						}
					})();
				}

				return response;
			} catch (error) {
				if (error instanceof WorkspaceStateConflictError) {
					throw new TRPCError({
						code: "CONFLICT",
						message: error.message,
						cause: { currentRevision: error.currentRevision },
					});
				}
				throw error;
			}
		},

		loadWorkspaceChanges: async (workspaceScope) => {
			return await getWorkspaceChanges(workspaceScope.workspacePath);
		},

		loadGitLog: async (workspaceScope, input) => {
			const cwd = await resolveWorkingDir(
				workspaceScope.workspacePath,
				normalizeOptionalTaskWorkspaceScopeInput(input.taskScope ?? null),
			);
			return await getGitLog({
				cwd,
				ref: input.ref ?? null,
				refs: input.refs ?? null,
				maxCount: input.maxCount,
				skip: input.skip,
			});
		},

		loadGitRefs: async (workspaceScope, input) => {
			const cwd = await resolveWorkingDir(
				workspaceScope.workspacePath,
				normalizeOptionalTaskWorkspaceScopeInput(input ?? null),
			);
			return await getGitRefs(cwd);
		},

		loadCommitDiff: async (workspaceScope, input) => {
			const cwd = await resolveWorkingDir(
				workspaceScope.workspacePath,
				normalizeOptionalTaskWorkspaceScopeInput(input.taskScope ?? null),
			);
			return await getCommitDiff({ cwd, commitHash: input.commitHash });
		},

		getDiffText: async (workspaceScope, taskScope, paths) => {
			const cwd = await resolveWorkingDir(workspaceScope.workspacePath, taskScope);
			// Get unified diff for selected paths (or all changes if no paths specified).
			const args = ["diff", "HEAD", "--"];
			if (paths && paths.length > 0) {
				args.push(...paths);
			}
			return await getGitStdout(args, cwd);
		},

		notifyTaskTitleUpdated: (workspaceScope, taskId, title) => {
			deps.broadcastTaskTitleUpdated(workspaceScope.workspaceId, taskId, title);
		},

		setTaskDisplaySummary: async (workspaceScope, taskId, text, generatedAt) => {
			const manager = await deps.ensureTerminalManagerForWorkspace(
				workspaceScope.workspaceId,
				workspaceScope.workspacePath,
			);
			manager.store.setDisplaySummary(taskId, text, generatedAt);
			broadcastStateUpdate(workspaceScope);
		},

		setFocusedTask: (workspaceScope, taskId) => {
			deps.setFocusedTask(workspaceScope.workspaceId, taskId);
		},

		stashPush: async (workspaceScope, input) => {
			try {
				const taskScope = normalizeOptionalTaskWorkspaceScopeInput(input.taskScope);
				const cwd = await resolveWorkingDir(workspaceScope.workspacePath, taskScope);
				const response = await stashPush({ cwd, paths: input.paths, message: input.message });
				if (response.ok) refreshGitMetadata(workspaceScope, taskScope);
				return response;
			} catch (error) {
				return { ok: false, error: errorMessage(error) } satisfies RuntimeStashPushResponse;
			}
		},

		stashList: async (workspaceScope, input) => {
			try {
				const cwd = await resolveWorkingDir(
					workspaceScope.workspacePath,
					normalizeOptionalTaskWorkspaceScopeInput(input.taskScope),
				);
				return await stashList(cwd);
			} catch (error) {
				return { ok: false, entries: [], error: errorMessage(error) } satisfies RuntimeStashListResponse;
			}
		},

		stashPop: async (workspaceScope, input) => {
			try {
				const taskScope = normalizeOptionalTaskWorkspaceScopeInput(input.taskScope);
				const cwd = await resolveWorkingDir(workspaceScope.workspacePath, taskScope);
				const response = await stashPop({ cwd, index: input.index });
				if (response.ok || response.conflicted) refreshGitMetadata(workspaceScope, taskScope);
				return response;
			} catch (error) {
				return { ok: false, conflicted: false, error: errorMessage(error) } satisfies RuntimeStashPopApplyResponse;
			}
		},

		stashApply: async (workspaceScope, input) => {
			try {
				const taskScope = normalizeOptionalTaskWorkspaceScopeInput(input.taskScope);
				const cwd = await resolveWorkingDir(workspaceScope.workspacePath, taskScope);
				const response = await stashApply({ cwd, index: input.index });
				if (response.ok || response.conflicted) refreshGitMetadata(workspaceScope, taskScope);
				return response;
			} catch (error) {
				return { ok: false, conflicted: false, error: errorMessage(error) } satisfies RuntimeStashPopApplyResponse;
			}
		},

		stashDrop: async (workspaceScope, input) => {
			try {
				const taskScope = normalizeOptionalTaskWorkspaceScopeInput(input.taskScope);
				const cwd = await resolveWorkingDir(workspaceScope.workspacePath, taskScope);
				const response = await stashDrop({ cwd, index: input.index });
				if (response.ok) refreshGitMetadata(workspaceScope, taskScope);
				return response;
			} catch (error) {
				return { ok: false, error: errorMessage(error) } satisfies RuntimeStashDropResponse;
			}
		},

		stashShow: async (workspaceScope, input) => {
			try {
				const cwd = await resolveWorkingDir(
					workspaceScope.workspacePath,
					normalizeOptionalTaskWorkspaceScopeInput(input.taskScope),
				);
				return await stashShow({ cwd, index: input.index });
			} catch (error) {
				return { ok: false, error: errorMessage(error) } satisfies RuntimeStashShowResponse;
			}
		},
	};
}
