import { resolve } from "node:path";
import { TRPCError } from "@trpc/server";
import type {
	RuntimeConflictAbortResponse,
	RuntimeConflictContinueResponse,
	RuntimeConflictFilesResponse,
	RuntimeFileContentResponse,
	RuntimeGitCheckoutResponse,
	RuntimeGitCommitResponse,
	RuntimeGitDiscardResponse,
	RuntimeGitMergeResponse,
	RuntimeGitSummaryResponse,
	RuntimeGitSyncAction,
	RuntimeGitSyncResponse,
	RuntimeListFilesResponse,
	RuntimeWorkspaceChangesMode,
	RuntimeWorkspaceFileSearchResponse,
	RuntimeWorkspaceStateResponse,
} from "../core/api-contract";
import {
	parseGitCheckoutRequest,
	parseWorktreeDeleteRequest,
	parseWorktreeEnsureRequest,
} from "../core/api-validation";
import { loadWorkspaceState, saveWorkspaceState, WorkspaceStateConflictError } from "../state/workspace-state";
import type { TerminalSessionManager } from "../terminal/session-manager";
import { generateTaskTitle } from "../title/title-generator";
import {
	createEmptyWorkspaceChangesResponse,
	getWorkspaceChanges,
	getWorkspaceChangesBetweenRefs,
	getWorkspaceChangesFromRef,
	validateRef,
} from "../workspace/get-workspace-changes";
import { getCommitDiff, getGitLog, getGitRefs } from "../workspace/git-history";
import {
	abortMergeOrRebase,
	commitSelectedFiles,
	continueMergeOrRebase,
	createBranchFromRef,
	deleteBranch,
	discardGitChanges,
	discardSingleFile,
	getConflictFileContent,
	getGitSyncSummary,
	resolveConflictFile as gitResolveConflictFile,
	runGitCheckoutAction,
	runGitMergeAction,
	runGitSyncAction,
} from "../workspace/git-sync";
import { getFileContentAtRef, listFilesAtRef } from "../workspace/git-utils";
import { readWorkspaceFile } from "../workspace/read-workspace-file";
import { listAllWorkspaceFiles, searchWorkspaceFiles } from "../workspace/search-workspace-files";
import {
	deleteTaskWorktree,
	ensureTaskWorktreeIfDoesntExist,
	getTaskWorkspaceInfo,
	isMissingTaskWorktreeError,
	resolveTaskWorkingDirectory,
} from "../workspace/task-worktree";
import type { RuntimeTrpcContext } from "./app-router";

const MAX_CONCURRENT_TITLE_REQUESTS = 3;

export interface CreateWorkspaceApiDependencies {
	ensureTerminalManagerForWorkspace: (workspaceId: string, repoPath: string) => Promise<TerminalSessionManager>;
	broadcastRuntimeWorkspaceStateUpdated: (workspaceId: string, workspacePath: string) => Promise<void> | void;
	broadcastRuntimeProjectsUpdated: (preferredCurrentProjectId: string | null) => Promise<void> | void;
	broadcastTaskTitleUpdated: (
		workspaceId: string,
		taskId: string,
		title: string,
		options?: { autoGenerated?: boolean },
	) => void;
	buildWorkspaceStateSnapshot: (workspaceId: string, workspacePath: string) => Promise<RuntimeWorkspaceStateResponse>;
	setFocusedTask: (workspaceId: string, taskId: string | null) => void;
}

function normalizeOptionalTaskWorkspaceScopeInput(
	input: { taskId: string; baseRef: string } | null,
): { taskId: string; baseRef: string } | null {
	if (!input) {
		return null;
	}
	const taskId = input.taskId.trim();
	const baseRef = input.baseRef.trim();
	if (!taskId || !baseRef) {
		throw new Error("baseRef query parameter requires taskId.");
	}
	return {
		taskId,
		baseRef,
	};
}

function normalizeRequiredTaskWorkspaceScopeInput(input: {
	taskId: string | null;
	baseRef?: string;
	mode?: RuntimeWorkspaceChangesMode;
}): {
	taskId: string;
	baseRef: string;
	mode: RuntimeWorkspaceChangesMode;
} {
	const taskId = (input.taskId ?? "").trim();
	const baseRef = (input.baseRef ?? "").trim();
	if (!taskId) {
		throw new Error("Missing taskId query parameter.");
	}
	if (!baseRef) {
		throw new Error("Missing baseRef query parameter.");
	}
	const mode: RuntimeWorkspaceChangesMode = input.mode ?? "working_copy";
	return {
		taskId,
		baseRef,
		mode,
	};
}

function createEmptyGitSummaryErrorResponse(error: unknown): RuntimeGitSummaryResponse {
	const message = error instanceof Error ? error.message : String(error);
	return {
		ok: false,
		summary: {
			currentBranch: null,
			upstreamBranch: null,
			changedFiles: 0,
			additions: 0,
			deletions: 0,
			aheadCount: 0,
			behindCount: 0,
		},
		error: message,
	};
}

function createEmptyGitSyncErrorResponse(action: RuntimeGitSyncAction, error: unknown): RuntimeGitSyncResponse {
	const message = error instanceof Error ? error.message : String(error);
	return {
		ok: false,
		action,
		summary: {
			currentBranch: null,
			upstreamBranch: null,
			changedFiles: 0,
			additions: 0,
			deletions: 0,
			aheadCount: 0,
			behindCount: 0,
		},
		output: "",
		error: message,
	};
}

function createEmptyGitCheckoutErrorResponse(error: unknown): RuntimeGitCheckoutResponse {
	const message = error instanceof Error ? error.message : String(error);
	return {
		ok: false,
		branch: "",
		summary: {
			currentBranch: null,
			upstreamBranch: null,
			changedFiles: 0,
			additions: 0,
			deletions: 0,
			aheadCount: 0,
			behindCount: 0,
		},
		output: "",
		error: message,
	};
}

function createEmptyGitMergeErrorResponse(error: unknown): RuntimeGitMergeResponse {
	const message = error instanceof Error ? error.message : String(error);
	return {
		ok: false,
		branch: "",
		summary: {
			currentBranch: null,
			upstreamBranch: null,
			changedFiles: 0,
			additions: 0,
			deletions: 0,
			aheadCount: 0,
			behindCount: 0,
		},
		output: "",
		error: message,
	};
}

function createEmptyGitDiscardErrorResponse(error: unknown): RuntimeGitDiscardResponse {
	const message = error instanceof Error ? error.message : String(error);
	return {
		ok: false,
		summary: {
			currentBranch: null,
			upstreamBranch: null,
			changedFiles: 0,
			additions: 0,
			deletions: 0,
			aheadCount: 0,
			behindCount: 0,
		},
		output: "",
		error: message,
	};
}

function createEmptyGitCommitErrorResponse(error: unknown): RuntimeGitCommitResponse {
	const message = error instanceof Error ? error.message : String(error);
	return {
		ok: false,
		summary: {
			currentBranch: null,
			upstreamBranch: null,
			changedFiles: 0,
			additions: 0,
			deletions: 0,
			aheadCount: 0,
			behindCount: 0,
		},
		output: "",
		error: message,
	};
}

export function createWorkspaceApi(deps: CreateWorkspaceApiDependencies): RuntimeTrpcContext["workspaceApi"] {
	return {
		loadGitSummary: async (workspaceScope, input) => {
			try {
				const taskScope = normalizeOptionalTaskWorkspaceScopeInput(input);
				let summaryCwd = workspaceScope.workspacePath;
				if (taskScope) {
					summaryCwd = await resolveTaskWorkingDirectory({
						workspacePath: workspaceScope.workspacePath,
						...taskScope,
					});
				}
				const summary = await getGitSyncSummary(summaryCwd);
				return {
					ok: true,
					summary,
				} satisfies RuntimeGitSummaryResponse;
			} catch (error) {
				return createEmptyGitSummaryErrorResponse(error);
			}
		},
		runGitSyncAction: async (workspaceScope, input) => {
			try {
				return await runGitSyncAction({
					cwd: workspaceScope.workspacePath,
					action: input.action,
				});
			} catch (error) {
				return createEmptyGitSyncErrorResponse(input.action, error);
			}
		},
		checkoutGitBranch: async (workspaceScope, input) => {
			try {
				const body = parseGitCheckoutRequest(input);

				// Task-scoped checkout: resolve task worktree and checkout there
				if (input.taskId) {
					const taskCwd = await resolveTaskWorkingDirectory({
						workspacePath: workspaceScope.workspacePath,
						taskId: input.taskId,
						baseRef: input.baseRef ?? "",
					});
					const response = await runGitCheckoutAction({
						cwd: taskCwd,
						branch: body.branch,
					});
					return response;
				}

				// Home repo checkout: block when an active task is running in the shared checkout
				const state = await loadWorkspaceState(workspaceScope.workspacePath);
				const activeColumnIds = new Set(["in_progress", "review"]);
				const hasSharedCheckoutTask = state.board.columns
					.filter((col) => activeColumnIds.has(col.id))
					.some((col) =>
						col.cards.some((card) => {
							const isSharedCheckout = card.workingDirectory
								? resolve(card.workingDirectory) === resolve(workspaceScope.workspacePath)
								: card.useWorktree === false;
							return isSharedCheckout;
						}),
					);
				if (hasSharedCheckoutTask) {
					return createEmptyGitCheckoutErrorResponse(
						new Error(
							"Cannot switch branches while a task in the shared checkout is in progress or review. Isolate the task or move it to another column first.",
						),
					);
				}
				const response = await runGitCheckoutAction({
					cwd: workspaceScope.workspacePath,
					branch: body.branch,
				});
				if (response.ok) {
					void deps.broadcastRuntimeWorkspaceStateUpdated(
						workspaceScope.workspaceId,
						workspaceScope.workspacePath,
					);
				}
				return response;
			} catch (error) {
				return createEmptyGitCheckoutErrorResponse(error);
			}
		},
		mergeBranch: async (workspaceScope, input) => {
			try {
				const branchToMerge = input.branch.trim();
				if (!branchToMerge) {
					return createEmptyGitMergeErrorResponse(new Error("Branch name cannot be empty."));
				}

				// Task-scoped merge: resolve task worktree and merge there
				if (input.taskId) {
					const taskCwd = await resolveTaskWorkingDirectory({
						workspacePath: workspaceScope.workspacePath,
						taskId: input.taskId,
						baseRef: input.baseRef ?? "",
					});
					const response = await runGitMergeAction({ cwd: taskCwd, branch: branchToMerge });
					return response;
				}

				// Home repo merge: block when an active task is running in the shared checkout
				const state = await loadWorkspaceState(workspaceScope.workspacePath);
				const activeColumnIds = new Set(["in_progress", "review"]);
				const hasSharedCheckoutTask = state.board.columns
					.filter((col) => activeColumnIds.has(col.id))
					.some((col) =>
						col.cards.some((card) => {
							const isSharedCheckout = card.workingDirectory
								? resolve(card.workingDirectory) === resolve(workspaceScope.workspacePath)
								: card.useWorktree === false;
							return isSharedCheckout;
						}),
					);
				if (hasSharedCheckoutTask) {
					return createEmptyGitMergeErrorResponse(
						new Error(
							"Cannot merge while a task in the shared checkout is in progress or review. Isolate the task or move it to another column first.",
						),
					);
				}
				const response = await runGitMergeAction({ cwd: workspaceScope.workspacePath, branch: branchToMerge });
				if (response.ok) {
					void deps.broadcastRuntimeWorkspaceStateUpdated(
						workspaceScope.workspaceId,
						workspaceScope.workspacePath,
					);
				}
				if (!response.ok && response.conflictState) {
					void deps.broadcastRuntimeWorkspaceStateUpdated(
						workspaceScope.workspaceId,
						workspaceScope.workspacePath,
					);
				}
				return response;
			} catch (error) {
				return createEmptyGitMergeErrorResponse(error);
			}
		},
		getConflictFiles: async (workspaceScope, input) => {
			try {
				let cwd = workspaceScope.workspacePath;
				if (input.taskId) {
					cwd = await resolveTaskWorkingDirectory({
						workspacePath: workspaceScope.workspacePath,
						taskId: input.taskId,
						baseRef: "",
					});
				}
				const files = await Promise.all(input.paths.map((path) => getConflictFileContent(cwd, path)));
				return { ok: true, files } satisfies RuntimeConflictFilesResponse;
			} catch (error) {
				const message = error instanceof Error ? error.message : String(error);
				return { ok: false, files: [], error: message } satisfies RuntimeConflictFilesResponse;
			}
		},
		resolveConflictFile: async (workspaceScope, input) => {
			try {
				let cwd = workspaceScope.workspacePath;
				if (input.taskId) {
					cwd = await resolveTaskWorkingDirectory({
						workspacePath: workspaceScope.workspacePath,
						taskId: input.taskId,
						baseRef: "",
					});
				}
				const result = await gitResolveConflictFile(cwd, input.path, input.resolution);
				if (result.ok) {
					void deps.broadcastRuntimeWorkspaceStateUpdated(
						workspaceScope.workspaceId,
						workspaceScope.workspacePath,
					);
				}
				return result;
			} catch (error) {
				const message = error instanceof Error ? error.message : String(error);
				return { ok: false, error: message };
			}
		},
		continueConflictResolution: async (workspaceScope, input) => {
			try {
				let cwd = workspaceScope.workspacePath;
				if (input.taskId) {
					cwd = await resolveTaskWorkingDirectory({
						workspacePath: workspaceScope.workspacePath,
						taskId: input.taskId,
						baseRef: "",
					});
				}
				const response = await continueMergeOrRebase(cwd);
				void deps.broadcastRuntimeWorkspaceStateUpdated(workspaceScope.workspaceId, workspaceScope.workspacePath);
				return response;
			} catch (error) {
				const message = error instanceof Error ? error.message : String(error);
				return {
					ok: false,
					completed: false,
					summary: {
						currentBranch: null,
						upstreamBranch: null,
						changedFiles: 0,
						additions: 0,
						deletions: 0,
						aheadCount: 0,
						behindCount: 0,
					},
					output: "",
					error: message,
				} satisfies RuntimeConflictContinueResponse;
			}
		},
		abortConflictResolution: async (workspaceScope, input) => {
			try {
				let cwd = workspaceScope.workspacePath;
				if (input.taskId) {
					cwd = await resolveTaskWorkingDirectory({
						workspacePath: workspaceScope.workspacePath,
						taskId: input.taskId,
						baseRef: "",
					});
				}
				const response = await abortMergeOrRebase(cwd);
				void deps.broadcastRuntimeWorkspaceStateUpdated(workspaceScope.workspaceId, workspaceScope.workspacePath);
				return response;
			} catch (error) {
				const message = error instanceof Error ? error.message : String(error);
				return {
					ok: false,
					summary: {
						currentBranch: null,
						upstreamBranch: null,
						changedFiles: 0,
						additions: 0,
						deletions: 0,
						aheadCount: 0,
						behindCount: 0,
					},
					error: message,
				} satisfies RuntimeConflictAbortResponse;
			}
		},
		discardGitChanges: async (workspaceScope, input) => {
			try {
				const taskScope = normalizeOptionalTaskWorkspaceScopeInput(input);
				let discardCwd = workspaceScope.workspacePath;
				if (taskScope) {
					discardCwd = await resolveTaskWorkingDirectory({
						workspacePath: workspaceScope.workspacePath,
						...taskScope,
					});
					// Block discard for non-worktree tasks to avoid destroying shared checkout state.
					if (resolve(discardCwd) === resolve(workspaceScope.workspacePath)) {
						return createEmptyGitDiscardErrorResponse(
							new Error("Cannot discard changes in the shared checkout. Isolate the task to a worktree first."),
						);
					}
				}
				const response = await discardGitChanges({
					cwd: discardCwd,
				});
				if (response.ok) {
					void deps.broadcastRuntimeWorkspaceStateUpdated(
						workspaceScope.workspaceId,
						workspaceScope.workspacePath,
					);
				}
				return response;
			} catch (error) {
				return createEmptyGitDiscardErrorResponse(error);
			}
		},
		commitSelectedFiles: async (workspaceScope, input) => {
			try {
				const taskScope = normalizeOptionalTaskWorkspaceScopeInput(input.taskScope);
				let commitCwd = workspaceScope.workspacePath;
				if (taskScope) {
					commitCwd = await resolveTaskWorkingDirectory({
						workspacePath: workspaceScope.workspacePath,
						...taskScope,
					});
					if (resolve(commitCwd) === resolve(workspaceScope.workspacePath)) {
						return createEmptyGitCommitErrorResponse(
							new Error("Cannot commit in the shared checkout. Isolate the task to a worktree first."),
						);
					}
				}
				const response = await commitSelectedFiles({
					cwd: commitCwd,
					paths: input.paths,
					message: input.message,
				});
				if (response.ok) {
					void deps.broadcastRuntimeWorkspaceStateUpdated(
						workspaceScope.workspaceId,
						workspaceScope.workspacePath,
					);
				}
				return response;
			} catch (error) {
				return createEmptyGitCommitErrorResponse(error);
			}
		},
		discardFile: async (workspaceScope, input) => {
			try {
				const taskScope = normalizeOptionalTaskWorkspaceScopeInput(input.taskScope);
				let discardCwd = workspaceScope.workspacePath;
				if (taskScope) {
					discardCwd = await resolveTaskWorkingDirectory({
						workspacePath: workspaceScope.workspacePath,
						...taskScope,
					});
					if (resolve(discardCwd) === resolve(workspaceScope.workspacePath)) {
						return createEmptyGitDiscardErrorResponse(
							new Error("Cannot discard changes in the shared checkout. Isolate the task to a worktree first."),
						);
					}
				}
				const response = await discardSingleFile({
					cwd: discardCwd,
					path: input.path,
					fileStatus: input.fileStatus,
				});
				if (response.ok) {
					void deps.broadcastRuntimeWorkspaceStateUpdated(
						workspaceScope.workspaceId,
						workspaceScope.workspacePath,
					);
				}
				return response;
			} catch (error) {
				return createEmptyGitDiscardErrorResponse(error);
			}
		},
		createBranch: async (workspaceScope, input) => {
			try {
				const result = await createBranchFromRef({
					cwd: workspaceScope.workspacePath,
					branchName: input.branchName,
					startRef: input.startRef,
				});
				if (result.ok) {
					void deps.broadcastRuntimeWorkspaceStateUpdated(
						workspaceScope.workspaceId,
						workspaceScope.workspacePath,
					);
				}
				return result;
			} catch (error) {
				const message = error instanceof Error ? error.message : String(error);
				return { ok: false as const, branchName: input.branchName, error: message };
			}
		},
		deleteBranch: async (workspaceScope, input) => {
			try {
				const result = await deleteBranch({
					cwd: workspaceScope.workspacePath,
					branchName: input.branchName,
				});
				if (result.ok) {
					void deps.broadcastRuntimeWorkspaceStateUpdated(
						workspaceScope.workspaceId,
						workspaceScope.workspacePath,
					);
				}
				return result;
			} catch (error) {
				const message = error instanceof Error ? error.message : String(error);
				return { ok: false as const, branchName: input.branchName, error: message };
			}
		},
		loadChanges: async (workspaceScope, input) => {
			// Path A: Ref-to-ref comparison (Compare tab)
			if (input.fromRef && input.toRef) {
				validateRef(input.fromRef, "fromRef");
				validateRef(input.toRef, "toRef");
				let cwd: string;
				if (input.taskId) {
					try {
						cwd = await resolveTaskWorkingDirectory({
							workspacePath: workspaceScope.workspacePath,
							taskId: input.taskId,
							baseRef: input.baseRef ?? "",
						});
					} catch (error) {
						if (isMissingTaskWorktreeError(error)) {
							return await createEmptyWorkspaceChangesResponse(workspaceScope.workspacePath);
						}
						throw error;
					}
				} else {
					cwd = workspaceScope.workspacePath;
				}
				return await getWorkspaceChangesBetweenRefs({ cwd, fromRef: input.fromRef, toRef: input.toRef });
			}

			// Path B: Home repo uncommitted (no task)
			if (!input.taskId) {
				return await getWorkspaceChanges(workspaceScope.workspacePath);
			}

			// Path C & D: Task-scoped (existing behavior)
			const normalizedInput = normalizeRequiredTaskWorkspaceScopeInput(input);
			let taskCwd: string;
			try {
				taskCwd = await resolveTaskWorkingDirectory({
					workspacePath: workspaceScope.workspacePath,
					...normalizedInput,
				});
			} catch (error) {
				if (isMissingTaskWorktreeError(error)) {
					return await createEmptyWorkspaceChangesResponse(workspaceScope.workspacePath);
				}
				throw error;
			}
			if (normalizedInput.mode === "last_turn") {
				const terminalManager = await deps.ensureTerminalManagerForWorkspace(
					workspaceScope.workspaceId,
					workspaceScope.workspacePath,
				);
				const summary = terminalManager.store.getSummary(normalizedInput.taskId);
				const fromCheckpoint = summary?.previousTurnCheckpoint;
				const toCheckpoint = summary?.latestTurnCheckpoint;
				if (!toCheckpoint) {
					return await createEmptyWorkspaceChangesResponse(taskCwd);
				}
				if (summary?.state === "running" || !fromCheckpoint) {
					return await getWorkspaceChangesFromRef({
						cwd: taskCwd,
						fromRef: toCheckpoint.commit,
					});
				}
				return await getWorkspaceChangesBetweenRefs({
					cwd: taskCwd,
					fromRef: fromCheckpoint.commit,
					toRef: toCheckpoint.commit,
				});
			}
			return await getWorkspaceChanges(taskCwd);
		},
		// Called by the UI's ensureTaskWorkspace (use-task-sessions.ts) for restore-from-trash.
		// The other path to ensureTaskWorktreeIfDoesntExist is startTaskSession in runtime-api.ts,
		// which reads branch from persisted board state server-side instead.
		ensureWorktree: async (workspaceScope, input) => {
			const body = parseWorktreeEnsureRequest(input);
			return await ensureTaskWorktreeIfDoesntExist({
				cwd: workspaceScope.workspacePath,
				taskId: body.taskId,
				baseRef: body.baseRef,
				branch: body.branch ?? undefined,
			});
		},
		deleteWorktree: async (workspaceScope, input) => {
			const body = parseWorktreeDeleteRequest(input);
			const result = await deleteTaskWorktree({
				repoPath: workspaceScope.workspacePath,
				taskId: body.taskId,
			});
			// workingDirectory is cleared by the client when it moves the card
			// to trash (moveTaskToColumn sets workingDirectory = null for trash).
			// The client persists through its normal board state cycle, avoiding
			// a dual-writer race where the server bumps the revision while the
			// client's persist debounce is in flight.
			return result;
		},
		loadTaskContext: async (workspaceScope, input) => {
			const normalizedInput = normalizeRequiredTaskWorkspaceScopeInput(input);
			return await getTaskWorkspaceInfo({
				cwd: workspaceScope.workspacePath,
				taskId: normalizedInput.taskId,
				baseRef: normalizedInput.baseRef,
			});
		},
		searchFiles: async (workspaceScope, input) => {
			const query = input.query.trim();
			const limit = input.limit;
			const files = await searchWorkspaceFiles(workspaceScope.workspacePath, query, limit);
			return {
				query,
				files,
			} satisfies RuntimeWorkspaceFileSearchResponse;
		},
		listFiles: async (workspaceScope, input) => {
			// Home-scoped or branch-view: no task resolution needed
			if (!input.taskId) {
				if (input.ref) {
					const files = await listFilesAtRef(workspaceScope.workspacePath, input.ref);
					return { files } satisfies RuntimeListFilesResponse;
				}
				const files = await listAllWorkspaceFiles(workspaceScope.workspacePath);
				return { files } satisfies RuntimeListFilesResponse;
			}

			// Ref-based browsing against a task worktree's repo
			if (input.ref) {
				const normalizedInput = normalizeRequiredTaskWorkspaceScopeInput(input);
				let taskCwd: string;
				try {
					taskCwd = await resolveTaskWorkingDirectory({
						workspacePath: workspaceScope.workspacePath,
						...normalizedInput,
					});
				} catch (error) {
					if (!isMissingTaskWorktreeError(error)) {
						throw error;
					}
					return { files: [] } satisfies RuntimeListFilesResponse;
				}
				const files = await listFilesAtRef(taskCwd, input.ref);
				return { files } satisfies RuntimeListFilesResponse;
			}

			// Task-scoped: existing behavior
			const normalizedInput = normalizeRequiredTaskWorkspaceScopeInput(input);
			let taskCwd: string;
			try {
				taskCwd = await resolveTaskWorkingDirectory({
					workspacePath: workspaceScope.workspacePath,
					...normalizedInput,
				});
			} catch (error) {
				if (!isMissingTaskWorktreeError(error)) {
					throw error;
				}
				return { files: [] } satisfies RuntimeListFilesResponse;
			}
			const files = await listAllWorkspaceFiles(taskCwd);
			return { files } satisfies RuntimeListFilesResponse;
		},
		getFileContent: async (workspaceScope, input) => {
			const filePath = input.path.trim();
			if (!filePath) {
				throw new Error("Missing path parameter.");
			}

			// Determine the working directory for file reading
			const resolveCwd = async (): Promise<string | null> => {
				if (!input.taskId) {
					return workspaceScope.workspacePath;
				}
				const normalizedInput = normalizeRequiredTaskWorkspaceScopeInput(input);
				try {
					return await resolveTaskWorkingDirectory({
						workspacePath: workspaceScope.workspacePath,
						...normalizedInput,
					});
				} catch (error) {
					if (isMissingTaskWorktreeError(error)) {
						return null;
					}
					throw error;
				}
			};

			const cwd = await resolveCwd();
			if (!cwd) {
				return {
					content: "",
					language: "",
					binary: false,
					size: 0,
					truncated: false,
				} satisfies RuntimeFileContentResponse;
			}

			// Ref-based content: read from git object store
			if (input.ref) {
				const refContent = await getFileContentAtRef(cwd, input.ref, filePath);
				if (!refContent) {
					return {
						content: "",
						language: "",
						binary: false,
						size: 0,
						truncated: false,
					} satisfies RuntimeFileContentResponse;
				}
				return {
					content: refContent.content,
					language: "",
					binary: refContent.binary,
					size: refContent.content.length,
					truncated: false,
				} satisfies RuntimeFileContentResponse;
			}

			// Disk-based content: existing behavior
			return await readWorkspaceFile(cwd, filePath);
		},
		loadState: async (workspaceScope) => {
			return await deps.buildWorkspaceStateSnapshot(workspaceScope.workspaceId, workspaceScope.workspacePath);
		},
		notifyStateUpdated: async (workspaceScope) => {
			void deps.broadcastRuntimeWorkspaceStateUpdated(workspaceScope.workspaceId, workspaceScope.workspacePath);
			void deps.broadcastRuntimeProjectsUpdated(workspaceScope.workspaceId);
			return {
				ok: true,
			};
		},
		saveState: async (workspaceScope, input) => {
			try {
				const terminalManager = await deps.ensureTerminalManagerForWorkspace(
					workspaceScope.workspaceId,
					workspaceScope.workspacePath,
				);
				for (const summary of terminalManager.store.listSummaries()) {
					input.sessions[summary.taskId] = summary;
				}
				const response = await saveWorkspaceState(workspaceScope.workspacePath, input);
				void deps.broadcastRuntimeWorkspaceStateUpdated(workspaceScope.workspaceId, workspaceScope.workspacePath);
				void deps.broadcastRuntimeProjectsUpdated(workspaceScope.workspaceId);

				// Fire-and-forget: generate titles for any new cards that have title === null.
				// Cap concurrency to avoid flooding the LLM proxy when many cards are created at once.
				const untitledCards = input.board.columns.flatMap((col) => col.cards.filter((card) => card.title === null));
				const generateTitle = async (card: (typeof untitledCards)[number]) => {
					const title = await generateTaskTitle(card.prompt);
					if (!title) {
						return;
					}
					// Send the title to the UI via a lightweight message. The client
					// applies it to its board state and persists through its normal
					// cycle, avoiding a dual-writer race where mutateWorkspaceState
					// would bump the revision while the client's persist is in flight.
					deps.broadcastTaskTitleUpdated(workspaceScope.workspaceId, card.id, title, { autoGenerated: true });
				};
				if (untitledCards.length > 0) {
					void (async () => {
						for (let i = 0; i < untitledCards.length; i += MAX_CONCURRENT_TITLE_REQUESTS) {
							const batch = untitledCards.slice(i, i + MAX_CONCURRENT_TITLE_REQUESTS);
							await Promise.allSettled(batch.map(generateTitle));
						}
					})();
				}

				return response;
			} catch (error) {
				if (error instanceof WorkspaceStateConflictError) {
					throw new TRPCError({
						code: "CONFLICT",
						message: error.message,
						cause: {
							currentRevision: error.currentRevision,
						},
					});
				}
				throw error;
			}
		},
		loadWorkspaceChanges: async (workspaceScope) => {
			return await getWorkspaceChanges(workspaceScope.workspacePath);
		},
		loadGitLog: async (workspaceScope, input) => {
			const taskScope = normalizeOptionalTaskWorkspaceScopeInput(input.taskScope ?? null);
			let logCwd = workspaceScope.workspacePath;
			if (taskScope) {
				logCwd = await resolveTaskWorkingDirectory({ workspacePath: workspaceScope.workspacePath, ...taskScope });
			}
			return await getGitLog({
				cwd: logCwd,
				ref: input.ref ?? null,
				refs: input.refs ?? null,
				maxCount: input.maxCount,
				skip: input.skip,
			});
		},
		loadGitRefs: async (workspaceScope, input) => {
			const taskScope = normalizeOptionalTaskWorkspaceScopeInput(input ?? null);
			let refsCwd = workspaceScope.workspacePath;
			if (taskScope) {
				refsCwd = await resolveTaskWorkingDirectory({ workspacePath: workspaceScope.workspacePath, ...taskScope });
			}
			return await getGitRefs(refsCwd);
		},
		loadCommitDiff: async (workspaceScope, input) => {
			const taskScope = normalizeOptionalTaskWorkspaceScopeInput(input.taskScope ?? null);
			let diffCwd = workspaceScope.workspacePath;
			if (taskScope) {
				diffCwd = await resolveTaskWorkingDirectory({ workspacePath: workspaceScope.workspacePath, ...taskScope });
			}
			return await getCommitDiff({
				cwd: diffCwd,
				commitHash: input.commitHash,
			});
		},
		notifyTaskTitleUpdated: (workspaceScope, taskId, title) => {
			deps.broadcastTaskTitleUpdated(workspaceScope.workspaceId, taskId, title);
		},
		setTaskDisplaySummary: async (workspaceScope, taskId, text, generatedAt) => {
			const manager = await deps.ensureTerminalManagerForWorkspace(
				workspaceScope.workspaceId,
				workspaceScope.workspacePath,
			);
			manager.store.setDisplaySummary(taskId, text, generatedAt);
			void deps.broadcastRuntimeWorkspaceStateUpdated(workspaceScope.workspaceId, workspaceScope.workspacePath);
		},
		setFocusedTask: (workspaceScope, taskId) => {
			deps.setFocusedTask(workspaceScope.workspaceId, taskId);
		},
	};
}
