import { TRPCError } from "@trpc/server";
import { parseWorktreeDeleteRequest, parseWorktreeEnsureRequest } from "../core/api-validation";
import { saveWorkspaceState, WorkspaceStateConflictError } from "../state/workspace-state";
import { generateTaskTitle } from "../title/title-generator";
import { deleteTaskWorktree, ensureTaskWorktreeIfDoesntExist, getTaskWorkspaceInfo } from "../workspace/task-worktree";
import type { RuntimeTrpcContext } from "./app-router-context";
import { normalizeRequiredTaskWorkspaceScopeInput, type WorkspaceApiContext } from "./workspace-api-shared";

const MAX_CONCURRENT_TITLE_REQUESTS = 3;

type StateOps = Pick<
	RuntimeTrpcContext["workspaceApi"],
	| "ensureWorktree"
	| "deleteWorktree"
	| "loadTaskContext"
	| "loadState"
	| "notifyStateUpdated"
	| "saveState"
	| "notifyTaskTitleUpdated"
	| "setTaskDisplaySummary"
	| "setFocusedTask"
>;

export function createStateOps(ctx: WorkspaceApiContext): StateOps {
	return {
		// Called by the UI's ensureTaskWorkspace (use-task-sessions.ts) for restore-from-trash.
		// The other path to ensureTaskWorktreeIfDoesntExist is startTaskSession in runtime-api.ts,
		// which reads branch from persisted board state server-side instead.
		ensureWorktree: async (workspaceScope, input) => {
			const body = parseWorktreeEnsureRequest(input);
			return await ensureTaskWorktreeIfDoesntExist({
				cwd: workspaceScope.workspacePath,
				taskId: body.taskId,
				baseRef: body.baseRef,
				branch: body.branch ?? undefined,
			});
		},

		deleteWorktree: async (workspaceScope, input) => {
			const body = parseWorktreeDeleteRequest(input);
			const result = await deleteTaskWorktree({
				repoPath: workspaceScope.workspacePath,
				taskId: body.taskId,
			});
			// workingDirectory is cleared by the client when it moves the card
			// to trash (moveTaskToColumn sets workingDirectory = null for trash).
			// The client persists through its normal board state cycle, avoiding
			// a dual-writer race where the server bumps the revision while the
			// client's persist debounce is in flight.
			return result;
		},

		loadTaskContext: async (workspaceScope, input) => {
			const normalizedInput = normalizeRequiredTaskWorkspaceScopeInput(input);
			return await getTaskWorkspaceInfo({
				cwd: workspaceScope.workspacePath,
				taskId: normalizedInput.taskId,
				baseRef: normalizedInput.baseRef,
			});
		},

		loadState: async (workspaceScope) => {
			return await ctx.deps.data.buildWorkspaceStateSnapshot(
				workspaceScope.workspaceId,
				workspaceScope.workspacePath,
			);
		},

		notifyStateUpdated: async (workspaceScope) => {
			ctx.broadcastStateUpdate(workspaceScope);
			void ctx.deps.broadcaster.broadcastRuntimeProjectsUpdated(workspaceScope.workspaceId);
			return { ok: true };
		},

		saveState: async (workspaceScope, input) => {
			try {
				const terminalManager = await ctx.deps.terminals.ensureTerminalManagerForWorkspace(
					workspaceScope.workspaceId,
					workspaceScope.workspacePath,
				);
				for (const summary of terminalManager.store.listSummaries()) {
					input.sessions[summary.taskId] = summary;
				}
				const response = await saveWorkspaceState(workspaceScope.workspacePath, input);
				ctx.broadcastStateUpdate(workspaceScope);
				void ctx.deps.broadcaster.broadcastRuntimeProjectsUpdated(workspaceScope.workspaceId);

				// Fire-and-forget: generate titles for any new cards that have title === null.
				// Cap concurrency to avoid flooding the LLM proxy when many cards are created at once.
				const untitledCards = input.board.columns.flatMap((col) => col.cards.filter((card) => card.title === null));
				const generateTitle = async (card: (typeof untitledCards)[number]) => {
					const title = await generateTaskTitle(card.prompt);
					if (!title) return;
					// Send the title to the UI via a lightweight message. The client
					// applies it to its board state and persists through its normal
					// single-writer cycle.
					ctx.deps.broadcaster.broadcastTaskTitleUpdated(workspaceScope.workspaceId, card.id, title, {
						autoGenerated: true,
					});
				};
				if (untitledCards.length > 0) {
					void (async () => {
						for (let i = 0; i < untitledCards.length; i += MAX_CONCURRENT_TITLE_REQUESTS) {
							const batch = untitledCards.slice(i, i + MAX_CONCURRENT_TITLE_REQUESTS);
							await Promise.allSettled(batch.map(generateTitle));
						}
					})();
				}

				return response;
			} catch (error) {
				if (error instanceof WorkspaceStateConflictError) {
					throw new TRPCError({
						code: "CONFLICT",
						message: error.message,
						cause: { currentRevision: error.currentRevision },
					});
				}
				throw error;
			}
		},

		notifyTaskTitleUpdated: (workspaceScope, taskId, title) => {
			ctx.deps.broadcaster.broadcastTaskTitleUpdated(workspaceScope.workspaceId, taskId, title);
		},

		setTaskDisplaySummary: async (workspaceScope, taskId, text, generatedAt) => {
			const manager = await ctx.deps.terminals.ensureTerminalManagerForWorkspace(
				workspaceScope.workspaceId,
				workspaceScope.workspacePath,
			);
			manager.store.setDisplaySummary(taskId, text, generatedAt);
			ctx.broadcastStateUpdate(workspaceScope);
		},

		setFocusedTask: (workspaceScope, taskId) => {
			ctx.deps.broadcaster.setFocusedTask(workspaceScope.workspaceId, taskId);
		},
	};
}
