import { z } from "zod";
import { promptShortcutSchema, runtimeAgentIdSchema, runtimeProjectShortcutSchema } from "./shared.js";

export const runtimeAgentDefinitionSchema = z.object({
	id: runtimeAgentIdSchema,
	label: z.string(),
	binary: z.string(),
	command: z.string(),
	defaultArgs: z.array(z.string()),
	installed: z.boolean(),
	configured: z.boolean(),
});
export type RuntimeAgentDefinition = z.infer<typeof runtimeAgentDefinitionSchema>;

export const runtimeConfigResponseSchema = z.object({
	selectedAgentId: runtimeAgentIdSchema,
	selectedShortcutLabel: z.string().nullable(),
	agentAutonomousModeEnabled: z.boolean(),
	debugModeEnabled: z.boolean().optional(),
	effectiveCommand: z.string().nullable(),
	globalConfigPath: z.string(),
	projectConfigPath: z.string().nullable(),
	readyForReviewNotificationsEnabled: z.boolean(),
	shellAutoRestartEnabled: z.boolean(),
	showTrashWorktreeNotice: z.boolean(),
	uncommittedChangesOnCardsEnabled: z.boolean(),
	unmergedChangesIndicatorEnabled: z.boolean(),
	behindBaseIndicatorEnabled: z.boolean(),
	skipTaskCheckoutConfirmation: z.boolean(),
	skipHomeCheckoutConfirmation: z.boolean(),
	skipCherryPickConfirmation: z.boolean(),
	audibleNotificationsEnabled: z.boolean(),
	audibleNotificationVolume: z.number().min(0).max(1),
	audibleNotificationEvents: z.object({
		permission: z.boolean(),
		review: z.boolean(),
		failure: z.boolean(),
		completion: z.boolean(),
	}),
	audibleNotificationsOnlyWhenHidden: z.boolean(),
	commitPromptTemplate: z.string(),
	openPrPromptTemplate: z.string(),
	commitPromptTemplateDefault: z.string(),
	openPrPromptTemplateDefault: z.string(),
	detectedCommands: z.array(z.string()),
	agents: z.array(runtimeAgentDefinitionSchema),
	shortcuts: z.array(runtimeProjectShortcutSchema),
	pinnedBranches: z.array(z.string()),
	promptShortcuts: z.array(promptShortcutSchema),
	hiddenDefaultPromptShortcuts: z.array(z.string()),
	showSummaryOnCards: z.boolean(),
	autoGenerateSummary: z.boolean(),
	summaryStaleAfterSeconds: z.number(),
	focusedTaskPollMs: z.number(),
	backgroundTaskPollMs: z.number(),
	homeRepoPollMs: z.number(),
	statuslineEnabled: z.boolean(),
	terminalFontWeight: z.number(),
	terminalWebGLRenderer: z.boolean(),
	worktreeAddParentRepoDir: z.boolean(),
	worktreeAddParentGitDir: z.boolean(),
	worktreeAddQuarterdeckDir: z.boolean(),
	showRunningTaskEmergencyActions: z.boolean(),
	eventLogEnabled: z.boolean(),
	llmConfigured: z.boolean(),
});
export type RuntimeConfigResponse = z.infer<typeof runtimeConfigResponseSchema>;

export const runtimeConfigSaveRequestSchema = z.object({
	selectedAgentId: runtimeAgentIdSchema.optional(),
	selectedShortcutLabel: z.string().nullable().optional(),
	agentAutonomousModeEnabled: z.boolean().optional(),
	shortcuts: z.array(runtimeProjectShortcutSchema).optional(),
	pinnedBranches: z.array(z.string()).optional(),
	promptShortcuts: z.array(promptShortcutSchema).optional(),
	hiddenDefaultPromptShortcuts: z.array(z.string()).optional(),
	readyForReviewNotificationsEnabled: z.boolean().optional(),
	shellAutoRestartEnabled: z.boolean().optional(),
	showSummaryOnCards: z.boolean().optional(),
	autoGenerateSummary: z.boolean().optional(),
	summaryStaleAfterSeconds: z.number().min(5).optional(),
	showTrashWorktreeNotice: z.boolean().optional(),
	uncommittedChangesOnCardsEnabled: z.boolean().optional(),
	unmergedChangesIndicatorEnabled: z.boolean().optional(),
	behindBaseIndicatorEnabled: z.boolean().optional(),
	skipTaskCheckoutConfirmation: z.boolean().optional(),
	skipHomeCheckoutConfirmation: z.boolean().optional(),
	skipCherryPickConfirmation: z.boolean().optional(),
	commitPromptTemplate: z.string().optional(),
	openPrPromptTemplate: z.string().optional(),
	audibleNotificationsEnabled: z.boolean().optional(),
	audibleNotificationVolume: z.number().min(0).max(1).optional(),
	audibleNotificationEvents: z
		.object({
			permission: z.boolean(),
			review: z.boolean(),
			failure: z.boolean(),
			completion: z.boolean(),
		})
		.optional(),
	audibleNotificationsOnlyWhenHidden: z.boolean().optional(),
	focusedTaskPollMs: z.number().min(500).max(60000).optional(),
	backgroundTaskPollMs: z.number().min(500).max(60000).optional(),
	homeRepoPollMs: z.number().min(500).max(60000).optional(),
	statuslineEnabled: z.boolean().optional(),
	terminalFontWeight: z.number().min(100).max(900).optional(),
	terminalWebGLRenderer: z.boolean().optional(),
	worktreeAddParentRepoDir: z.boolean().optional(),
	worktreeAddParentGitDir: z.boolean().optional(),
	worktreeAddQuarterdeckDir: z.boolean().optional(),
	showRunningTaskEmergencyActions: z.boolean().optional(),
	eventLogEnabled: z.boolean().optional(),
});
export type RuntimeConfigSaveRequest = z.infer<typeof runtimeConfigSaveRequestSchema>;
