import { z } from "zod";
import { diagnosticRecordEnvelopeSchema, diagnosticRecordingStateSchema } from "./diagnostics.js";
import {
	runtimeProjectMetadataSchema,
	runtimeProjectStateResponseSchema,
	runtimeProjectSummarySchema,
} from "./project-state.js";
import { runtimeTaskSessionSummarySchema } from "./task-session.js";

export const runtimeStateStreamSnapshotMessageSchema = z.object({
	type: z.literal("snapshot"),
	// Exact packaged artifact identity. Optional only for rolling compatibility
	// with runtimes built before browser/runtime build fencing existed.
	runtimeBuildId: z.string().min(1).optional(),
	currentProjectId: z.string().nullable(),
	projects: z.array(runtimeProjectSummarySchema),
	projectState: runtimeProjectStateResponseSchema.nullable(),
	projectMetadata: runtimeProjectMetadataSchema.nullable(),
	// Connection-time baseline for all managed projects; live updates continue
	// to arrive through task_notification messages.
	notificationSummariesByProject: z.record(z.string(), z.array(runtimeTaskSessionSummarySchema)).optional(),
	// Per-project ordering fence for the notification baseline. This prevents a
	// connection snapshot from replacing a newer live delta that reached the
	// browser while the snapshot was being assembled.
	notificationRevisionsByProject: z.record(z.string(), z.number().int().nonnegative()).optional(),
});
export type RuntimeStateStreamSnapshotMessage = z.infer<typeof runtimeStateStreamSnapshotMessageSchema>;

export const runtimeStateStreamProjectStateMessageSchema = z.object({
	type: z.literal("project_state_updated"),
	projectId: z.string(),
	projectState: runtimeProjectStateResponseSchema,
});
export type RuntimeStateStreamProjectStateMessage = z.infer<typeof runtimeStateStreamProjectStateMessageSchema>;

export const runtimeStateStreamTaskSessionsMessageSchema = z.object({
	type: z.literal("task_sessions_updated"),
	projectId: z.string(),
	summaries: z.array(runtimeTaskSessionSummarySchema),
});
export type RuntimeStateStreamTaskSessionsMessage = z.infer<typeof runtimeStateStreamTaskSessionsMessageSchema>;

export const runtimeStateStreamProjectsMessageSchema = z.object({
	type: z.literal("projects_updated"),
	currentProjectId: z.string().nullable(),
	projects: z.array(runtimeProjectSummarySchema),
});
export type RuntimeStateStreamProjectsMessage = z.infer<typeof runtimeStateStreamProjectsMessageSchema>;

export const runtimeStateStreamProjectMetadataMessageSchema = z.object({
	type: z.literal("project_metadata_updated"),
	projectId: z.string(),
	projectMetadata: runtimeProjectMetadataSchema,
});
export type RuntimeStateStreamProjectMetadataMessage = z.infer<typeof runtimeStateStreamProjectMetadataMessageSchema>;

export const runtimeStateStreamTaskReadyForReviewMessageSchema = z.object({
	type: z.literal("task_ready_for_review"),
	projectId: z.string(),
	taskId: z.string(),
	triggeredAt: z.number(),
});
export type RuntimeStateStreamTaskReadyForReviewMessage = z.infer<
	typeof runtimeStateStreamTaskReadyForReviewMessageSchema
>;

export const runtimeStateStreamTaskTitleUpdatedMessageSchema = z.object({
	type: z.literal("task_title_updated"),
	projectId: z.string(),
	taskId: z.string(),
	title: z.string(),
	autoGenerated: z.boolean().optional(),
});
export type RuntimeStateStreamTaskTitleUpdatedMessage = z.infer<typeof runtimeStateStreamTaskTitleUpdatedMessageSchema>;

export const runtimeStateStreamTaskBaseRefUpdatedMessageSchema = z.object({
	type: z.literal("task_base_ref_updated"),
	projectId: z.string(),
	taskId: z.string(),
	baseRef: z.string(),
});
export type RuntimeStateStreamTaskBaseRefUpdatedMessage = z.infer<
	typeof runtimeStateStreamTaskBaseRefUpdatedMessageSchema
>;

export const runtimeStateStreamTaskNotificationMessageSchema = z.object({
	type: z.literal("task_notification"),
	// Included for consistency with other message schemas and to support future
	// per-project notification settings (currently out of scope).
	projectId: z.string(),
	notificationRevision: z.number().int().nonnegative(),
	summaries: z.array(runtimeTaskSessionSummarySchema),
	removedTaskIds: z.array(z.string()).optional(),
	replace: z.boolean().optional(),
});
export type RuntimeStateStreamTaskNotificationMessage = z.infer<typeof runtimeStateStreamTaskNotificationMessageSchema>;

export const runtimeStateStreamErrorMessageSchema = z.object({
	type: z.literal("error"),
	message: z.string(),
});
export type RuntimeStateStreamErrorMessage = z.infer<typeof runtimeStateStreamErrorMessageSchema>;

export const runtimeConsoleLogLevelSchema = z.enum(["debug", "info", "warn", "error"]);
export type RuntimeConsoleLogLevel = z.infer<typeof runtimeConsoleLogLevelSchema>;

export const runtimeStateStreamDiagnosticsStateMessageSchema = z.object({
	type: z.literal("diagnostics_state"),
	runtimeInstanceId: z.string(),
	browserCapability: z.string(),
	consoleLogLevel: runtimeConsoleLogLevelSchema,
	recording: diagnosticRecordingStateSchema,
	recentRecords: z.array(diagnosticRecordEnvelopeSchema),
});
export type RuntimeStateStreamDiagnosticsStateMessage = z.infer<typeof runtimeStateStreamDiagnosticsStateMessageSchema>;

export const runtimeStateStreamDiagnosticRecordBatchMessageSchema = z.object({
	type: z.literal("diagnostic_record_batch"),
	records: z.array(diagnosticRecordEnvelopeSchema),
});
export type RuntimeStateStreamDiagnosticRecordBatchMessage = z.infer<
	typeof runtimeStateStreamDiagnosticRecordBatchMessageSchema
>;

export const runtimeStateStreamDiagnosticCaptureStateMessageSchema = z.object({
	type: z.literal("diagnostic_capture_state"),
	consoleLogLevel: runtimeConsoleLogLevelSchema,
	recording: diagnosticRecordingStateSchema,
});
export type RuntimeStateStreamDiagnosticCaptureStateMessage = z.infer<
	typeof runtimeStateStreamDiagnosticCaptureStateMessageSchema
>;

export const runtimeStateStreamDiagnosticSnapshotRequestMessageSchema = z.object({
	type: z.literal("diagnostic_snapshot_request"),
	nonce: z.string(),
	deadline: z.number().int().nonnegative(),
});
export type RuntimeStateStreamDiagnosticSnapshotRequestMessage = z.infer<
	typeof runtimeStateStreamDiagnosticSnapshotRequestMessageSchema
>;

export const runtimeStateStreamMessageSchema = z.discriminatedUnion("type", [
	runtimeStateStreamSnapshotMessageSchema,
	runtimeStateStreamProjectStateMessageSchema,
	runtimeStateStreamTaskSessionsMessageSchema,
	runtimeStateStreamProjectsMessageSchema,
	runtimeStateStreamProjectMetadataMessageSchema,
	runtimeStateStreamTaskReadyForReviewMessageSchema,
	runtimeStateStreamTaskTitleUpdatedMessageSchema,
	runtimeStateStreamTaskBaseRefUpdatedMessageSchema,
	runtimeStateStreamTaskNotificationMessageSchema,
	runtimeStateStreamErrorMessageSchema,
	runtimeStateStreamDiagnosticsStateMessageSchema,
	runtimeStateStreamDiagnosticRecordBatchMessageSchema,
	runtimeStateStreamDiagnosticCaptureStateMessageSchema,
	runtimeStateStreamDiagnosticSnapshotRequestMessageSchema,
]);
export type RuntimeStateStreamMessage = z.infer<typeof runtimeStateStreamMessageSchema>;

export const runtimeTerminalWsResizeMessageSchema = z.object({
	type: z.literal("resize"),
	cols: z.number().int().positive(),
	rows: z.number().int().positive(),
	pixelWidth: z.number().int().positive().optional(),
	pixelHeight: z.number().int().positive().optional(),
	/** When true, the server sends SIGWINCH even if dimensions haven't changed.
	 *  Used on task switch to force TUI agents to redraw. */
	force: z.boolean().optional(),
});
export type RuntimeTerminalWsResizeMessage = z.infer<typeof runtimeTerminalWsResizeMessageSchema>;

export const runtimeTerminalWsStopMessageSchema = z.object({
	type: z.literal("stop"),
});
export type RuntimeTerminalWsStopMessage = z.infer<typeof runtimeTerminalWsStopMessageSchema>;

export const runtimeTerminalWsOutputAckMessageSchema = z.object({
	type: z.literal("output_ack"),
	bytes: z.number().int().nonnegative(),
});
export type RuntimeTerminalWsOutputAckMessage = z.infer<typeof runtimeTerminalWsOutputAckMessageSchema>;

export const runtimeTerminalWsRestoreCompleteMessageSchema = z.object({
	type: z.literal("restore_complete"),
});
export type RuntimeTerminalWsRestoreCompleteMessage = z.infer<typeof runtimeTerminalWsRestoreCompleteMessageSchema>;

export const runtimeTerminalWsRequestRestoreMessageSchema = z.object({
	type: z.literal("request_restore"),
});
export type RuntimeTerminalWsRequestRestoreMessage = z.infer<typeof runtimeTerminalWsRequestRestoreMessageSchema>;

export const runtimeTerminalWsClientMessageSchema = z.discriminatedUnion("type", [
	runtimeTerminalWsResizeMessageSchema,
	runtimeTerminalWsStopMessageSchema,
	runtimeTerminalWsOutputAckMessageSchema,
	runtimeTerminalWsRestoreCompleteMessageSchema,
	runtimeTerminalWsRequestRestoreMessageSchema,
]);
export type RuntimeTerminalWsClientMessage = z.infer<typeof runtimeTerminalWsClientMessageSchema>;

export const runtimeTerminalWsStateMessageSchema = z.object({
	type: z.literal("state"),
	summary: runtimeTaskSessionSummarySchema,
});
export type RuntimeTerminalWsStateMessage = z.infer<typeof runtimeTerminalWsStateMessageSchema>;

export const runtimeTerminalWsErrorMessageSchema = z.object({
	type: z.literal("error"),
	message: z.string(),
});
export type RuntimeTerminalWsErrorMessage = z.infer<typeof runtimeTerminalWsErrorMessageSchema>;

export const runtimeTerminalWsExitMessageSchema = z.object({
	type: z.literal("exit"),
	code: z.number().nullable(),
});
export type RuntimeTerminalWsExitMessage = z.infer<typeof runtimeTerminalWsExitMessageSchema>;

export const runtimeTerminalWsRestoreMessageSchema = z.object({
	type: z.literal("restore"),
	snapshot: z.string(),
	cols: z.number().int().positive().nullable().optional(),
	rows: z.number().int().positive().nullable().optional(),
});
export type RuntimeTerminalWsRestoreMessage = z.infer<typeof runtimeTerminalWsRestoreMessageSchema>;

export const runtimeTerminalWsServerMessageSchema = z.discriminatedUnion("type", [
	runtimeTerminalWsStateMessageSchema,
	runtimeTerminalWsErrorMessageSchema,
	runtimeTerminalWsExitMessageSchema,
	runtimeTerminalWsRestoreMessageSchema,
]);
export type RuntimeTerminalWsServerMessage = z.infer<typeof runtimeTerminalWsServerMessageSchema>;
