/**
 * Shared service interfaces for dependency injection.
 *
 * Each interface defines a focused capability that multiple consumers depend on.
 * Implementing classes (RuntimeStateHub, WorkspaceRegistry) add `implements`
 * clauses; consumers accept the interface in their constructor instead of
 * re-declaring the same function signatures in bespoke dependency bags.
 *
 * These are the C#-style service contracts — ctrl+click an interface to see
 * every consumer, ctrl+click the `implements` clause to see the provider.
 */

import type { RuntimeConfigState } from "../config/runtime-config";
import type { WorkspaceMetadataPollIntervals } from "../server/workspace-metadata-monitor";
import type { TerminalSessionManager } from "../terminal/session-manager";
import type { RuntimeProjectSummary, RuntimeProjectTaskCounts, RuntimeWorkspaceStateResponse } from "./api-contract";
import type { LogLevel } from "./runtime-logger";

// ── Broadcasting ─────────────────────────────────────────────────────────────

/**
 * Broadcasts real-time state changes to connected browser clients.
 * Implemented by RuntimeStateHub.
 */
export interface IRuntimeBroadcaster {
	broadcastRuntimeWorkspaceStateUpdated: (workspaceId: string, workspacePath: string) => Promise<void>;
	broadcastRuntimeProjectsUpdated: (preferredCurrentProjectId: string | null) => Promise<void>;
	broadcastTaskReadyForReview: (workspaceId: string, taskId: string) => void;
	broadcastTaskTitleUpdated: (
		workspaceId: string,
		taskId: string,
		title: string,
		options?: { autoGenerated?: boolean },
	) => void;
	broadcastTaskWorkingDirectoryUpdated: (
		workspaceId: string,
		taskId: string,
		workingDirectory: string,
		useWorktree: boolean,
	) => void;
	broadcastLogLevel: (level: LogLevel) => void;
	setFocusedTask: (workspaceId: string, taskId: string | null) => void;
	requestTaskRefresh: (workspaceId: string, taskId: string) => void;
	requestHomeRefresh: (workspaceId: string) => void;
	setPollIntervals: (workspaceId: string, intervals: WorkspaceMetadataPollIntervals) => void;
}

// ── Terminal Manager Access ──────────────────────────────────────────────────

/**
 * Provides access to terminal session managers per workspace.
 * Implemented by WorkspaceRegistry.
 */
export interface ITerminalManagerProvider {
	getTerminalManagerForWorkspace: (workspaceId: string) => TerminalSessionManager | null;
	ensureTerminalManagerForWorkspace: (workspaceId: string, repoPath: string) => Promise<TerminalSessionManager>;
}

// ── Workspace Resolution ─────────────────────────────────────────────────────

/**
 * Resolves workspace identity and paths from workspace IDs.
 * Implemented by WorkspaceRegistry.
 */
export interface IWorkspaceResolver {
	getActiveWorkspaceId: () => string | null;
	getActiveWorkspacePath: () => string | null;
	getWorkspacePathById: (workspaceId: string) => string | null;
	rememberWorkspace: (workspaceId: string, repoPath: string) => void;
	setActiveWorkspace: (workspaceId: string, repoPath: string) => Promise<void>;
	clearActiveWorkspace: () => void;
}

// ── Runtime Config ───────────────────────────────────────────────────────────

/**
 * Loads and updates runtime configuration at global or workspace scope.
 * Implemented by WorkspaceRegistry.
 */
export interface IRuntimeConfigProvider {
	getActiveRuntimeConfig: () => RuntimeConfigState;
	setActiveRuntimeConfig: (config: RuntimeConfigState) => void;
	loadScopedRuntimeConfig: (scope: { workspaceId: string; workspacePath: string }) => Promise<RuntimeConfigState>;
}

// ── Workspace Data ───────────────────────────────────────────────────────────

/**
 * Builds workspace and project snapshots for streaming to clients.
 * Implemented by WorkspaceRegistry.
 */
export interface IWorkspaceDataProvider {
	buildWorkspaceStateSnapshot: (workspaceId: string, workspacePath: string) => Promise<RuntimeWorkspaceStateResponse>;
	buildProjectsPayload: (preferredCurrentProjectId: string | null) => Promise<{
		currentProjectId: string | null;
		projects: RuntimeProjectSummary[];
	}>;
	summarizeProjectTaskCounts: (workspaceId: string, repoPath: string) => Promise<RuntimeProjectTaskCounts>;
	createProjectSummary: (input: {
		workspaceId: string;
		repoPath: string;
		taskCounts: RuntimeProjectTaskCounts;
	}) => RuntimeProjectSummary;
}
