/**
 * Shared service interfaces for dependency injection.
 *
 * Each interface defines a focused capability that multiple consumers depend on.
 * Implementing classes (RuntimeStateHub, ProjectRegistry) add `implements`
 * clauses; consumers accept the interface in their constructor instead of
 * re-declaring the same function signatures in bespoke dependency bags.
 *
 * These are the C#-style service contracts — ctrl+click an interface to see
 * every consumer, ctrl+click the `implements` clause to see the provider.
 */

import type { RuntimeConfigState } from "../config";
import type { TerminalSessionManager } from "../terminal";
import type { RuntimeProjectStateResponse, RuntimeProjectSummary, RuntimeProjectTaskCounts } from "./api-contract";
import type { LogLevel } from "./runtime-logger";

// ── Broadcasting ─────────────────────────────────────────────────────────────

/**
 * Broadcasts real-time state changes to connected browser clients.
 * Implemented by RuntimeStateHub.
 */
export interface IRuntimeBroadcaster {
	broadcastRuntimeProjectStateUpdated: (projectId: string, projectPath: string) => Promise<void>;
	broadcastRuntimeProjectNotificationsUpdated: (projectId: string) => Promise<void>;
	broadcastRuntimeProjectsUpdated: (preferredCurrentProjectId: string | null) => Promise<void>;
	broadcastTaskReadyForReview: (projectId: string, taskId: string) => void;
	broadcastTaskTitleUpdated: (
		projectId: string,
		taskId: string,
		title: string,
		options?: { autoGenerated?: boolean },
	) => void;
	broadcastTaskBaseRefUpdated: (projectId: string, taskId: string, baseRef: string) => void;
	broadcastLogLevel: (level: LogLevel) => void;
	setFocusedTask: (projectId: string, taskId: string | null) => void;
	setDocumentVisible: (projectId: string, clientId: string, isDocumentVisible: boolean) => void;
	requestTaskRefresh: (projectId: string, taskId: string) => void;
	requestHomeRefresh: (projectId: string) => void;
}

// ── Terminal Manager Access ──────────────────────────────────────────────────

/**
 * Provides access to terminal session managers per project.
 * Implemented by ProjectRegistry.
 */
export interface ITerminalManagerProvider {
	getTerminalManagerForProject: (projectId: string) => TerminalSessionManager | null;
	ensureTerminalManagerForProject: (projectId: string, repoPath: string) => Promise<TerminalSessionManager>;
}

// ── Project Resolution ─────────────────────────────────────────────────────

/**
 * Resolves project identity and paths from project IDs.
 * Implemented by ProjectRegistry.
 */
export interface IProjectResolver {
	getActiveProjectId: () => string | null;
	getActiveProjectPath: () => string | null;
	getProjectPathById: (projectId: string) => string | null;
	rememberProject: (projectId: string, repoPath: string) => void;
	setActiveProject: (projectId: string, repoPath: string) => Promise<void>;
	clearActiveProject: () => void;
}

// ── Runtime Config ───────────────────────────────────────────────────────────

/**
 * Loads and updates runtime configuration at global or project scope.
 * Implemented by ProjectRegistry.
 */
export interface IRuntimeConfigProvider {
	getActiveRuntimeConfig: () => RuntimeConfigState;
	setActiveRuntimeConfig: (config: RuntimeConfigState) => void;
	loadScopedRuntimeConfig: (scope: { projectId: string; projectPath: string }) => Promise<RuntimeConfigState>;
}

// ── Project Data ───────────────────────────────────────────────────────────

/**
 * Builds project and metadata snapshots for streaming to clients.
 * Implemented by ProjectRegistry.
 */
export interface IProjectDataProvider {
	buildProjectStateSnapshot: (projectId: string, projectPath: string) => Promise<RuntimeProjectStateResponse>;
	buildProjectsPayload: (preferredCurrentProjectId: string | null) => Promise<{
		currentProjectId: string | null;
		projects: RuntimeProjectSummary[];
	}>;
	summarizeProjectTaskCounts: (projectId: string, repoPath: string) => Promise<RuntimeProjectTaskCounts>;
	createProjectSummary: (input: {
		projectId: string;
		repoPath: string;
		taskCounts: RuntimeProjectTaskCounts;
	}) => RuntimeProjectSummary;
}
