import {
	applyRuntimeProjectNotificationDelta,
	pruneRuntimeProjectNotificationStateMap,
	type RuntimeProjectNotificationStateMap,
	replaceRuntimeProjectNotificationStateMap,
	replaceRuntimeProjectNotificationStateMapFromProjectState,
	replaceRuntimeProjectNotificationStateMapFromProjectSummaries,
} from "@/runtime/runtime-notification-projects";
import type {
	RuntimeDebugLogEntry,
	RuntimeProjectMetadata,
	RuntimeProjectStateResponse,
	RuntimeProjectSummary,
	RuntimeStateStreamProjectsMessage,
	RuntimeStateStreamSnapshotMessage,
	RuntimeStateStreamTaskReadyForReviewMessage,
	RuntimeTaskSessionSummary,
} from "@/runtime/types";
import { mergeTaskSessionSummaryMap, reconcileAuthoritativeTaskSessionSummaryMap } from "@/utils/session-summary-utils";

const DEBUG_LOG_ENTRIES_MAX = 500;

export interface TaskTitleUpdate {
	taskId: string;
	title: string;
	autoGenerated?: boolean;
}

export interface TaskBaseRefUpdate {
	taskId: string;
	baseRef: string;
}

export interface RuntimeNotificationMemory {
	projects: RuntimeProjectNotificationStateMap;
}

export interface RuntimeStateStreamStore {
	currentProjectId: string | null;
	projects: RuntimeProjectSummary[];
	projectState: RuntimeProjectStateResponse | null;
	projectMetadata: RuntimeProjectMetadata | null;
	notificationMemory: RuntimeNotificationMemory;
	latestTaskReadyForReview: RuntimeStateStreamTaskReadyForReviewMessage | null;
	latestTaskTitleUpdate: TaskTitleUpdate | null;
	latestTaskBaseRefUpdate: TaskBaseRefUpdate | null;
	logLevel: "debug" | "info" | "warn" | "error";
	debugLogEntries: RuntimeDebugLogEntry[];
	streamError: string | null;
	isRuntimeDisconnected: boolean;
	hasReceivedSnapshot: boolean;
}

export type RuntimeStateStreamAction =
	| {
			type: "requested_project_changed";
			preloadedProjectState: RuntimeProjectStateResponse | null;
			requestedProjectId: string | null;
	  }
	| { type: "stream_connected" }
	| { type: "snapshot"; payload: RuntimeStateStreamSnapshotMessage }
	| {
			type: "projects_updated";
			payload: RuntimeStateStreamProjectsMessage;
			nextProjectId: string | null;
	  }
	| { type: "project_metadata_updated"; projectMetadata: RuntimeProjectMetadata }
	| { type: "task_ready_for_review"; payload: RuntimeStateStreamTaskReadyForReviewMessage }
	| { type: "task_title_updated"; taskId: string; title: string; autoGenerated?: boolean }
	| { type: "task_base_ref_updated"; taskId: string; baseRef: string }
	| { type: "project_state_updated"; projectState: RuntimeProjectStateResponse }
	| { type: "task_sessions_updated"; summaries: readonly RuntimeTaskSessionSummary[] }
	| {
			type: "task_notification";
			projectId: string;
			summaries: readonly RuntimeTaskSessionSummary[];
			removedTaskIds?: readonly string[];
			replace?: boolean;
	  }
	| {
			type: "debug_logging_state";
			level: "debug" | "info" | "warn" | "error";
			recentEntries?: readonly RuntimeDebugLogEntry[];
	  }
	| { type: "debug_log_batch"; entries: readonly RuntimeDebugLogEntry[] }
	| { type: "stream_error"; message: string }
	| { type: "stream_disconnected"; message: string };

function mergeTaskSessionSummaries(
	currentSessions: Record<string, RuntimeTaskSessionSummary>,
	summaries: readonly RuntimeTaskSessionSummary[],
): Record<string, RuntimeTaskSessionSummary> {
	if (summaries.length === 0) {
		return currentSessions;
	}

	return mergeTaskSessionSummaryMap(currentSessions, summaries);
}

function reconcileProjectStateSessions(
	currentProjectState: RuntimeProjectStateResponse | null,
	incomingProjectState: RuntimeProjectStateResponse,
): RuntimeProjectStateResponse {
	return {
		...incomingProjectState,
		sessions: reconcileAuthoritativeTaskSessionSummaryMap(
			currentProjectState?.sessions ?? {},
			incomingProjectState.sessions ?? {},
		),
	};
}

function mergeNotificationMemory(
	currentMemory: RuntimeNotificationMemory,
	projectId: string,
	summaries: readonly RuntimeTaskSessionSummary[],
	removedTaskIds: readonly string[] = [],
	replace = false,
): RuntimeNotificationMemory {
	if (replace) {
		return {
			projects: replaceRuntimeProjectNotificationStateMap(currentMemory.projects, projectId, summaries),
		};
	}

	if (summaries.length === 0 && removedTaskIds.length === 0) {
		return currentMemory;
	}

	return {
		projects: applyRuntimeProjectNotificationDelta(currentMemory.projects, projectId, summaries, removedTaskIds),
	};
}

function replaceNotificationMemoryFromProjectState(
	currentMemory: RuntimeNotificationMemory,
	projectId: string | null,
	projectState: RuntimeProjectStateResponse | null,
): RuntimeNotificationMemory {
	return {
		projects: replaceRuntimeProjectNotificationStateMapFromProjectState(
			currentMemory.projects,
			projectId,
			projectState,
		),
	};
}

function replaceNotificationMemoryFromProjectSummaries(
	currentMemory: RuntimeNotificationMemory,
	projects: readonly RuntimeProjectSummary[],
	summariesByProject: RuntimeStateStreamSnapshotMessage["notificationSummariesByProject"],
): RuntimeNotificationMemory {
	return {
		projects: replaceRuntimeProjectNotificationStateMapFromProjectSummaries(
			currentMemory.projects,
			projects,
			summariesByProject,
		),
	};
}

function pruneNotificationMemory(
	currentMemory: RuntimeNotificationMemory,
	projects: readonly RuntimeProjectSummary[],
): RuntimeNotificationMemory {
	return {
		projects: pruneRuntimeProjectNotificationStateMap(currentMemory.projects, projects),
	};
}

function mergeDebugLogEntries(
	currentEntries: RuntimeDebugLogEntry[],
	incomingEntries: readonly RuntimeDebugLogEntry[],
): RuntimeDebugLogEntry[] {
	if (incomingEntries.length === 0) {
		return currentEntries;
	}

	const existingIds = new Set(currentEntries.map((entry) => entry.id));
	const newEntries = incomingEntries.filter((entry) => !existingIds.has(entry.id));
	return [...currentEntries, ...newEntries].slice(-DEBUG_LOG_ENTRIES_MAX);
}

function applyRequestedProjectChange(
	state: RuntimeStateStreamStore,
	preloadedProjectState: RuntimeProjectStateResponse | null,
	requestedProjectId: string | null,
): RuntimeStateStreamStore {
	if (!preloadedProjectState) {
		return {
			...state,
			projectState: null,
			projectMetadata: null,
			streamError: null,
			isRuntimeDisconnected: false,
			hasReceivedSnapshot: false,
		};
	}

	return {
		...state,
		currentProjectId: requestedProjectId,
		projectState: preloadedProjectState,
		projectMetadata: null,
		notificationMemory: replaceNotificationMemoryFromProjectState(
			state.notificationMemory,
			requestedProjectId,
			preloadedProjectState,
		),
		streamError: null,
		isRuntimeDisconnected: false,
		hasReceivedSnapshot: true,
	};
}

function applySnapshot(
	state: RuntimeStateStreamStore,
	payload: RuntimeStateStreamSnapshotMessage,
): RuntimeStateStreamStore {
	const nextProjectState = payload.projectState
		? reconcileProjectStateSessions(state.projectState, payload.projectState)
		: null;

	return {
		...state,
		currentProjectId: payload.currentProjectId,
		projects: payload.projects,
		projectState: nextProjectState,
		projectMetadata: payload.projectMetadata,
		notificationMemory: replaceNotificationMemoryFromProjectState(
			replaceNotificationMemoryFromProjectSummaries(
				pruneNotificationMemory(state.notificationMemory, payload.projects),
				payload.projects,
				payload.notificationSummariesByProject,
			),
			payload.currentProjectId,
			nextProjectState,
		),
		streamError: null,
		isRuntimeDisconnected: false,
		hasReceivedSnapshot: true,
	};
}

export function createInitialRuntimeStateStreamStore(requestedProjectId: string | null): RuntimeStateStreamStore {
	return {
		currentProjectId: requestedProjectId,
		projects: [],
		projectState: null,
		projectMetadata: null,
		notificationMemory: {
			projects: {},
		},
		latestTaskReadyForReview: null,
		latestTaskTitleUpdate: null,
		latestTaskBaseRefUpdate: null,
		logLevel: "warn",
		debugLogEntries: [],
		streamError: null,
		isRuntimeDisconnected: false,
		hasReceivedSnapshot: false,
	};
}

export function runtimeStateStreamReducer(
	state: RuntimeStateStreamStore,
	action: RuntimeStateStreamAction,
): RuntimeStateStreamStore {
	if (action.type === "requested_project_changed") {
		return applyRequestedProjectChange(state, action.preloadedProjectState, action.requestedProjectId);
	}
	if (action.type === "stream_connected") {
		return {
			...state,
			streamError: null,
			isRuntimeDisconnected: false,
		};
	}
	if (action.type === "snapshot") {
		return applySnapshot(state, action.payload);
	}
	if (action.type === "projects_updated") {
		const didProjectChange = action.nextProjectId !== state.currentProjectId;
		return {
			...state,
			currentProjectId: action.nextProjectId,
			projects: action.payload.projects,
			notificationMemory: pruneNotificationMemory(state.notificationMemory, action.payload.projects),
			projectState: didProjectChange ? null : state.projectState,
			projectMetadata: didProjectChange ? null : state.projectMetadata,
			latestTaskReadyForReview: didProjectChange ? null : state.latestTaskReadyForReview,
			hasReceivedSnapshot: true,
		};
	}
	if (action.type === "project_metadata_updated") {
		return {
			...state,
			projectMetadata: action.projectMetadata,
		};
	}
	if (action.type === "task_ready_for_review") {
		return {
			...state,
			latestTaskReadyForReview: action.payload,
		};
	}
	if (action.type === "task_title_updated") {
		return {
			...state,
			latestTaskTitleUpdate: { taskId: action.taskId, title: action.title, autoGenerated: action.autoGenerated },
		};
	}
	if (action.type === "task_base_ref_updated") {
		return {
			...state,
			latestTaskBaseRefUpdate: { taskId: action.taskId, baseRef: action.baseRef },
		};
	}
	if (action.type === "project_state_updated") {
		const nextProjectState = reconcileProjectStateSessions(state.projectState, action.projectState);
		return {
			...state,
			projectState: nextProjectState,
			notificationMemory: replaceNotificationMemoryFromProjectState(
				state.notificationMemory,
				state.currentProjectId,
				nextProjectState,
			),
		};
	}
	if (action.type === "task_sessions_updated") {
		if (!state.projectState) {
			return state;
		}
		return {
			...state,
			projectState: {
				...state.projectState,
				sessions: mergeTaskSessionSummaries(state.projectState.sessions, action.summaries),
			},
		};
	}
	if (action.type === "task_notification") {
		// Live deltas update notification memory, while authoritative snapshots
		// and project-state updates replace project buckets to clear stale tasks.
		return {
			...state,
			notificationMemory: mergeNotificationMemory(
				state.notificationMemory,
				action.projectId,
				action.summaries,
				action.removedTaskIds ?? [],
				action.replace ?? false,
			),
		};
	}
	if (action.type === "debug_logging_state") {
		return {
			...state,
			logLevel: action.level,
			debugLogEntries: mergeDebugLogEntries(state.debugLogEntries, action.recentEntries ?? []),
		};
	}
	if (action.type === "debug_log_batch") {
		return {
			...state,
			debugLogEntries: [...state.debugLogEntries, ...action.entries].slice(-DEBUG_LOG_ENTRIES_MAX),
		};
	}
	if (action.type === "stream_error") {
		return {
			...state,
			streamError: action.message,
			isRuntimeDisconnected: false,
		};
	}
	if (action.type === "stream_disconnected") {
		return {
			...state,
			streamError: action.message,
			isRuntimeDisconnected: true,
		};
	}
	return state;
}
