import { mergeProjectStateByRevision } from "@/runtime/project-state-ordering";
import {
	applyRuntimeNotificationDelta,
	createRuntimeNotificationMemory,
	pruneRuntimeNotificationMemory,
	type RuntimeNotificationMemory,
	replaceRuntimeNotificationMemoryFromSnapshot,
	resetRuntimeNotificationOrdering,
	seedRuntimeNotificationMemoryFromProjectState,
} from "@/runtime/runtime-notification-memory";
import type {
	ProjectOrganization,
	RuntimeProjectMetadata,
	RuntimeProjectStateResponse,
	RuntimeProjectSummary,
	RuntimeStateStreamProjectsMessage,
	RuntimeStateStreamSnapshotMessage,
	RuntimeStateStreamTaskReadyForReviewMessage,
	RuntimeTaskSessionSummary,
} from "@/runtime/types";
import { countTasksByColumn } from "@/utils/app-utils";
import { mergeTaskSessionSummaryMap, reconcileAuthoritativeTaskSessionSummaryMap } from "@/utils/session-summary-utils";

export interface TaskTitleUpdate {
	projectId: string;
	taskId: string;
	title: string;
	autoGenerated?: boolean;
}

export interface TaskBaseRefUpdate {
	projectId: string;
	taskId: string;
	baseRef: string;
}

export interface RuntimeStateStreamStore {
	streamGeneration: number;
	currentProjectId: string | null;
	projects: RuntimeProjectSummary[];
	organization: ProjectOrganization | null;
	exactBoardRevisionsByProject: Record<string, number>;
	projectState: RuntimeProjectStateResponse | null;
	projectMetadata: RuntimeProjectMetadata | null;
	notificationMemory: RuntimeNotificationMemory;
	latestTaskReadyForReview: RuntimeStateStreamTaskReadyForReviewMessage | null;
	latestTaskTitleUpdate: TaskTitleUpdate | null;
	latestTaskBaseRefUpdate: TaskBaseRefUpdate | null;
	streamError: string | null;
	isRuntimeDisconnected: boolean;
	hasReceivedSnapshot: boolean;
}

export type RuntimeStateStreamDomainAction =
	| {
			type: "requested_project_changed";
			preloadedProjectState: RuntimeProjectStateResponse | null;
			requestedProjectId: string | null;
	  }
	| { type: "stream_connected" }
	| { type: "organization_updated"; organization: ProjectOrganization }
	| { type: "snapshot"; payload: RuntimeStateStreamSnapshotMessage }
	| {
			type: "projects_updated";
			payload: RuntimeStateStreamProjectsMessage;
			nextProjectId: string | null;
	  }
	| { type: "project_metadata_updated"; projectId: string; projectMetadata: RuntimeProjectMetadata }
	| { type: "task_ready_for_review"; payload: RuntimeStateStreamTaskReadyForReviewMessage }
	| { type: "task_title_updated"; projectId: string; taskId: string; title: string; autoGenerated?: boolean }
	| { type: "task_base_ref_updated"; projectId: string; taskId: string; baseRef: string }
	| { type: "project_state_updated"; projectId: string; projectState: RuntimeProjectStateResponse }
	| { type: "project_management_updated"; project: RuntimeProjectSummary; projectState?: RuntimeProjectStateResponse }
	| { type: "task_sessions_updated"; projectId: string; summaries: readonly RuntimeTaskSessionSummary[] }
	| {
			type: "task_notification";
			projectId: string;
			notificationRevision: number;
			summaries: readonly RuntimeTaskSessionSummary[];
			removedTaskIds?: readonly string[];
			replace?: boolean;
	  }
	| { type: "stream_error"; message: string }
	| { type: "stream_disconnected"; message: string };

export type RuntimeStateStreamAction =
	| RuntimeStateStreamDomainAction
	| {
			type: "stream_generation_changed";
			streamGeneration: number;
			preloadedProjectState: RuntimeProjectStateResponse | null;
			requestedProjectId: string | null;
	  }
	| {
			type: "stream_action";
			streamGeneration: number;
			action: RuntimeStateStreamDomainAction;
	  };

function mergeTaskSessionSummaries(
	currentSessions: Record<string, RuntimeTaskSessionSummary>,
	summaries: readonly RuntimeTaskSessionSummary[],
): Record<string, RuntimeTaskSessionSummary> {
	if (summaries.length === 0) {
		return currentSessions;
	}

	return mergeTaskSessionSummaryMap(currentSessions, summaries);
}

function reconcileProjectStateSessions(
	currentProjectState: RuntimeProjectStateResponse | null,
	incomingProjectState: RuntimeProjectStateResponse,
): RuntimeProjectStateResponse {
	const orderedState = mergeProjectStateByRevision(currentProjectState, incomingProjectState);
	return {
		...orderedState,
		sessions: reconcileAuthoritativeTaskSessionSummaryMap(
			currentProjectState?.sessions ?? {},
			orderedState.sessions ?? {},
		),
	};
}

export function mergeProjectSummariesByRevision(
	current: readonly RuntimeProjectSummary[],
	incoming: readonly RuntimeProjectSummary[],
	exactBoardRevisionsByProject: Readonly<Record<string, number>> = {},
): RuntimeProjectSummary[] {
	const currentById = new Map(current.map((project) => [project.id, project]));
	return incoming.map((project) => {
		const existing = currentById.get(project.id);
		if (!existing) {
			return project;
		}
		const metadata = (existing.metadataRevision ?? 0) > (project.metadataRevision ?? 0) ? existing : project;
		const retainBoard =
			existing.boardRevision > project.boardRevision ||
			(existing.boardRevision === project.boardRevision &&
				exactBoardRevisionsByProject[project.id] === project.boardRevision);
		return {
			...metadata,
			boardRevision: retainBoard ? existing.boardRevision : project.boardRevision,
			taskCounts: retainBoard ? existing.taskCounts : project.taskCounts,
		};
	});
}

function recordExactBoardRevision(
	current: Readonly<Record<string, number>>,
	projectId: string | null,
	projectState: RuntimeProjectStateResponse | null,
): Record<string, number> {
	if (!projectId || !projectState || current[projectId] === projectState.revision) {
		return { ...current };
	}
	return {
		...current,
		[projectId]: projectState.revision,
	};
}

function pruneExactBoardRevisions(
	current: Readonly<Record<string, number>>,
	projects: readonly RuntimeProjectSummary[],
): Record<string, number> {
	const projectIds = new Set(projects.map((project) => project.id));
	return Object.fromEntries(Object.entries(current).filter(([projectId]) => projectIds.has(projectId)));
}

function mergeProjectStateSummary(
	projects: readonly RuntimeProjectSummary[],
	projectId: string | null,
	projectState: RuntimeProjectStateResponse | null,
): RuntimeProjectSummary[] {
	if (!projectId || !projectState) {
		return [...projects];
	}
	return projects.map((project) => {
		if (project.id !== projectId) return project;
		const next = { ...project };
		if (project.boardRevision <= projectState.revision) {
			next.boardRevision = projectState.revision;
			next.taskCounts = countTasksByColumn(projectState.board);
		}
		if ((project.metadataRevision ?? 0) <= (projectState.metadataRevision ?? 0)) {
			if (next.path !== projectState.repoPath && !next.displayName) {
				next.name = projectState.repoPath.replaceAll("\\", "/").split("/").filter(Boolean).at(-1) ?? next.name;
			}
			next.path = projectState.repoPath;
			next.folderOnly = projectState.git.folderOnly;
			next.metadataRevision = projectState.metadataRevision;
			next.availability = projectState.availability;
		}
		return next;
	});
}

function applyKnownProjectLocation(
	projects: readonly RuntimeProjectSummary[],
	projectId: string | null,
	projectState: RuntimeProjectStateResponse | null,
): RuntimeProjectStateResponse | null {
	if (!projectState) return null;
	const project = projects.find((candidate) => candidate.id === projectId);
	if (!project || (project.metadataRevision ?? 0) <= (projectState.metadataRevision ?? 0)) return projectState;
	return {
		...projectState,
		repoPath: project.path,
		metadataRevision: project.metadataRevision,
		availability: project.availability,
	};
}

function isProjectMetadataCurrent(
	projects: readonly RuntimeProjectSummary[],
	projectId: string | null,
	projectState: RuntimeProjectStateResponse | null,
	metadata: RuntimeProjectMetadata,
): boolean {
	const project = projects.find((candidate) => candidate.id === projectId);
	return (
		projectState?.availability?.status !== "unavailable" &&
		project?.availability?.status !== "unavailable" &&
		(metadata.metadataRevision ?? 0) >= Math.max(project?.metadataRevision ?? 0, projectState?.metadataRevision ?? 0)
	);
}

function applyRequestedProjectChange(
	state: RuntimeStateStreamStore,
	preloadedProjectState: RuntimeProjectStateResponse | null,
	requestedProjectId: string | null,
): RuntimeStateStreamStore {
	preloadedProjectState = applyKnownProjectLocation(state.projects, requestedProjectId, preloadedProjectState);
	const didProjectChange = requestedProjectId !== state.currentProjectId;
	if (!preloadedProjectState) {
		return {
			...state,
			currentProjectId: requestedProjectId,
			projectState: null,
			projectMetadata: null,
			latestTaskReadyForReview: didProjectChange ? null : state.latestTaskReadyForReview,
			latestTaskTitleUpdate: didProjectChange ? null : state.latestTaskTitleUpdate,
			latestTaskBaseRefUpdate: didProjectChange ? null : state.latestTaskBaseRefUpdate,
			streamError: null,
			isRuntimeDisconnected: false,
			hasReceivedSnapshot: false,
		};
	}

	return {
		...state,
		currentProjectId: requestedProjectId,
		projects: mergeProjectStateSummary(state.projects, requestedProjectId, preloadedProjectState),
		exactBoardRevisionsByProject: recordExactBoardRevision(
			state.exactBoardRevisionsByProject,
			requestedProjectId,
			preloadedProjectState,
		),
		projectState: preloadedProjectState,
		projectMetadata: null,
		latestTaskReadyForReview: didProjectChange ? null : state.latestTaskReadyForReview,
		latestTaskTitleUpdate: didProjectChange ? null : state.latestTaskTitleUpdate,
		latestTaskBaseRefUpdate: didProjectChange ? null : state.latestTaskBaseRefUpdate,
		notificationMemory: seedRuntimeNotificationMemoryFromProjectState(
			state.notificationMemory,
			requestedProjectId,
			preloadedProjectState,
		),
		streamError: null,
		isRuntimeDisconnected: false,
		hasReceivedSnapshot: true,
	};
}

function applySnapshot(
	state: RuntimeStateStreamStore,
	payload: RuntimeStateStreamSnapshotMessage,
): RuntimeStateStreamStore {
	const staleOrganization = isOlderOrganization(state.organization, payload.organization);
	if (staleOrganization)
		payload = {
			...payload,
			organization: state.organization,
			projects: retainProjectIdentities(state.projects, payload.projects),
		};
	const didProjectChange = payload.currentProjectId !== state.currentProjectId;
	const currentProjectState = didProjectChange ? null : state.projectState;
	const summaries = mergeProjectSummariesByRevision(
		state.projects,
		payload.projects,
		state.exactBoardRevisionsByProject,
	);
	const nextProjectState = applyKnownProjectLocation(
		summaries,
		payload.currentProjectId,
		payload.projectState ? reconcileProjectStateSessions(currentProjectState, payload.projectState) : null,
	);
	const projects = mergeProjectStateSummary(summaries, payload.currentProjectId, nextProjectState);
	const exactBoardRevisionsByProject = recordExactBoardRevision(
		pruneExactBoardRevisions(state.exactBoardRevisionsByProject, payload.projects),
		payload.currentProjectId,
		nextProjectState,
	);
	const notificationMemory = replaceRuntimeNotificationMemoryFromSnapshot(
		pruneRuntimeNotificationMemory(state.notificationMemory, payload.projects),
		payload.projects,
		payload.notificationSummariesByProject,
		payload.notificationRevisionsByProject,
	);

	return {
		...state,
		currentProjectId: payload.currentProjectId,
		projects,
		organization: payload.organization ?? state.organization,
		exactBoardRevisionsByProject,
		projectState: nextProjectState,
		projectMetadata:
			payload.projectMetadata &&
			isProjectMetadataCurrent(projects, payload.currentProjectId, nextProjectState, payload.projectMetadata)
				? payload.projectMetadata
				: null,
		latestTaskReadyForReview: didProjectChange ? null : state.latestTaskReadyForReview,
		latestTaskTitleUpdate: didProjectChange ? null : state.latestTaskTitleUpdate,
		latestTaskBaseRefUpdate: didProjectChange ? null : state.latestTaskBaseRefUpdate,
		notificationMemory: seedRuntimeNotificationMemoryFromProjectState(
			notificationMemory,
			payload.currentProjectId,
			nextProjectState,
		),
		streamError: null,
		isRuntimeDisconnected: false,
		hasReceivedSnapshot: true,
	};
}

export function createInitialRuntimeStateStreamStore(requestedProjectId: string | null): RuntimeStateStreamStore {
	return {
		streamGeneration: 0,
		currentProjectId: requestedProjectId,
		projects: [],
		organization: null,
		exactBoardRevisionsByProject: {},
		projectState: null,
		projectMetadata: null,
		notificationMemory: createRuntimeNotificationMemory(),
		latestTaskReadyForReview: null,
		latestTaskTitleUpdate: null,
		latestTaskBaseRefUpdate: null,
		streamError: null,
		isRuntimeDisconnected: false,
		hasReceivedSnapshot: false,
	};
}

/** Returns the active-project fence for actions that must never cross project boundaries. */
function getProjectScopedActionProjectId(action: RuntimeStateStreamDomainAction): string | null {
	switch (action.type) {
		case "project_metadata_updated":
		case "task_title_updated":
		case "task_base_ref_updated":
		case "project_state_updated":
		case "task_sessions_updated":
			return action.projectId;
		case "task_ready_for_review":
			return action.payload.projectId;
		default:
			return null;
	}
}

function reduceRuntimeStateStreamDomainAction(
	state: RuntimeStateStreamStore,
	action: RuntimeStateStreamDomainAction,
): RuntimeStateStreamStore {
	const scopedProjectId = getProjectScopedActionProjectId(action);
	if (scopedProjectId !== null && scopedProjectId !== state.currentProjectId) {
		return state;
	}

	switch (action.type) {
		case "requested_project_changed":
			return applyRequestedProjectChange(state, action.preloadedProjectState, action.requestedProjectId);
		case "stream_connected":
			return {
				...state,
				notificationMemory: resetRuntimeNotificationOrdering(state.notificationMemory),
				streamError: null,
				isRuntimeDisconnected: false,
			};
		case "snapshot":
			return applySnapshot(state, action.payload);
		case "organization_updated":
			return isOlderOrganization(state.organization, action.organization)
				? state
				: { ...state, organization: action.organization };
		case "projects_updated": {
			if (isOlderOrganization(state.organization, action.payload.organization)) {
				const projects = mergeProjectSummariesByRevision(
					state.projects,
					retainProjectIdentities(state.projects, action.payload.projects),
					state.exactBoardRevisionsByProject,
				);
				const projectState = applyKnownProjectLocation(projects, state.currentProjectId, state.projectState);
				return {
					...state,
					projects,
					projectState,
					projectMetadata: projectState?.repoPath !== state.projectState?.repoPath ? null : state.projectMetadata,
				};
			}
			const didProjectChange = action.nextProjectId !== state.currentProjectId;
			const projects = mergeProjectSummariesByRevision(
				state.projects,
				action.payload.projects,
				state.exactBoardRevisionsByProject,
			);
			const projectState = didProjectChange
				? null
				: applyKnownProjectLocation(projects, state.currentProjectId, state.projectState);
			return {
				...state,
				currentProjectId: action.nextProjectId,
				organization: action.payload.organization ?? state.organization,
				projects,
				exactBoardRevisionsByProject: pruneExactBoardRevisions(
					state.exactBoardRevisionsByProject,
					action.payload.projects,
				),
				notificationMemory: pruneRuntimeNotificationMemory(state.notificationMemory, action.payload.projects),
				projectState,
				projectMetadata:
					didProjectChange || projectState?.repoPath !== state.projectState?.repoPath
						? null
						: state.projectMetadata,
				latestTaskReadyForReview: didProjectChange ? null : state.latestTaskReadyForReview,
				latestTaskTitleUpdate: didProjectChange ? null : state.latestTaskTitleUpdate,
				latestTaskBaseRefUpdate: didProjectChange ? null : state.latestTaskBaseRefUpdate,
				hasReceivedSnapshot: true,
			};
		}
		case "project_metadata_updated":
			if (
				!isProjectMetadataCurrent(
					state.projects,
					state.currentProjectId,
					state.projectState,
					action.projectMetadata,
				)
			)
				return state;
			return {
				...state,
				projectMetadata: action.projectMetadata,
			};
		case "task_ready_for_review":
			return {
				...state,
				latestTaskReadyForReview: action.payload,
			};
		case "task_title_updated":
			return {
				...state,
				latestTaskTitleUpdate: {
					projectId: action.projectId,
					taskId: action.taskId,
					title: action.title,
					autoGenerated: action.autoGenerated,
				},
			};
		case "task_base_ref_updated":
			return {
				...state,
				latestTaskBaseRefUpdate: {
					projectId: action.projectId,
					taskId: action.taskId,
					baseRef: action.baseRef,
				},
			};
		case "project_state_updated": {
			if (
				state.projectState &&
				action.projectState.revision < state.projectState.revision &&
				(action.projectState.metadataRevision ?? 0) <= (state.projectState.metadataRevision ?? 0)
			)
				return state;
			const nextProjectState = applyKnownProjectLocation(
				state.projects,
				state.currentProjectId,
				reconcileProjectStateSessions(state.projectState, action.projectState),
			);
			return {
				...state,
				projects: mergeProjectStateSummary(state.projects, state.currentProjectId, nextProjectState),
				exactBoardRevisionsByProject: recordExactBoardRevision(
					state.exactBoardRevisionsByProject,
					state.currentProjectId,
					nextProjectState,
				),
				projectState: nextProjectState,
				projectMetadata: nextProjectState?.repoPath !== state.projectState?.repoPath ? null : state.projectMetadata,
			};
		}
		case "project_management_updated": {
			if (!state.projects.some((project) => project.id === action.project.id)) return state;
			const projects = mergeProjectSummariesByRevision(
				state.projects,
				state.projects.map((project) => (project.id === action.project.id ? action.project : project)),
				state.exactBoardRevisionsByProject,
			);
			const projectState = applyKnownProjectLocation(projects, state.currentProjectId, state.projectState);
			const next = {
				...state,
				projects,
				projectState,
				projectMetadata: projectState?.repoPath !== state.projectState?.repoPath ? null : state.projectMetadata,
			};
			return action.projectState && action.project.id === state.currentProjectId
				? reduceRuntimeStateStreamDomainAction(next, {
						type: "project_state_updated",
						projectId: action.project.id,
						projectState: action.projectState,
					})
				: next;
		}
		case "task_sessions_updated":
			if (!state.projectState) {
				return state;
			}
			return {
				...state,
				projectState: {
					...state.projectState,
					sessions: mergeTaskSessionSummaries(state.projectState.sessions, action.summaries),
				},
			};
		case "task_notification": {
			// Versioned live deltas and connection snapshots are the notification
			// projection's only replacement paths. Project state may seed a preload,
			// but does not compete as a second owner after the stream is connected.
			const notificationMemory = applyRuntimeNotificationDelta(state.notificationMemory, action);
			if (notificationMemory === state.notificationMemory) {
				return state;
			}
			return {
				...state,
				notificationMemory,
			};
		}
		case "stream_error":
			return {
				...state,
				streamError: action.message,
				isRuntimeDisconnected: false,
			};
		case "stream_disconnected":
			return {
				...state,
				streamError: action.message,
				isRuntimeDisconnected: true,
			};
	}
}

export function runtimeStateStreamReducer(
	state: RuntimeStateStreamStore,
	action: RuntimeStateStreamAction,
): RuntimeStateStreamStore {
	switch (action.type) {
		case "stream_generation_changed":
			return applyRequestedProjectChange(
				{
					...state,
					streamGeneration: action.streamGeneration,
				},
				action.preloadedProjectState,
				action.requestedProjectId,
			);
		case "stream_action":
			return action.streamGeneration === state.streamGeneration
				? reduceRuntimeStateStreamDomainAction(state, action.action)
				: state;
		default:
			return reduceRuntimeStateStreamDomainAction(state, action);
	}
}

function isOlderOrganization(
	current: ProjectOrganization | null,
	incoming: ProjectOrganization | null | undefined,
): boolean {
	return current !== null && (!incoming || (incoming.id === current.id && incoming.revision < current.revision));
}

function retainProjectIdentities(
	current: RuntimeProjectSummary[],
	incoming: RuntimeProjectSummary[],
): RuntimeProjectSummary[] {
	const byId = new Map(incoming.map((project) => [project.id, project]));
	return current.map((project) => byId.get(project.id) ?? project);
}
