/**
 * Typed dispatch map for incoming RuntimeStateStream WebSocket messages.
 *
 * The handler map is keyed by message type discriminant. The compiler enforces
 * that every member of the RuntimeStateStreamMessage union has a handler — add
 * a new message type and you get a type error here until you handle it.
 *
 * Handlers are imperative: they dispatch reducer actions and may update
 * connection-scoped mutable state via the context parameter.
 */
import type { Dispatch } from "react";
import type {
	RuntimeStateStreamMessage,
	RuntimeStateStreamProjectsMessage,
	RuntimeStateStreamSnapshotMessage,
} from "@/runtime/types";

// ── Reducer action type (imported from the hook) ─────────────────────────────

// Re-declare the action union here to avoid a circular import. The hook file
// defines the canonical type; this type is structurally identical and the
// compiler verifies compatibility at the call site.
type StreamAction =
	| { type: "snapshot"; payload: RuntimeStateStreamSnapshotMessage }
	| { type: "projects_updated"; payload: RuntimeStateStreamProjectsMessage; nextProjectId: string | null }
	| {
			type: "project_metadata_updated";
			projectMetadata: RuntimeStateStreamMessage extends infer M
				? M extends { type: "project_metadata_updated"; projectMetadata: infer W }
					? W
					: never
				: never;
	  }
	| { type: "task_ready_for_review"; payload: Extract<RuntimeStateStreamMessage, { type: "task_ready_for_review" }> }
	| { type: "task_title_updated"; taskId: string; title: string; autoGenerated?: boolean }
	| { type: "task_base_ref_updated"; taskId: string; baseRef: string }
	| { type: "task_working_directory_updated"; taskId: string; workingDirectory: string; useWorktree: boolean }
	| {
			type: "project_state_updated";
			projectState: Extract<RuntimeStateStreamMessage, { type: "project_state_updated" }>["projectState"];
	  }
	| {
			type: "task_sessions_updated";
			summaries: Extract<RuntimeStateStreamMessage, { type: "task_sessions_updated" }>["summaries"];
	  }
	| {
			type: "task_notification";
			projectId: string;
			summaries: Extract<RuntimeStateStreamMessage, { type: "task_notification" }>["summaries"];
	  }
	| {
			type: "debug_logging_state";
			level: "debug" | "info" | "warn" | "error";
			recentEntries?: Extract<RuntimeStateStreamMessage, { type: "debug_logging_state" }>["recentEntries"];
	  }
	| { type: "debug_log_batch"; entries: Extract<RuntimeStateStreamMessage, { type: "debug_log_batch" }>["entries"] }
	| { type: "stream_error"; message: string }
	| { type: "requested_project_changed"; preloadedProjectState: null; requestedProjectId: string };

// ── Dispatch context ─────────────────────────────────────────────────────────

/** Connection-scoped mutable state that some handlers need for side effects. */
export interface StreamDispatchContext {
	getActiveProjectId: () => string | null;
	setActiveProjectId: (id: string | null) => void;
	reconnectToProject: (projectId: string) => void;
	dispatch: Dispatch<StreamAction>;
}

// ── Handler type ─────────────────────────────────────────────────────────────

type StreamMessageHandler<T extends RuntimeStateStreamMessage["type"]> = (
	message: Extract<RuntimeStateStreamMessage, { type: T }>,
	ctx: StreamDispatchContext,
) => void;

// ── Resolve helper ───────────────────────────────────────────────────────────

export function resolveProjectIdAfterProjectsUpdate(
	currentProjectId: string | null,
	payload: RuntimeStateStreamProjectsMessage,
): string | null {
	if (currentProjectId && payload.projects.some((project) => project.id === currentProjectId)) {
		return currentProjectId;
	}
	return payload.currentProjectId;
}

// ── Handler map (compiler-enforced completeness) ─────────────────────────────

const streamMessageHandlers: {
	[K in RuntimeStateStreamMessage["type"]]: StreamMessageHandler<K>;
} = {
	snapshot: (msg, ctx) => {
		ctx.setActiveProjectId(msg.currentProjectId);
		ctx.dispatch({ type: "snapshot", payload: msg });
	},

	projects_updated: (msg, ctx) => {
		const previousProjectId = ctx.getActiveProjectId();
		const nextProjectId = resolveProjectIdAfterProjectsUpdate(previousProjectId, msg);
		ctx.setActiveProjectId(nextProjectId);
		ctx.dispatch({ type: "projects_updated", payload: msg, nextProjectId });
		if (nextProjectId && nextProjectId !== previousProjectId) {
			ctx.reconnectToProject(nextProjectId);
		}
	},

	project_state_updated: (msg, ctx) => {
		if (msg.projectId !== ctx.getActiveProjectId()) return;
		ctx.dispatch({ type: "project_state_updated", projectState: msg.projectState });
	},

	project_metadata_updated: (msg, ctx) => {
		if (msg.projectId !== ctx.getActiveProjectId()) return;
		ctx.dispatch({ type: "project_metadata_updated", projectMetadata: msg.projectMetadata });
	},

	task_sessions_updated: (msg, ctx) => {
		if (msg.projectId !== ctx.getActiveProjectId()) return;
		ctx.dispatch({ type: "task_sessions_updated", summaries: msg.summaries });
	},

	task_notification: (msg, ctx) => {
		ctx.dispatch({ type: "task_notification", projectId: msg.projectId, summaries: msg.summaries });
	},

	task_ready_for_review: (msg, ctx) => {
		if (msg.projectId !== ctx.getActiveProjectId()) return;
		ctx.dispatch({ type: "task_ready_for_review", payload: msg });
	},

	task_title_updated: (msg, ctx) => {
		if (msg.projectId !== ctx.getActiveProjectId()) return;
		ctx.dispatch({
			type: "task_title_updated",
			taskId: msg.taskId,
			title: msg.title,
			autoGenerated: msg.autoGenerated,
		});
	},

	task_base_ref_updated: (msg, ctx) => {
		if (msg.projectId !== ctx.getActiveProjectId()) return;
		ctx.dispatch({
			type: "task_base_ref_updated",
			taskId: msg.taskId,
			baseRef: msg.baseRef,
		});
	},

	task_working_directory_updated: (msg, ctx) => {
		if (msg.projectId !== ctx.getActiveProjectId()) return;
		ctx.dispatch({
			type: "task_working_directory_updated",
			taskId: msg.taskId,
			workingDirectory: msg.workingDirectory,
			useWorktree: msg.useWorktree,
		});
	},

	debug_logging_state: (msg, ctx) => {
		ctx.dispatch({ type: "debug_logging_state", level: msg.level, recentEntries: msg.recentEntries });
	},

	debug_log_batch: (msg, ctx) => {
		ctx.dispatch({ type: "debug_log_batch", entries: msg.entries });
	},

	error: (msg, ctx) => {
		ctx.dispatch({ type: "stream_error", message: msg.message });
	},
};

// ── Public dispatch function ─────────────────────────────────────────────────

/**
 * Dispatches an incoming WebSocket message to its typed handler.
 * The handler map above guarantees compile-time completeness.
 */
export function dispatchStreamMessage(payload: RuntimeStateStreamMessage, ctx: StreamDispatchContext): void {
	// Each handler is properly typed at the definition site. The indexed access
	// requires a cast because TS can't narrow through dynamic key lookup.
	const handler = streamMessageHandlers[payload.type] as (
		msg: RuntimeStateStreamMessage,
		ctx: StreamDispatchContext,
	) => void;
	handler(payload, ctx);
}
