/**
 * Pure message-to-action resolution for incoming RuntimeStateStream messages.
 *
 * This module intentionally does not own any WebSocket side effects. It takes
 * the current active project id, translates messages into typed domain actions,
 * and reports whether the transport should reconnect to a different project.
 * Project-ownership validation belongs to the state-store boundary.
 */
import type { RuntimeStateStreamDomainAction } from "@/runtime/runtime-state-stream-store";
import type { RuntimeStateStreamMessage, RuntimeStateStreamProjectsMessage } from "@/runtime/types";

export interface RuntimeStreamDispatchState {
	activeProjectId: string | null;
}

export interface RuntimeStreamDispatchResult {
	actions: RuntimeStateStreamDomainAction[];
	nextActiveProjectId: string | null;
	reconnectProjectId: string | null;
}

type StreamMessageHandler<T extends RuntimeStateStreamMessage["type"]> = (
	message: Extract<RuntimeStateStreamMessage, { type: T }>,
	state: RuntimeStreamDispatchState,
) => RuntimeStreamDispatchResult;

function createDispatchResult(
	actions: RuntimeStateStreamDomainAction[],
	nextActiveProjectId: string | null,
	reconnectProjectId: string | null = null,
): RuntimeStreamDispatchResult {
	return {
		actions,
		nextActiveProjectId,
		reconnectProjectId,
	};
}

function createStableProjectResult(
	action: RuntimeStateStreamDomainAction,
	state: RuntimeStreamDispatchState,
): RuntimeStreamDispatchResult {
	return createDispatchResult([action], state.activeProjectId);
}

export function resolveProjectIdAfterProjectsUpdate(
	currentProjectId: string | null,
	payload: RuntimeStateStreamProjectsMessage,
): string | null {
	if (currentProjectId && payload.projects.some((project) => project.id === currentProjectId)) {
		return currentProjectId;
	}
	return payload.currentProjectId;
}

const streamMessageHandlers: {
	[K in RuntimeStateStreamMessage["type"]]: StreamMessageHandler<K>;
} = {
	snapshot: (msg) => createDispatchResult([{ type: "snapshot", payload: msg }], msg.currentProjectId),

	projects_updated: (msg, state) => {
		const nextProjectId = resolveProjectIdAfterProjectsUpdate(state.activeProjectId, msg);
		const reconnectProjectId = nextProjectId && nextProjectId !== state.activeProjectId ? nextProjectId : null;
		return createDispatchResult(
			[{ type: "projects_updated", payload: msg, nextProjectId }],
			nextProjectId,
			reconnectProjectId,
		);
	},

	project_state_updated: (msg, state) =>
		createStableProjectResult(
			{ type: "project_state_updated", projectId: msg.projectId, projectState: msg.projectState },
			state,
		),

	project_metadata_updated: (msg, state) =>
		createStableProjectResult(
			{
				type: "project_metadata_updated",
				projectId: msg.projectId,
				projectMetadata: msg.projectMetadata,
			},
			state,
		),

	task_sessions_updated: (msg, state) =>
		createStableProjectResult(
			{ type: "task_sessions_updated", projectId: msg.projectId, summaries: msg.summaries },
			state,
		),

	task_notification: (msg, state) => {
		const action: RuntimeStateStreamDomainAction = {
			type: "task_notification",
			projectId: msg.projectId,
			notificationRevision: msg.notificationRevision,
			summaries: msg.summaries,
			...(msg.removedTaskIds?.length ? { removedTaskIds: msg.removedTaskIds } : undefined),
			...(msg.replace ? { replace: true } : undefined),
		};
		return createStableProjectResult(action, state);
	},

	task_ready_for_review: (msg, state) =>
		createStableProjectResult({ type: "task_ready_for_review", payload: msg }, state),

	task_title_updated: (msg, state) =>
		createStableProjectResult(
			{
				type: "task_title_updated",
				projectId: msg.projectId,
				taskId: msg.taskId,
				title: msg.title,
				autoGenerated: msg.autoGenerated,
			},
			state,
		),

	task_base_ref_updated: (msg, state) =>
		createStableProjectResult(
			{
				type: "task_base_ref_updated",
				projectId: msg.projectId,
				taskId: msg.taskId,
				baseRef: msg.baseRef,
			},
			state,
		),

	diagnostics_state: (_msg, state) => createDispatchResult([], state.activeProjectId),
	diagnostic_record_batch: (_msg, state) => createDispatchResult([], state.activeProjectId),
	diagnostic_capture_state: (_msg, state) => createDispatchResult([], state.activeProjectId),
	diagnostic_snapshot_request: (_msg, state) => createDispatchResult([], state.activeProjectId),

	error: (msg, state) => createDispatchResult([{ type: "stream_error", message: msg.message }], state.activeProjectId),
};

export function resolveStreamMessage(
	payload: RuntimeStateStreamMessage,
	state: RuntimeStreamDispatchState,
): RuntimeStreamDispatchResult {
	const handler = streamMessageHandlers[payload.type] as (
		msg: RuntimeStateStreamMessage,
		state: RuntimeStreamDispatchState,
	) => RuntimeStreamDispatchResult;
	return handler(payload, state);
}
