import { useEffect, useReducer } from "react";
import { consumeProjectPreload } from "@/runtime/project-preload-cache";
import { setRuntimeDisconnected } from "@/runtime/runtime-connection-state";
import { dispatchStreamMessage, type StreamDispatchContext } from "@/runtime/runtime-stream-dispatch";
import type {
	RuntimeDebugLogEntry,
	RuntimeProjectMetadata,
	RuntimeProjectStateResponse,
	RuntimeProjectSummary,
	RuntimeStateStreamMessage,
	RuntimeStateStreamProjectsMessage,
	RuntimeStateStreamSnapshotMessage,
	RuntimeStateStreamTaskReadyForReviewMessage,
	RuntimeTaskSessionSummary,
} from "@/runtime/types";
import { createClientLogger } from "@/utils/client-logger";
import { toErrorMessage } from "@/utils/to-error-message";

const log = createClientLogger("ws-stream");

const STREAM_RECONNECT_BASE_DELAY_MS = 500;
const STREAM_RECONNECT_MAX_DELAY_MS = 5_000;
const DEBUG_LOG_ENTRIES_MAX = 500;

function mergeTaskSessionSummaries(
	currentSessions: Record<string, RuntimeTaskSessionSummary>,
	summaries: RuntimeTaskSessionSummary[],
): Record<string, RuntimeTaskSessionSummary> {
	if (summaries.length === 0) {
		return currentSessions;
	}
	const nextSessions = { ...currentSessions };
	for (const summary of summaries) {
		const existing = nextSessions[summary.taskId];
		if (!existing || existing.updatedAt <= summary.updatedAt) {
			nextSessions[summary.taskId] = summary;
		}
	}
	return nextSessions;
}

function getRuntimeStreamUrl(projectId: string | null): string {
	const protocol = window.location.protocol === "https:" ? "wss:" : "ws:";
	const url = new URL(`${protocol}//${window.location.host}/api/runtime/ws`);
	if (projectId) {
		url.searchParams.set("projectId", projectId);
	}
	return url.toString();
}

export interface TaskTitleUpdate {
	taskId: string;
	title: string;
	autoGenerated?: boolean;
}

export interface TaskBaseRefUpdate {
	taskId: string;
	baseRef: string;
}

export interface TaskWorkingDirectoryUpdate {
	taskId: string;
	workingDirectory: string;
	useWorktree: boolean;
}

export interface UseRuntimeStateStreamResult {
	currentProjectId: string | null;
	projects: RuntimeProjectSummary[];
	projectState: RuntimeProjectStateResponse | null;
	projectMetadata: RuntimeProjectMetadata | null;
	notificationSessions: Record<string, RuntimeTaskSessionSummary>;
	notificationProjectIds: Record<string, string>;
	latestTaskReadyForReview: RuntimeStateStreamTaskReadyForReviewMessage | null;
	latestTaskTitleUpdate: TaskTitleUpdate | null;
	latestTaskBaseRefUpdate: TaskBaseRefUpdate | null;
	latestTaskWorkingDirectoryUpdate: TaskWorkingDirectoryUpdate | null;
	logLevel: "debug" | "info" | "warn" | "error";
	debugLogEntries: RuntimeDebugLogEntry[];
	streamError: string | null;
	isRuntimeDisconnected: boolean;
	hasReceivedSnapshot: boolean;
}

interface RuntimeStateStreamStore {
	currentProjectId: string | null;
	projects: RuntimeProjectSummary[];
	projectState: RuntimeProjectStateResponse | null;
	projectMetadata: RuntimeProjectMetadata | null;
	notificationSessions: Record<string, RuntimeTaskSessionSummary>;
	notificationProjectIds: Record<string, string>;
	latestTaskReadyForReview: RuntimeStateStreamTaskReadyForReviewMessage | null;
	latestTaskTitleUpdate: TaskTitleUpdate | null;
	latestTaskBaseRefUpdate: TaskBaseRefUpdate | null;
	latestTaskWorkingDirectoryUpdate: TaskWorkingDirectoryUpdate | null;
	logLevel: "debug" | "info" | "warn" | "error";
	debugLogEntries: RuntimeDebugLogEntry[];
	streamError: string | null;
	isRuntimeDisconnected: boolean;
	hasReceivedSnapshot: boolean;
}

type RuntimeStateStreamAction =
	| {
			type: "requested_project_changed";
			preloadedProjectState: RuntimeProjectStateResponse | null;
			requestedProjectId: string | null;
	  }
	| { type: "stream_connected" }
	| { type: "snapshot"; payload: RuntimeStateStreamSnapshotMessage }
	| {
			type: "projects_updated";
			payload: RuntimeStateStreamProjectsMessage;
			nextProjectId: string | null;
	  }
	| { type: "project_metadata_updated"; projectMetadata: RuntimeProjectMetadata }
	| { type: "task_ready_for_review"; payload: RuntimeStateStreamTaskReadyForReviewMessage }
	| { type: "task_title_updated"; taskId: string; title: string; autoGenerated?: boolean }
	| { type: "task_base_ref_updated"; taskId: string; baseRef: string }
	| { type: "task_working_directory_updated"; taskId: string; workingDirectory: string; useWorktree: boolean }
	| { type: "project_state_updated"; projectState: RuntimeProjectStateResponse }
	| { type: "task_sessions_updated"; summaries: RuntimeTaskSessionSummary[] }
	| { type: "task_notification"; projectId: string; summaries: RuntimeTaskSessionSummary[] }
	| { type: "debug_logging_state"; level: "debug" | "info" | "warn" | "error"; recentEntries?: RuntimeDebugLogEntry[] }
	| { type: "debug_log_batch"; entries: RuntimeDebugLogEntry[] }
	| { type: "debug_log_clear" }
	| { type: "stream_error"; message: string }
	| { type: "stream_disconnected"; message: string };

function createInitialRuntimeStateStreamStore(requestedProjectId: string | null): RuntimeStateStreamStore {
	return {
		currentProjectId: requestedProjectId,
		projects: [],
		projectState: null,
		projectMetadata: null,
		notificationSessions: {},
		notificationProjectIds: {},
		latestTaskReadyForReview: null,
		latestTaskTitleUpdate: null,
		latestTaskBaseRefUpdate: null,
		latestTaskWorkingDirectoryUpdate: null,
		logLevel: "warn",
		debugLogEntries: [],
		streamError: null,
		isRuntimeDisconnected: false,
		hasReceivedSnapshot: false,
	};
}

function runtimeStateStreamReducer(
	state: RuntimeStateStreamStore,
	action: RuntimeStateStreamAction,
): RuntimeStateStreamStore {
	if (action.type === "requested_project_changed") {
		if (action.preloadedProjectState) {
			// Advance currentProjectId immediately — we have preloaded data to render
			// without waiting for the WebSocket snapshot. The non-preloaded path leaves
			// currentProjectId unchanged; the snapshot action updates it.
			const preloadedSessions = Object.values(action.preloadedProjectState.sessions ?? {});
			return {
				...state,
				currentProjectId: action.requestedProjectId,
				projectState: action.preloadedProjectState,
				projectMetadata: null,
				notificationSessions: mergeTaskSessionSummaries(state.notificationSessions, preloadedSessions),
				notificationProjectIds: action.requestedProjectId
					? {
							...state.notificationProjectIds,
							...Object.fromEntries(preloadedSessions.map((s) => [s.taskId, action.requestedProjectId!])),
						}
					: state.notificationProjectIds,
				streamError: null,
				isRuntimeDisconnected: false,
				hasReceivedSnapshot: true,
			};
		}
		return {
			...state,
			projectState: null,
			projectMetadata: null,
			streamError: null,
			isRuntimeDisconnected: false,
			hasReceivedSnapshot: false,
		};
	}
	if (action.type === "stream_connected") {
		return {
			...state,
			streamError: null,
			isRuntimeDisconnected: false,
		};
	}
	if (action.type === "snapshot") {
		const snapshotSessions = action.payload.projectState?.sessions ?? {};
		const nextProjectState = action.payload.projectState
			? {
					...action.payload.projectState,
					sessions: mergeTaskSessionSummaries(state.projectState?.sessions ?? {}, Object.values(snapshotSessions)),
				}
			: null;
		return {
			currentProjectId: action.payload.currentProjectId,
			projects: action.payload.projects,
			projectState: nextProjectState,
			projectMetadata: action.payload.projectMetadata,
			// Seeded from the active project's sessions only; other projects'
			// sessions arrive incrementally via `task_notification` messages.
			notificationSessions: mergeTaskSessionSummaries(state.notificationSessions, Object.values(snapshotSessions)),
			notificationProjectIds: action.payload.currentProjectId
				? {
						...state.notificationProjectIds,
						...Object.fromEntries(
							Object.keys(snapshotSessions).map((taskId) => [taskId, action.payload.currentProjectId!]),
						),
					}
				: state.notificationProjectIds,
			latestTaskReadyForReview: state.latestTaskReadyForReview,
			latestTaskTitleUpdate: state.latestTaskTitleUpdate,
			latestTaskBaseRefUpdate: state.latestTaskBaseRefUpdate,
			latestTaskWorkingDirectoryUpdate: state.latestTaskWorkingDirectoryUpdate,
			logLevel: state.logLevel,
			debugLogEntries: state.debugLogEntries,
			streamError: null,
			isRuntimeDisconnected: false,
			hasReceivedSnapshot: true,
		};
	}
	if (action.type === "projects_updated") {
		const didProjectChange = action.nextProjectId !== state.currentProjectId;
		return {
			...state,
			currentProjectId: action.nextProjectId,
			projects: action.payload.projects,
			projectState: didProjectChange ? null : state.projectState,
			projectMetadata: didProjectChange ? null : state.projectMetadata,
			latestTaskReadyForReview: didProjectChange ? null : state.latestTaskReadyForReview,
			hasReceivedSnapshot: true,
		};
	}
	if (action.type === "project_metadata_updated") {
		return {
			...state,
			projectMetadata: action.projectMetadata,
		};
	}
	if (action.type === "task_ready_for_review") {
		return {
			...state,
			latestTaskReadyForReview: action.payload,
		};
	}
	if (action.type === "task_title_updated") {
		return {
			...state,
			latestTaskTitleUpdate: { taskId: action.taskId, title: action.title, autoGenerated: action.autoGenerated },
		};
	}
	if (action.type === "task_base_ref_updated") {
		return {
			...state,
			latestTaskBaseRefUpdate: { taskId: action.taskId, baseRef: action.baseRef },
		};
	}
	if (action.type === "task_working_directory_updated") {
		return {
			...state,
			latestTaskWorkingDirectoryUpdate: {
				taskId: action.taskId,
				workingDirectory: action.workingDirectory,
				useWorktree: action.useWorktree,
			},
		};
	}
	if (action.type === "project_state_updated") {
		const mergedProjectState = {
			...action.projectState,
			sessions: mergeTaskSessionSummaries(
				state.projectState?.sessions ?? {},
				Object.values(action.projectState.sessions ?? {}),
			),
		};
		return {
			...state,
			projectState: mergedProjectState,
		};
	}
	if (action.type === "task_sessions_updated") {
		if (!state.projectState) {
			return state;
		}
		return {
			...state,
			projectState: {
				...state.projectState,
				sessions: mergeTaskSessionSummaries(state.projectState.sessions, action.summaries),
			},
		};
	}
	if (action.type === "task_notification") {
		// notificationSessions grows monotonically (entries are never removed). This is
		// intentional: the set stays small (one entry per task that emits a notification)
		// and useAudibleNotifications compares against the previous snapshot to detect
		// new events, so pruning would cause duplicate notifications on reconnect.
		return {
			...state,
			notificationSessions: mergeTaskSessionSummaries(state.notificationSessions, action.summaries),
			notificationProjectIds: {
				...state.notificationProjectIds,
				...Object.fromEntries(action.summaries.map((s) => [s.taskId, action.projectId])),
			},
		};
	}
	if (action.type === "debug_logging_state") {
		const incoming = action.recentEntries ?? [];
		// Merge recent entries from server, deduplicating by id.
		const existingIds = new Set(state.debugLogEntries.map((e) => e.id));
		const newEntries = incoming.filter((e) => !existingIds.has(e.id));
		const merged = [...state.debugLogEntries, ...newEntries].slice(-DEBUG_LOG_ENTRIES_MAX);
		return {
			...state,
			logLevel: action.level,
			debugLogEntries: merged,
		};
	}
	if (action.type === "debug_log_batch") {
		const merged = [...state.debugLogEntries, ...action.entries].slice(-DEBUG_LOG_ENTRIES_MAX);
		return {
			...state,
			debugLogEntries: merged,
		};
	}
	if (action.type === "debug_log_clear") {
		return {
			...state,
			debugLogEntries: [],
		};
	}
	if (action.type === "stream_error") {
		return {
			...state,
			streamError: action.message,
			isRuntimeDisconnected: false,
		};
	}
	if (action.type === "stream_disconnected") {
		return {
			...state,
			streamError: action.message,
			isRuntimeDisconnected: true,
		};
	}
	return state;
}

export function useRuntimeStateStream(requestedProjectId: string | null): UseRuntimeStateStreamResult {
	const [state, dispatch] = useReducer(
		runtimeStateStreamReducer,
		requestedProjectId,
		createInitialRuntimeStateStreamStore,
	);
	useEffect(() => {
		let cancelled = false;
		let socket: WebSocket | null = null;
		let reconnectTimer: number | null = null;
		let reconnectAttempt = 0;
		let activeProjectId = requestedProjectId;
		let requestedProjectForConnection = requestedProjectId;

		const preloadedProjectState = requestedProjectId ? consumeProjectPreload(requestedProjectId) : null;
		dispatch({ type: "requested_project_changed", preloadedProjectState, requestedProjectId });

		const cleanupSocket = () => {
			if (socket) {
				socket.onopen = null;
				socket.onmessage = null;
				socket.onerror = null;
				socket.onclose = null;
				socket.close();
				socket = null;
			}
		};

		const scheduleReconnect = () => {
			if (cancelled) {
				return;
			}
			if (reconnectTimer !== null) {
				return;
			}
			const delay = Math.min(STREAM_RECONNECT_MAX_DELAY_MS, STREAM_RECONNECT_BASE_DELAY_MS * 2 ** reconnectAttempt);
			reconnectAttempt += 1;
			reconnectTimer = window.setTimeout(() => {
				connect();
			}, delay);
		};

		const connect = () => {
			if (cancelled) {
				return;
			}
			if (reconnectTimer !== null) {
				window.clearTimeout(reconnectTimer);
				reconnectTimer = null;
			}
			cleanupSocket();
			try {
				socket = new WebSocket(getRuntimeStreamUrl(requestedProjectForConnection));
			} catch (error) {
				setRuntimeDisconnected(true);
				dispatch({
					type: "stream_disconnected",
					message: toErrorMessage(error),
				});
				scheduleReconnect();
				return;
			}
			socket.onopen = () => {
				reconnectAttempt = 0;
				setRuntimeDisconnected(false);
				dispatch({ type: "stream_connected" });
			};
			const streamCtx: StreamDispatchContext = {
				getActiveProjectId: () => activeProjectId,
				setActiveProjectId: (id) => {
					activeProjectId = id;
				},
				reconnectToProject: (projectId) => {
					requestedProjectForConnection = projectId;
					dispatch({
						type: "requested_project_changed",
						preloadedProjectState: null,
						requestedProjectId: projectId,
					});
					connect();
				},
				dispatch,
			};
			socket.onmessage = (event) => {
				try {
					const payload = JSON.parse(String(event.data)) as RuntimeStateStreamMessage;
					dispatchStreamMessage(payload, streamCtx);
				} catch (err) {
					log.warn("Malformed stream message", err);
				}
			};
			socket.onclose = () => {
				if (cancelled) {
					return;
				}
				setRuntimeDisconnected(true);
				dispatch({
					type: "stream_disconnected",
					message: "Runtime stream disconnected.",
				});
				scheduleReconnect();
			};
			socket.onerror = () => {
				if (cancelled) {
					return;
				}
				setRuntimeDisconnected(true);
				log.error("WebSocket connection failed");
				dispatch({
					type: "stream_disconnected",
					message: "Runtime stream connection failed.",
				});
			};
		};

		connect();

		return () => {
			cancelled = true;
			if (reconnectTimer != null) {
				window.clearTimeout(reconnectTimer);
			}
			cleanupSocket();
		};
	}, [requestedProjectId]);

	return {
		currentProjectId: state.currentProjectId,
		projects: state.projects,
		projectState: state.projectState,
		projectMetadata: state.projectMetadata,
		notificationSessions: state.notificationSessions,
		notificationProjectIds: state.notificationProjectIds,
		latestTaskReadyForReview: state.latestTaskReadyForReview,
		latestTaskTitleUpdate: state.latestTaskTitleUpdate,
		latestTaskBaseRefUpdate: state.latestTaskBaseRefUpdate,
		latestTaskWorkingDirectoryUpdate: state.latestTaskWorkingDirectoryUpdate,
		logLevel: state.logLevel,
		debugLogEntries: state.debugLogEntries,
		streamError: state.streamError,
		isRuntimeDisconnected: state.isRuntimeDisconnected,
		hasReceivedSnapshot: state.hasReceivedSnapshot,
	};
}
