import { appendFile, mkdir } from "node:fs/promises";
import { join } from "node:path";

import { describe, expect, it, vi } from "vitest";

import { findCardInBoard } from "../../src/core";
import { createCodexTaskTitleMonitor } from "../../src/server/codex-task-title-monitor";
import { loadProjectContext, loadProjectState, ProjectBoardCommandService } from "../../src/state";
import { InMemorySessionSummaryStore } from "../../src/terminal";
import { initGitRepository } from "../utilities/git-env";
import { createTestTaskSessionSummary } from "../utilities/task-session-factory";
import { createTempDir, withTemporaryHome } from "../utilities/temp-dir";

describe("native Codex title synchronization", { concurrent: false }, () => {
	it("persists provider name updates until a same-wording manual rename takes ownership", async () => {
		await withTemporaryHome(async () => {
			const sandbox = createTempDir("quarterdeck-title-monitor-");
			let monitor: ReturnType<typeof createCodexTaskTitleMonitor> | undefined;
			try {
				const projectPath = join(sandbox.path, "project");
				const codexHome = join(sandbox.path, "codex-profile");
				await mkdir(projectPath);
				await mkdir(codexHome);
				initGitRepository(projectPath);
				const { projectId } = await loadProjectContext(projectPath);
				const scope = { projectId, projectPath };
				const session = createTestTaskSessionSummary({
					taskId: "task-a",
					agentId: "codex",
					sessionInstanceId: "launch-a",
					resumeSessionId: "thread-a",
				});
				const service = new ProjectBoardCommandService({ getAuthoritativeSessions: () => ({ "task-a": session }) });
				const initial = await loadProjectState(projectPath);
				await service.execute(scope, {
					commandId: "create-task",
					expectedRevision: initial.revision,
					command: {
						kind: "create_task",
						columnId: "review",
						taskId: "task-a",
						prompt: "Follow native thread names",
						baseRef: "main",
						agentId: "codex",
						createdAt: 100,
					},
				});
				await service.setGeneratedTaskTitle(scope, "task-a", 100, "Local placeholder", 200);
				const store = new InMemorySessionSummaryStore();
				vi.spyOn(store, "listSummaries").mockReturnValue([session]);
				vi.spyOn(store, "getSummary").mockReturnValue(session);
				const terminalManager = {
					store,
					getTaskSessionProcessIdentity: () => ({
						pid: 123,
						sessionInstanceId: "launch-a",
						launchOperationId: null,
						agentId: "codex" as const,
						binary: "codex",
						profileEnvironment: { CODEX_HOME: codexHome },
					}),
				};
				const publishTitleUpdated = vi.fn();
				monitor = createCodexTaskTitleMonitor({
					listManagedProjects: () => [{ projectId, projectPath, terminalManager }],
					loadBoard: async () => (await loadProjectState(projectPath)).board,
					boardCommands: service,
					publishTitleUpdated,
				});
				const appendName = (threadName: string) =>
					appendFile(
						join(codexHome, "session_index.jsonl"),
						`${JSON.stringify({ id: "thread-a", thread_name: threadName, updated_at: "2026-09-25T00:00:00Z" })}\n`,
					);
				await monitor.refresh();
				expect(findCardInBoard((await loadProjectState(projectPath)).board, "task-a")).toMatchObject({
					title: "Local placeholder",
					titleAutoGenerated: true,
				});
				await appendName("First Codex name");
				await monitor.refresh();
				expect(findCardInBoard((await loadProjectState(projectPath)).board, "task-a")).toMatchObject({
					title: "First Codex name",
					titleAutoGenerated: true,
				});
				await appendName("Updated Codex name");
				await monitor.refresh();
				const updated = await loadProjectState(projectPath);
				expect(findCardInBoard(updated.board, "task-a")).toMatchObject({
					title: "Updated Codex name",
					titleAutoGenerated: true,
				});
				await monitor.refresh();
				expect((await loadProjectState(projectPath)).revision).toBe(updated.revision);
				const manual = await service.execute(scope, {
					commandId: "manual-rename",
					expectedRevision: updated.revision,
					command: { kind: "patch_task", taskId: "task-a", title: "Updated Codex name", updatedAt: Date.now() },
				});
				await appendName("Ignored later name");
				await monitor.refresh();
				const final = await loadProjectState(projectPath);
				expect(final.revision).toBe(manual.state.revision);
				expect(findCardInBoard(final.board, "task-a")).toMatchObject({
					title: "Updated Codex name",
					titleAutoGenerated: false,
				});
				expect(publishTitleUpdated.mock.calls).toEqual([
					[{ projectId, taskId: "task-a", title: "First Codex name" }],
					[{ projectId, taskId: "task-a", title: "Updated Codex name" }],
				]);
			} finally {
				await monitor?.close();
				sandbox.cleanup();
			}
		});
	});
});
