import {
	runtimeAgentIdSchema,
	runtimeBoardCardSchema,
	runtimeBoardColumnIdSchema,
	runtimeCodexOptionsSchema,
	runtimeTaskImageSchema,
} from "@runtime-contract";
import { z } from "zod";
import type { BoardCard, BoardColumnId, TaskImage } from "@/types";

const rawPersistedBoardSchema = z.object({
	columns: z.array(z.unknown()),
});

const rawPersistedBoardColumnSchema = z.object({
	id: z.unknown(),
	cards: z.unknown().optional(),
});

const rawPersistedBoardCardSchema = z.object({
	id: z.unknown().optional(),
	title: z.unknown().optional(),
	titleAutoGenerated: z.unknown().optional(),
	prompt: z.unknown().optional(),
	images: z.unknown().optional(),
	baseRef: z.unknown().optional(),
	baseRefPinned: z.unknown().optional(),
	agentId: z.unknown().optional(),
	codexOptions: z.unknown().optional(),
	useWorktree: z.unknown().optional(),
	workingDirectory: z.unknown().optional(),
	branch: z.unknown().optional(),
	pinned: z.unknown().optional(),
	colorIndex: z.unknown().optional(),
	unstarted: z.unknown().optional(),
	createdAt: z.unknown().optional(),
	updatedAt: z.unknown().optional(),
});

export interface ParsedPersistedBoardColumn {
	id: BoardColumnId | "backlog";
	cards: unknown[];
}

export interface ParsedPersistedBoardPayload {
	columns: ParsedPersistedBoardColumn[];
}

export function parsePersistedBoardPayload(rawBoard: unknown): ParsedPersistedBoardPayload | null {
	const result = rawPersistedBoardSchema.safeParse(rawBoard);
	if (!result.success) {
		return null;
	}

	const columns: ParsedPersistedBoardColumn[] = [];
	for (const rawColumn of result.data.columns) {
		const column = parsePersistedBoardColumn(rawColumn);
		if (column) {
			columns.push(column);
		}
	}

	return {
		columns,
	};
}

export function parsePersistedBoardCard(
	rawCard: unknown,
	options: { createTaskId: () => string; now?: number },
): BoardCard | null {
	const result = rawPersistedBoardCardSchema.safeParse(rawCard);
	if (!result.success) {
		return null;
	}

	const prompt = parseRequiredTrimmedString(result.data.prompt);
	if (!prompt) {
		return null;
	}

	const baseRef = parseTrimmedString(result.data.baseRef);
	if (baseRef === null) {
		return null;
	}

	const color = runtimeBoardCardSchema.shape.colorIndex.safeParse(result.data.colorIndex);
	const now = options.now ?? Date.now();
	const agentId = parsePersistedAgentId(result.data.agentId);
	const codexOptions = runtimeCodexOptionsSchema.safeParse(result.data.codexOptions);

	return {
		id: parseNonEmptyString(result.data.id) ?? options.createTaskId(),
		title: typeof result.data.title === "string" ? result.data.title : null,
		...(typeof result.data.titleAutoGenerated === "boolean"
			? { titleAutoGenerated: result.data.titleAutoGenerated }
			: {}),
		prompt,
		images: parsePersistedTaskImages(result.data.images),
		baseRef,
		...(typeof result.data.baseRefPinned === "boolean" ? { baseRefPinned: result.data.baseRefPinned } : {}),
		...(agentId ? { agentId } : {}),
		...(agentId === "codex" && codexOptions.success ? { codexOptions: codexOptions.data } : {}),
		useWorktree: typeof result.data.useWorktree === "boolean" ? result.data.useWorktree : undefined,
		workingDirectory: parseOptionalNullableString(result.data.workingDirectory),
		branch: parseOptionalNullableString(result.data.branch),
		...(color.success && color.data !== undefined ? { colorIndex: color.data } : {}),
		pinned: typeof result.data.pinned === "boolean" ? result.data.pinned : undefined,
		...(result.data.unstarted === true ? { unstarted: true } : {}),
		createdAt: typeof result.data.createdAt === "number" ? result.data.createdAt : now,
		updatedAt: typeof result.data.updatedAt === "number" ? result.data.updatedAt : now,
	};
}

function parsePersistedAgentId(value: unknown): BoardCard["agentId"] | null {
	const result = runtimeAgentIdSchema.safeParse(value);
	return result.success ? result.data : null;
}

export function parsePersistedTaskImages(rawImages: unknown): TaskImage[] | undefined {
	const result = z.array(z.unknown()).safeParse(rawImages);
	if (!result.success) {
		return undefined;
	}

	const images = result.data.flatMap((rawImage) => {
		const image = runtimeTaskImageSchema.safeParse(rawImage);
		return image.success ? [image.data] : [];
	});
	return images.length > 0 ? images : undefined;
}

function parsePersistedBoardColumn(rawColumn: unknown): ParsedPersistedBoardColumn | null {
	const result = rawPersistedBoardColumnSchema.safeParse(rawColumn);
	if (!result.success) {
		return null;
	}

	const columnId = parseBoardColumnId(result.data.id);
	const cards = z.array(z.unknown()).safeParse(result.data.cards);
	if (!columnId || !cards.success) {
		return null;
	}

	return {
		id: columnId,
		cards: cards.data,
	};
}

function parseBoardColumnId(value: unknown): BoardColumnId | "backlog" | null {
	if (value === "backlog") return "backlog";
	const result = runtimeBoardColumnIdSchema.safeParse(value);
	return result.success ? result.data : null;
}

function parseNonEmptyString(value: unknown): string | null {
	return typeof value === "string" && value ? value : null;
}

function parseRequiredTrimmedString(value: unknown): string | null {
	if (typeof value !== "string") {
		return null;
	}
	const trimmed = value.trim();
	return trimmed ? trimmed : null;
}

function parseTrimmedString(value: unknown): string | null {
	return typeof value === "string" ? value.trim() : null;
}

function parseOptionalNullableString(value: unknown): string | null | undefined {
	if (typeof value === "string") {
		return value;
	}
	return value === null ? null : undefined;
}
